/* ------------------------------------------------------------------
   Engagement content: food, festivals, packing rules, quiz, i18n.
   ------------------------------------------------------------------ */
window.CONTENT = {
  food: [
    { name: 'Masala dosa', emoji: '🥞', region: 'Bengaluru', veg: true, spice: 1, price: '€1–3', text: 'Crisp fermented rice crêpe with spiced potato. Breakfast of the south — eat it at Vidyarthi Bhavan or MTR with filter coffee.' },
    { name: 'Filter coffee', emoji: '☕', region: 'Karnataka', veg: true, spice: 0, price: '€0.30', text: 'Chicory-blended, brewed in a steel filter and poured from a height to froth. Served in a tumbler-and-dabara set.' },
    { name: 'Goan fish thali', emoji: '🐟', region: 'Goa', veg: false, spice: 2, price: '€3–6', text: 'Fried kingfish, prawn curry, rice, kokum drink and pickles on one plate. Lunch-only at Ritz Classic, Anand or Vinayak.' },
    { name: 'Pork vindaloo', emoji: '🍖', region: 'Goa', veg: false, spice: 3, price: '€5–8', text: 'Portuguese "vinha d\'alhos" turned Goan — vinegar, garlic and Kashmiri chilli. Eat it with poi bread at Viva Panjim.' },
    { name: 'Kerala sadya', emoji: '🍃', region: 'Kerala', veg: true, spice: 1, price: '€2–5', text: 'Twenty-plus dishes on a banana leaf: avial, sambar, thoran, payasam. Eat with your right hand, banana at the end.' },
    { name: 'Appam & stew', emoji: '🥥', region: 'Kerala', veg: true, spice: 0, price: '€2–4', text: 'Lacy rice-coconut pancake with a soft centre, dipped in a mild coconut stew. The Munnar breakfast.' },
    { name: 'Karimeen pollichathu', emoji: '🌿', region: 'Backwaters', veg: false, spice: 2, price: '€6–10', text: 'Pearl-spot fish marinated in spices, wrapped in banana leaf and grilled. The houseboat classic.' },
    { name: 'Hyderabadi biryani', emoji: '🍛', region: 'Hyderabad', veg: false, spice: 2, price: '€3–6', text: 'Slow-cooked "dum" rice with marinated meat, saffron and fried onions. Paradise, Shah Ghouse or Bawarchi.' },
    { name: 'Mysore pak', emoji: '🍬', region: 'Mysuru', veg: true, spice: 0, price: '€1', text: 'Ghee, gram flour and sugar — melts in the mouth. Guru Sweets by Devaraja Market invented it for the Maharaja.' },
    { name: 'Benne dosa', emoji: '🧈', region: 'Davanagere / Bengaluru', veg: true, spice: 1, price: '€1–2', text: 'A softer, butter-drenched dosa from Davanagere. CTR in Malleshwaram is the Bengaluru pilgrimage.' },
    { name: 'Chettinad pepper chicken', emoji: '🌶️', region: 'Tamil Nadu', veg: false, spice: 3, price: '€4–7', text: 'Black pepper, star anise and stone-flower — the boldest spice blend in the south, from the Chettiar merchant kitchens.' },
    { name: 'Pandi curry', emoji: '🍲', region: 'Coorg', veg: false, spice: 2, price: '€4–6', text: 'Kodava pork curry darkened with kachampuli vinegar, eaten with kadambuttu rice dumplings at a coffee estate.' },
    { name: 'Bisi bele bath', emoji: '🍚', region: 'Karnataka', veg: true, spice: 2, price: '€1–3', text: 'Hot lentil-rice with vegetables, tamarind and a signature spice powder. Comfort food in every Bengaluru canteen.' },
    { name: 'Jigarthanda', emoji: '🥤', region: 'Madurai', veg: true, spice: 0, price: '€0.50', text: '"Heart-cooler": almond gum, milk, sarsaparilla syrup and ice cream. Famous Jigarthanda shop near the temple.' },
    { name: 'Vada pav', emoji: '🍔', region: 'Mumbai', veg: true, spice: 2, price: '€0.20', text: 'Spiced potato fritter in a bun with garlic chutney. Mumbai\'s burger — try Ashok Vada Pav in Dadar.' },
    { name: 'Laal maas', emoji: '🔥', region: 'Rajasthan', veg: false, spice: 3, price: '€6–10', text: 'Fiery mutton curry with Mathania chillies. Balance it with a makhaniya lassi in Jodhpur.' },
  ],

  /* November festival calendar (2026 dates; "approx" where the official date is announced late) */
  festivals: [
    { date: '2026-11-01', name: 'Karnataka Rajyotsava', where: 'Bengaluru & all Karnataka', text: 'State formation day: flags, processions, cultural shows on MG Road. Some shops close.', approx: false },
    { date: '2026-11-05', name: 'Hampi Utsav', where: 'Hampi', text: 'Three days of dance, music and light shows among the ruins. Usually early November — dates announced late, check.', approx: true },
    { date: '2026-11-08', name: 'Diwali / Deepavali', where: 'Everywhere', text: 'Festival of lights: oil lamps, sweets, fireworks. Some closures on the day; book hotels early for the week.', approx: false },
    { date: '2026-11-14', name: 'Children\'s Day', where: 'Everywhere', text: 'Not a holiday — but schools are on trips, so monuments are busier.', approx: false },
    { date: '2026-11-20', name: 'IFFI — International Film Festival of India', where: 'Panaji, Goa', text: 'Screenings, open-air shows and a festive Panaji for eight days (20–28 Nov).', approx: true },
    { date: '2026-11-21', name: 'Pushkar Camel Fair', where: 'Pushkar, Rajasthan', text: 'Camel trading, folk music and a full-moon fair. Peaks on Kartik Purnima (24 Nov).', approx: true },
    { date: '2026-11-24', name: 'Dev Deepawali & Guru Nanak Jayanti', where: 'Varanasi · Gurdwaras', text: 'A million lamps light the Varanasi ghats on Kartik Purnima. Sikh gurdwaras hold langar feasts.', approx: false },
    { date: '2026-11-28', name: 'Arpora Saturday Night Market opens', where: 'Arpora, Goa', text: 'The big night market season starts around late November — music, stalls, food.', approx: true },
    { date: '2026-12-01', name: 'Kochi-Muziris Biennale', where: 'Fort Kochi', text: 'India\'s biggest contemporary-art event, December to March in heritage warehouses.', approx: true },
  ],

  /* Packing rules — base list plus additions triggered by destination type or id */
  packing: {
    base: ['Passport + printed e-Visa + copies', 'Light cotton clothes, one smart outfit', 'Universal adapter (Type C/D/M), power bank', 'Sunscreen, sunglasses, hat', 'Mosquito repellent (DEET or picaridin)', 'ORS sachets, anti-diarrhoeal, paracetamol', 'Hand sanitiser & tissues', 'Reusable water bottle with filter', 'Small day-pack, padlock for lockers', 'Wise/Revolut card + backup card + some cash'],
    hills: ['Fleece or light down jacket (mornings 10–15 °C)', 'Rain jacket (NE-monsoon showers)', 'Walking shoes with grip', 'Motion-sickness tablets for ghat roads'],
    beach: ['Reef-safe sunscreen, rash vest', 'Sarong / cover-up for walking to shacks', 'Flip-flops + water shoes', 'Dry bag for boat trips'],
    wildlife: ['Muted-colour clothes (khaki, olive)', 'Binoculars', 'Warm layer for 06:00 safaris', 'Zoom lens or phone clip-on'],
    culture: ['Temple outfit: shoulders & knees covered', 'Socks for hot temple floors', 'Scarf / headcover for gurdwaras', 'Slip-on shoes (you remove them a lot)'],
    city: ['Comfortable trainers for long walks', 'Light scarf against evening AC', 'Small umbrella'],
    far: ['Warm layer for North Indian mornings (10 °C)', 'N95 mask for Delhi air quality', 'Extra memory cards — you will need them'],
    andaman: ['Snorkel mask (rental hygiene is patchy)', 'Waterproof phone pouch', 'Seasickness tablets for ferries'],
    kochi: ['Light long sleeves for houseboat mosquitoes'],
    rishikesh: ['Yoga clothes', 'Quick-dry towel for rafting'],
  },

  quiz: {
    questions: [
      { q: 'Your perfect morning on holiday starts with…', a: [
        { t: '🌊 Waves and a walk on the sand', s: { beach: 3 } },
        { t: '🌫️ Mist over hills and a cup of tea', s: { hills: 3 } },
        { t: '🛕 A temple bell and a busy market', s: { culture: 3 } },
        { t: '🐘 A 6 am jeep into the forest', s: { wildlife: 3 } } ] },
      { q: 'How do you feel about long drives?', a: [
        { t: '🚗 Love them — windows down, stops for chai', s: { hills: 2, wildlife: 2 } },
        { t: '✈️ Prefer a one-hour flight and done', s: { beach: 2, city: 2 } },
        { t: '🚆 Trains, please — I want to watch India go by', s: { culture: 2, far: 1 } },
        { t: '🛶 As long as there is a boat at the end', s: { hills: 1, beach: 1 } } ] },
      { q: 'Pick your dinner.', a: [
        { t: '🐟 Grilled fish at a beach shack', s: { beach: 3 } },
        { t: '🍃 A 20-dish sadya on a banana leaf', s: { hills: 2, culture: 1 } },
        { t: '🍛 Biryani or a royal thali in an old city', s: { culture: 2, city: 2, far: 1 } },
        { t: '☕ Estate dinner by a fire, coffee after', s: { hills: 2, wildlife: 1 } } ] },
      { q: 'Your group\'s energy level?', a: [
        { t: '😎 Slow — hammocks and one plan a day', s: { beach: 3 } },
        { t: '🥾 Active — hikes, sunrise points, safaris', s: { hills: 2, wildlife: 2 } },
        { t: '📸 Curious — ruins, palaces, stories', s: { culture: 3 } },
        { t: '🎉 Big — nightlife, markets, festivals', s: { city: 2, beach: 1, far: 1 } } ] },
      { q: 'What should the photos look like?', a: [
        { t: '🌅 Palm sunsets and turquoise water', s: { beach: 3 } },
        { t: '🍵 Endless green tea terraces', s: { hills: 3 } },
        { t: '🪨 Boulders, carved stone, golden light', s: { culture: 3 } },
        { t: '🏯 Forts, deserts and the Taj at dawn', s: { far: 3, culture: 1 } } ] },
    ],
    results: {
      beach:    { route: 'goa',      title: 'The Beach Soul', text: 'You want warmth, salt water and slow days. Goa is your route, with Gokarna or the Andamans if you have extra time.', picks: ['goa', 'gokarna', 'andaman'] },
      hills:    { route: 'kerala',   title: 'The Hill Wanderer', text: 'Cool air, tea estates and a houseboat night. Take the Tea Hills & Backwaters route, or swap in Coorg and Wayanad.', picks: ['munnar', 'coorg', 'wayanad'] },
      culture:  { route: 'heritage', title: 'The Heritage Hunter', text: 'Palaces, ruins and living temples. The Heritage & Coffee loop fits, with Hampi as the highlight.', picks: ['hampi', 'mysuru', 'madurai'] },
      wildlife: { route: 'kerala',   title: 'The Wild One', text: 'Dawn safaris and forest lodges. Build Kabini into the Heritage loop, or Thekkady into the Kerala route.', picks: ['kabini', 'thekkady', 'wayanad'] },
      city:     { route: 'goa',      title: 'The City Explorer', text: 'Food, markets, nightlife. Do Bengaluru properly, add Hyderabad or Mumbai, then finish on a Goa beach.', picks: ['hyderabad', 'mumbai', 'goa'] },
      far:      { route: 'golden', title: 'The Grand Tourist', text: 'You have time and want the icons: the Taj at dawn, Rajasthan\'s palaces, the Ganges at Varanasi.', picks: ['agra', 'udaipur', 'varanasi'] },
    },
  },

  /* German UI strings. Static HTML uses data-i18n keys; JS uses t('key'). */
  de: {
    'nav.flights': 'Flüge', 'nav.routes': 'Routen', 'nav.map': 'Karte', 'nav.destinations': 'Ziele', 'nav.food': 'Essen', 'nav.builder': 'Planen', 'nav.costs': 'Kosten', 'nav.safety': 'Sicherheit', 'nav.links': 'Links',
    'hero.eyebrow': 'Europa → Indien · richtig geplant',
    'hero.title': 'Europa nach Indien,<br /><span class="accent">richtig geplant.</span>',
    'hero.lead': 'Ein sicherer, komfortabler und detaillierter Reiseplan von jedem europäischen Flughafen nach ganz Indien: Gateway, Monat und Stil wählen — Routen, Hotels ab 4 Sternen, Kosten, Wetter und Buchungslinks passen sich an.',
    'hero.notYours': 'Nicht euer Flughafen?', 'nav.inspire': 'Entdecken', 'inspire.kicker': 'Erst die Bilder', 'inspire.h2': 'Wo möchtet ihr aufwachen?', 'inspire.p': 'Tippt auf das Herz bei den Orten, die euch anziehen. Wir machen daraus einen Plan.',
    'hero.cta1': 'Erst die Bilder ↓', 'hero.cta2': '💶 Kosten schätzen',
    'hero.s1': 'Flugzeit nonstop', 'hero.s2': 'im Reisemonat', 'hero.s3': 'Ziele ab BLR', 'hero.s4': '€ pro Person ab',
    'hero.legend1': 'Langstrecke ≈ 9 h', 'hero.legend2': 'Inland ≈ 1 h',
    'weather.kicker': 'Warum November', 'weather.h2': 'Der Monsun ist vorbei, die Massen kommen erst noch.', 'weather.p': 'Jeder Ort, bewertet für euren Monat.',
    'flights.kicker': 'Anreise', 'flights.h2': 'Von eurem Flughafen nach Indien', 'flights.p': 'Von eurem Flughafen zum Gateway, dann weiter.',
    'flights.arrive': '🛬 Ankunft',
    'flights.th1': 'Weiterreise', 'flights.th2': 'Dauer', 'flights.th3': 'Preis p. P.', 'flights.th4': 'Anbieter',
    'quiz.kicker': 'Kleiner Test', 'quiz.h2': 'Welche Reise passt zu euch?', 'quiz.p': 'Fünf Fragen, dreißig Sekunden, eine Route.',
    'routes.kicker': 'Reisepläne', 'routes.h2': 'Drei Routen, ein Tor.', 'routes.p': 'Fertige Pläne für euer Gateway. Einen wählen oder unten selbst bauen.',
    'map.kicker': 'Karte', 'map.h2': 'Alles, was von Bengaluru aus erreichbar ist.', 'map.p': 'Pin berühren für Zeit und Kosten ab eurem Gateway. Klicken zum Öffnen oder Hinzufügen.',
    'dest.kicker': 'Ziele', 'dest.h2': 'Wohin ihr wirklich fahrt.', 'dest.p': 'Nach Stimmung filtern, Karte antippen für den ganzen Guide.',
    'food.kicker': 'Essen', 'food.h2': 'Das müsst ihr probieren.', 'food.p': 'Sechzehn Gerichte, mit Schärfegrad und wo sie am besten sind.',
    'builder.kicker': 'Eure Reise', 'builder.h2': 'Baut euren eigenen Plan.', 'builder.p': 'Stopps antippen oder ziehen, Nächte setzen. Link mit der Gruppe teilen.',
    'costs.kicker': 'Kostenplaner', 'costs.h2': 'Was kostet das?', 'costs.p': 'Pro Person, Flüge inklusive, Doppelzimmer zu zweit. Eine Spanne, kein Angebot.',
    'dates.kicker': 'Eure Daten', 'dates.h2': 'Countdown, Feste & Packliste.', 'dates.p': 'Countdown, Feste in eurem Zeitraum und eine Packliste aus eurem Plan.',
    'safety.kicker': 'Sicher & entspannt', 'safety.h2': 'Reist, als wärt ihr schon mal da gewesen.', 'safety.p': 'Die paar Dinge, die den Unterschied machen.',
    'check.h3': '✅ Checkliste vor der Abreise', 'check.sub': 'Häkchen werden auf diesem Gerät gespeichert.',
    'links.kicker': 'Nützliche Links', 'links.h2': 'Alles, was ihr zum Buchen braucht.', 'links.p': 'Nur offizielle und bewährte Dienste.',
    'footer.note': 'Preise sind ungefähre Planungswerte in EUR — vor der Buchung prüfen. Keine Verbindung zu Airlines oder Hotels.',
    'label.travellers': 'Reisende', 'label.length': 'Reisedauer', 'label.style': 'Reisestil', 'label.departure': 'Abflug', 'label.route': 'Route',
    'result.label': 'Geschätzt pro Person', 'result.group': 'Ganze Gruppe',
    'builder.presets': 'Vorlage laden:', 'builder.pool': 'Stopp hinzufügen', 'builder.timeline': 'Eure Reihenfolge', 'builder.summary': 'Zusammenfassung', 'builder.share': 'Per WhatsApp teilen', 'builder.copy': 'Link kopieren', 'builder.print': 'Plan drucken / PDF', 'builder.clear': 'Zurücksetzen',
    'desk.kicker': 'Buchungsschalter', 'desk.h2': 'Alles buchen, in der richtigen Reihenfolge.', 'desk.p': 'Euer Plan als Buchungsliste, jeder Link vorausgefüllt.',
    'nav.desk': 'Buchen',
    'dates.label': 'Abflugdatum', 'dates.festivals': 'Feste während eurer Reise', 'dates.packing': 'Eure Packliste',
    'stamps.title': 'Euer Reisepass', 'stamps.sub': 'Jedes geöffnete Ziel gibt einen Stempel.',
  },

  /* English strings for JS-generated text (German equivalents in `de`) */
  en: {
    'quiz.start': 'Start the quiz', 'quiz.next': 'Question', 'quiz.of': 'of', 'quiz.again': 'Try again', 'quiz.route': 'See your route', 'quiz.share': 'Share on WhatsApp', 'quiz.picks': 'Three places for you',
    'builder.presets': 'Load a template:', 'builder.pool': 'Add a stop', 'builder.timeline': 'Your order', 'builder.summary': 'Summary', 'builder.share': 'Share on WhatsApp', 'builder.copy': 'Copy link', 'builder.print': 'Print / PDF', 'builder.clear': 'Reset',
    'builder.nights': 'nights', 'builder.days': 'days', 'builder.stops': 'stops', 'builder.travel': 'h of transfers', 'builder.perPerson': 'per person', 'builder.group': 'whole group', 'builder.empty': 'Tap a destination on the left (or drag it here) to start your plan.', 'builder.copied': 'Link copied!',
    'dates.days': 'days to go', 'dates.today': 'It\'s today — safe travels!', 'dates.gone': 'Already departed — enjoy!', 'dates.none': 'No festivals in your window — but every day has a temple ceremony somewhere.', 'dates.approx': 'approx.',
    'stamps.of': 'of', 'stamps.stamped': 'STAMPED', 'stamps.new': 'New stamp!',
    'rate.live': 'live rate', 'rate.fixed': 'approx. rate',
    'map.explore': 'Explore', 'map.add': 'Add to trip', 'map.fail': 'The map needs an internet connection to load tiles.',
    'check.done': 'done', 'check.all': 'All packed — have an amazing trip! 🎉',
    'dest.places': 'places', 'dest.place': 'place',
    'set.origin': 'Flying from', 'set.country': 'Home country', 'set.arrive': 'Arrive in', 'set.depart': 'Depart from', 'set.month': 'Travelling in', 'set.date': 'Departure date', 'set.people': 'Travellers', 'set.style': 'Style', 'set.currency': 'Currency', 'set.apply': 'Update plan', 'set.title': 'Your trip settings', 'set.same': 'same as arrival',
    'flights.nonstop': 'Nonstop', 'flights.onestop': 'One stop via', 'flights.none': 'No nonstop — connect via', 'flights.time': 'Time difference', 'flights.arriveNote': 'Most European arrivals land between 01:00 and 04:00 — book the first hotel from the night before and arrange a hotel pickup.',
    'month.best': 'Best time', 'month.good': 'Good', 'month.ok': 'Possible', 'month.avoid': 'Avoid', 'month.in': 'in', 'dest.bestOnly': 'Best this month',
    'comfort.title': 'Safety & comfort', 'comfort.score': 'Comfort score', 'comfort.hospital': 'Nearest good hospital',
    'safety.country': 'For travellers from', 'safety.advice': 'Official travel advice', 'safety.register': 'Register your trip', 'safety.embassy': 'Embassy in New Delhi', 'safety.consulates': 'Consulates in', 'safety.health': 'Health advice', 'safety.noneNear': 'No consulate near your gateway — the embassy in New Delhi covers all of India.',
    'leg.flight': 'Flight', 'leg.road': 'Private car with driver', 'leg.train': 'Train', 'leg.flightroad': 'Flight + car', 'leg.hours': 'h door to door',
    'gw.arrive': 'Arrival gateway', 'gw.depart': 'Departure gateway',
    'rating.on': 'Showing only {min}+ rated places with {count}+ Google reviews', 'rating.off': 'Live rating filter ({min}+, {count}+ reviews) is off — deploy the ratings service (see worker/README.md)', 'rating.loading': 'Checking live ratings…', 'rating.fail': 'Could not reach the ratings service — showing unfiltered picks', 'rating.hidden': 'show {n} hidden by the filter', 'rating.hide': 'hide {n} below the filter', 'rating.none': 'no rating found',
    'guide.eat': 'Where to eat', 'guide.eatNone': 'Meals are at your lodge here — nothing to rate.',
    'guide.picks': 'Our picks', 'guide.picksNote': 'Chosen for location, service and consistently strong public reviews. Tap through to check before you book.', 'guide.allHotels': 'All hotels on Booking.com', 'guide.maps': 'Open in Maps', 'guide.around': 'Getting around & booking ahead',
    'tier.budget': 'Budget', 'tier.mid': 'Comfort · 4★', 'tier.lux': 'Luxury · 5★',
    'desk.intl': 'International flights', 'desk.hop': 'Getting there', 'desk.stay': 'Stay', 'desk.book': 'Book ahead', 'desk.flight': 'Flight', 'desk.road': 'Car with driver', 'desk.train': 'Train / bus', 'desk.nights': 'nights', 'desk.rooms': 'rooms', 'desk.booked': 'Booked', 'desk.progress': 'booked', 'desk.empty': 'Build a plan above and set a departure date — the booking desk fills itself in.', 'desk.return': 'return', 'desk.from': 'from', 'desk.google': 'Google Flights', 'desk.sky': 'Skyscanner', 'desk.booking': 'Booking.com', 'desk.ghotels': 'Google Hotels', 'desk.picks': 'Our picks', 'desk.12go': '12Go (trains & buses)', 'desk.savaari': 'Savaari (car & driver)', 'desk.irctc': 'IRCTC (trains)', 'desk.noDate': 'Set a departure date to prefill exact dates.',
    'wx.now': 'Now', 'wx.trip': 'Your dates', 'wx.lastNov': 'Last November', 'wx.rainy': 'rainy days', 'wx.rain': 'rain chance', 'wx.by': 'Live weather & forecasts by Open-Meteo', 'wx.updated': 'updated', 'wx.soon': 'Forecast appears 16 days before your dates',
  },
  deJs: {
    'quiz.start': 'Test starten', 'quiz.next': 'Frage', 'quiz.of': 'von', 'quiz.again': 'Nochmal', 'quiz.route': 'Zur Route', 'quiz.share': 'Per WhatsApp teilen', 'quiz.picks': 'Drei Ziele für euch',
    'builder.presets': 'Vorlage laden:', 'builder.pool': 'Stopp hinzufügen', 'builder.timeline': 'Eure Reihenfolge', 'builder.summary': 'Zusammenfassung', 'builder.share': 'Per WhatsApp teilen', 'builder.copy': 'Link kopieren', 'builder.print': 'Drucken / PDF', 'builder.clear': 'Zurücksetzen',
    'builder.nights': 'Nächte', 'builder.days': 'Tage', 'builder.stops': 'Stopps', 'builder.travel': 'h Transfers', 'builder.perPerson': 'pro Person', 'builder.group': 'ganze Gruppe', 'builder.empty': 'Tippt links auf ein Ziel (oder zieht es hierher), um zu starten.', 'builder.copied': 'Link kopiert!',
    'dates.days': 'Tage bis zum Abflug', 'dates.today': 'Heute geht\'s los — gute Reise!', 'dates.gone': 'Schon unterwegs — viel Spaß!', 'dates.none': 'Keine Feste in eurem Zeitraum — aber irgendwo ist immer Tempelfest.', 'dates.approx': 'ca.',
    'stamps.of': 'von', 'stamps.stamped': 'GESTEMPELT', 'stamps.new': 'Neuer Stempel!',
    'rate.live': 'Live-Kurs', 'rate.fixed': 'ca. Kurs',
    'map.explore': 'Öffnen', 'map.add': 'Zur Reise', 'map.fail': 'Die Karte braucht Internet, um Kacheln zu laden.',
    'check.done': 'erledigt', 'check.all': 'Alles gepackt — gute Reise! 🎉',
    'dest.places': 'Orte', 'dest.place': 'Ort',
    'set.origin': 'Abflug ab', 'set.country': 'Heimatland', 'set.arrive': 'Ankunft in', 'set.depart': 'Abflug ab', 'set.month': 'Reisemonat', 'set.date': 'Abflugdatum', 'set.people': 'Reisende', 'set.style': 'Stil', 'set.currency': 'Währung', 'set.apply': 'Plan aktualisieren', 'set.title': 'Eure Reiseeinstellungen', 'set.same': 'wie Ankunft',
    'flights.nonstop': 'Nonstop', 'flights.onestop': 'Ein Umstieg via', 'flights.none': 'Kein Nonstop — Umstieg via', 'flights.time': 'Zeitunterschied', 'flights.arriveNote': 'Die meisten Flüge aus Europa landen zwischen 01:00 und 04:00 — erstes Hotel ab der Vornacht buchen und Hotelabholung bestellen.',
    'month.best': 'Beste Zeit', 'month.good': 'Gut', 'month.ok': 'Möglich', 'month.avoid': 'Vermeiden', 'month.in': 'im', 'dest.bestOnly': 'Beste diesen Monat',
    'comfort.title': 'Sicherheit & Komfort', 'comfort.score': 'Komfort-Score', 'comfort.hospital': 'Nächstes gutes Krankenhaus',
    'safety.country': 'Für Reisende aus', 'safety.advice': 'Offizielle Reisehinweise', 'safety.register': 'Reise registrieren', 'safety.embassy': 'Botschaft in Neu-Delhi', 'safety.consulates': 'Konsulate in', 'safety.health': 'Gesundheitshinweise', 'safety.noneNear': 'Kein Konsulat nahe eurem Gateway — die Botschaft in Neu-Delhi ist für ganz Indien zuständig.',
    'leg.flight': 'Flug', 'leg.road': 'Privatwagen mit Fahrer', 'leg.train': 'Zug', 'leg.flightroad': 'Flug + Auto', 'leg.hours': 'h Tür zu Tür',
    'gw.arrive': 'Ankunfts-Gateway', 'gw.depart': 'Abflug-Gateway',
    'rating.on': 'Nur Orte mit {min}+ Sternen und {count}+ Google-Bewertungen', 'rating.off': 'Live-Bewertungsfilter ({min}+, {count}+ Bewertungen) ist aus — Ratings-Service einrichten (siehe worker/README.md)', 'rating.loading': 'Live-Bewertungen werden geprüft…', 'rating.fail': 'Ratings-Service nicht erreichbar — ungefilterte Auswahl', 'rating.hidden': '{n} vom Filter ausgeblendete anzeigen', 'rating.hide': '{n} unter dem Filter ausblenden', 'rating.none': 'keine Bewertung gefunden',
    'guide.eat': 'Essen gehen', 'guide.eatNone': 'Hier wird in der Lodge gegessen — nichts zu bewerten.',
    'guide.picks': 'Unsere Empfehlungen', 'guide.picksNote': 'Ausgewählt nach Lage, Service und durchgehend guten öffentlichen Bewertungen. Vor dem Buchen die aktuellen Bewertungen ansehen.', 'guide.allHotels': 'Alle Hotels auf Booking.com', 'guide.maps': 'In Maps öffnen', 'guide.around': 'Unterwegs & vorab buchen',
    'tier.budget': 'Budget', 'tier.mid': 'Komfort · 4★', 'tier.lux': 'Luxus · 5★',
    'desk.intl': 'Internationale Flüge', 'desk.hop': 'Anreise', 'desk.stay': 'Unterkunft', 'desk.book': 'Vorab buchen', 'desk.flight': 'Flug', 'desk.road': 'Auto mit Fahrer', 'desk.train': 'Zug / Bus', 'desk.nights': 'Nächte', 'desk.rooms': 'Zimmer', 'desk.booked': 'Gebucht', 'desk.progress': 'gebucht', 'desk.empty': 'Baut oben einen Plan und wählt ein Abflugdatum — der Buchungsschalter füllt sich von selbst.', 'desk.return': 'zurück', 'desk.from': 'ab', 'desk.google': 'Google Flights', 'desk.sky': 'Skyscanner', 'desk.booking': 'Booking.com', 'desk.ghotels': 'Google Hotels', 'desk.picks': 'Unsere Empfehlungen', 'desk.12go': '12Go (Züge & Busse)', 'desk.savaari': 'Savaari (Auto & Fahrer)', 'desk.irctc': 'IRCTC (Züge)', 'desk.noDate': 'Abflugdatum setzen, um genaue Daten vorzufüllen.',
    'wx.now': 'Jetzt', 'wx.trip': 'Eure Daten', 'wx.lastNov': 'Letzter November', 'wx.rainy': 'Regentage', 'wx.rain': 'Regenrisiko', 'wx.by': 'Live-Wetter & Prognosen von Open-Meteo', 'wx.updated': 'aktualisiert', 'wx.soon': 'Prognose erscheint 16 Tage vor euren Daten',
  },
};
