/* ------------------------------------------------------------------
   Data for the Europe → South India (November) travel planner.
   All prices are approximate, per person, in EUR unless noted, and
   were written as planning estimates — always re-check live prices.
   ------------------------------------------------------------------ */

window.TRIP = {
  eurToInr: 98, // fallback; the page fetches a live rate when online
  photos: [],   // ids that have a real photo at img/<id>.jpg, e.g. ['goa', 'hampi']
  /* Live ratings filter for hotels & restaurants. Deploy worker/ and paste its URL here.
     Empty string = filter off (curated lists shown unfiltered). */
  ratingsEndpoint: '',
  ratingFilter: { min: 4.0, minCount: 100 },

  /* Arrival / departure gateways with nonstop links from Europe (see europe.js for the other side) */
  gateways: [
    { code: 'BLR', city: 'Bengaluru', dest: 'bengaluru', note: 'Best for the south: Kerala, Goa, Karnataka, Tamil Nadu.' },
    { code: 'DEL', city: 'Delhi', dest: 'delhi', note: 'Best for the north: Golden Triangle, Rajasthan, Varanasi, Himalaya.' },
    { code: 'BOM', city: 'Mumbai', dest: 'mumbai', note: 'Best for the west: Goa, Rajasthan by air, Kerala.' },
    { code: 'MAA', city: 'Chennai', dest: 'chennai', note: 'Tamil temple trail, Pondicherry, Andamans.' },
    { code: 'HYD', city: 'Hyderabad', dest: 'hyderabad', note: 'Central India; easy hop to Hampi, Goa, Bengaluru.' },
    { code: 'COK', city: 'Kochi', dest: 'kochi', note: 'Straight into Kerala (one stop via the Gulf).' },
    { code: 'CCU', city: 'Kolkata', dest: 'kolkata', note: 'East and north-east: Darjeeling, Sikkim, Varanasi.' },
    { code: 'GOI', city: 'Goa', dest: 'goa', note: 'Beach first (one stop via the Gulf / seasonal charters).' },
  ],
  monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  regions: { south: 'South India', west: 'West coast', north: 'North India', east: 'East & North-east', central: 'Central India', islands: 'Islands' },

  weather: [
    { id: 'bengaluru', place: 'Bengaluru', temp: '18–27 °C', note: 'Mild, breezy, mostly dry. Light showers possible in the first week.', icon: '⛅', rating: 'great' },
    { id: 'goa', place: 'Goa', temp: '23–33 °C', note: 'Dry, sunny, sea calm — the season kicks off in November.', icon: '☀️', rating: 'great' },
    { id: 'munnar', place: 'Munnar', temp: '12–22 °C', note: 'Cool, misty mornings. Some NE-monsoon showers in early November, clearing later.', icon: '🌫️', rating: 'good' },
    { id: 'kochi', place: 'Kochi / Alleppey', temp: '24–31 °C', note: 'Warm and humid, occasional evening showers, backwaters full and green.', icon: '🌦️', rating: 'good' },
    { id: 'coorg', place: 'Mysuru / Coorg', temp: '15–28 °C', note: 'Fresh, post-monsoon greenery, coffee harvest begins.', icon: '🌤️', rating: 'great' },
    { id: 'hampi', place: 'Hampi', temp: '18–31 °C', note: 'Dry and clear — ideal for walking the ruins.', icon: '☀️', rating: 'great' },
    { id: 'hyderabad', place: 'Hyderabad', temp: '18–30 °C', note: 'Dry, sunny, crisp evenings — great city weather.', icon: '☀️', rating: 'great' },
    { id: 'andaman', place: 'Andaman Islands', temp: '24–30 °C', note: 'Post-monsoon calm seas and good visibility for diving.', icon: '🏝️', rating: 'great' },
    { id: 'agra', place: 'Delhi / Agra / Jaipur', temp: '12–28 °C', note: 'Ideal temperatures, but Delhi smog peaks in November.', icon: '🌤️', rating: 'good' },
    { id: 'pondicherry', place: 'Pondicherry / Chennai', temp: '24–30 °C', note: 'Peak NE-monsoon rain in November. Better in January.', icon: '🌧️', rating: 'skip' },
  ],

  destinations: [
    {
      id: 'bengaluru', region: 'south', airport: 'BLR', via: null, priceIndex: 1.0, months: [3, 3, 2, 1, 1, 2, 2, 2, 2, 2, 3, 3], comfort: { score: 5, hospital: 'Manipal Hospital (Old Airport Road) · Apollo Bannerghatta', notes: ['Very safe, cosmopolitan city; Uber/Ola reliable at all hours.', 'Traffic is the main hazard — allow double the map time.', 'Air quality moderate; better than Delhi in every month.'] }, lat: 12.97, lng: 77.59, hours: 0, transfer: 0, type: 'city', from: 'Your arrival airport', nights: '2 nights', name: 'Bengaluru', tag: 'Your gateway city', emoji: '🏙️',
      hue: 'linear-gradient(135deg,#6366f1,#a855f7)',
      weather: '18–27 °C · mild & breezy',
      intro: 'India\'s garden city and tech capital. Great coffee, craft breweries, parks and easy first-day pace to shake off the jet lag.',
      todo: ['Cubbon Park & the red-brick High Court at dawn', 'Lalbagh Botanical Garden glasshouse', 'Bangalore Palace (Tudor-style, Wodeyar royals)', 'Church Street & Commercial Street browsing', 'Sunrise at Nandi Hills (60 km, leave 04:30)', 'VV Puram food street in the evening'],
      food: ['Masala dosa & filter coffee at MTR or Vidyarthi Bhavan', 'Andhra meals on a banana leaf at Nagarjuna', 'Craft beer & wood-fired pizza at Toit, Indiranagar', 'Coastal seafood at Karavalli (Taj)'],
      stay: { budget: 'Zostel / The Hosteller (Indiranagar) €12–25 pp', mid: 'Lemon Tree, ibis, The Park · €60–110 per room', lux: 'Taj West End, ITC Gardenia, The Leela Palace · €200–400' },
      area: 'Stay in Indiranagar, Koramangala or around MG Road — walkable, lively, well connected by Metro and Uber.',
      perDay: '€35 – 120',
    },
    {
      id: 'goa', region: 'west', airport: 'GOI', via: null, priceIndex: 1.2, months: [3, 3, 2, 1, 0, 0, 0, 0, 1, 2, 3, 3], comfort: { score: 4, hospital: 'Manipal Hospital Goa (Panaji) · Victor Hospital (Margao)', notes: ['Use Goa Miles or hotel taxis; avoid scooters after dark and never after drinking.', 'Swim only at lifeguarded beaches (Drishti flags); rip currents are real.', 'Petty theft at beach shacks — leave valuables in the hotel safe.'] }, lat: 15.49, lng: 73.83, hours: 1.2, transfer: 130, type: 'beach', from: '1 h 10 flight', nights: '4–5 nights', name: 'Goa', tag: 'Beaches, forts & Portuguese lanes', emoji: '🏖️',
      hue: 'linear-gradient(135deg,#f59e0b,#ef4444)',
      weather: '23–33 °C · dry & sunny',
      intro: 'Palm-lined beaches, 450 years of Portuguese heritage, night markets and the best seafood on the west coast. November is the sweet spot: dry, warm, not yet crowded.',
      todo: ['Sunset from Chapora Fort over Vagator', 'Ashwem & Morjim beaches (quiet, turtle nesting zone)', 'Old Goa: Basilica of Bom Jesus & Sé Cathedral (UNESCO)', 'Fontainhas Latin Quarter walk in Panaji', 'Dudhsagar Falls jeep safari + spice plantation lunch', 'Palolem & Agonda in the south — kayaking, dolphin boats', 'Anjuna Wednesday flea market · Arpora Saturday night market', 'IFFI film festival in Panaji (late Nov)'],
      food: ['Goan fish thali at Ritz Classic or Anand', 'Prawn balchão, pork vindaloo, xacuti at Viva Panjim', 'Beach-shack grilled kingfish & feni cocktails', 'Bebinca dessert, poi bread from a village bakery'],
      stay: { budget: 'Hostels & guesthouses in Anjuna/Palolem · €10–30', mid: 'Boutique villas in Assagao, Novotel Candolim · €70–140', lux: 'W Goa, Taj Fort Aguada, Alila Diwa, Ahilya by the Sea · €220–450' },
      area: 'North (Assagao/Anjuna/Vagator) for nightlife & cafés; South (Palolem/Agonda) for calm beaches. Rent a scooter (€6/day) or use Goa Miles taxis.',
      perDay: '€40 – 150',
    },
    {
      id: 'munnar', region: 'south', airport: null, via: 'COK', priceIndex: 1.1, months: [3, 3, 2, 2, 1, 0, 0, 0, 2, 2, 2, 3], comfort: { score: 4, hospital: 'Tata General Hospital Munnar (basic) · Aster Medcity Kochi (4 h)', notes: ['Winding roads: take a car with an experienced hill driver, travel by day.', 'Nearest full hospital is in Kochi — carry any prescription medicine.', 'Cool nights; leeches on forest walks in the wet months.'] }, lat: 10.09, lng: 77.06, hours: 5, transfer: 150, type: 'hills', from: '1 h flight to Kochi + 4 h drive', nights: '2–3 nights', name: 'Munnar', tag: 'Tea hills at 1,600 m', emoji: '🍃',
      hue: 'linear-gradient(135deg,#10b981,#0f766e)',
      weather: '12–22 °C · cool & misty',
      intro: 'Rolling tea estates, cloud forest and cool air — a full change of climate from the coast. Pack a fleece for mornings.',
      todo: ['Eravikulam National Park — endangered Nilgiri tahr', 'Sunrise jeep to Kolukkumalai, the world\'s highest tea estate', 'KDHP Tea Museum & tea tasting', 'Mattupetty Dam, Echo Point, Top Station viewpoint', 'Lockhart Gap & Anamudi peak views', 'Guided estate walk with a planter'],
      food: ['Kerala sadya on banana leaf', 'Appam with vegetable stew for breakfast', 'Fresh-picked cardamom tea', 'Beef fry & parotta (Kerala classic)'],
      stay: { budget: 'Homestays in Chinnakanal / Pallivasal · €20–40', mid: 'Tea Valley Resort, Elixir Hills · €70–130', lux: 'Windermere Estate, Spice Tree, KDHP Tea Bungalows · €180–350' },
      area: 'From Kochi airport: 4 h scenic drive (110 km). Hire a car with driver (€60–90 per day for the group). Roads are winding — motion-sickness tablets help.',
      perDay: '€35 – 140',
    },
    {
      id: 'kochi', region: 'south', airport: 'COK', via: null, priceIndex: 1.2, months: [3, 3, 2, 1, 0, 0, 0, 1, 2, 2, 2, 3], comfort: { score: 5, hospital: 'Aster Medcity · Amrita Hospital (both world-class)', notes: ['Calm, walkable Fort Kochi; safe for evening strolls.', 'Houseboats: book licensed operators with life jackets on board.', 'Humid — hydrate; mosquito repellent at dusk on the backwaters.'] }, lat: 9.93, lng: 76.27, hours: 1.1, transfer: 130, type: 'culture', from: '1 h 05 flight', nights: '2–3 nights', name: 'Kochi & Alleppey', tag: 'Spice port & backwaters', emoji: '⛵',
      hue: 'linear-gradient(135deg,#0ea5e9,#2563eb)',
      weather: '24–31 °C · warm & humid',
      intro: 'Fort Kochi\'s colonial lanes and Chinese fishing nets, then a night on a houseboat gliding through Alleppey\'s palm-fringed canals.',
      todo: ['Chinese fishing nets at sunset, Fort Kochi', 'Mattancherry Palace & Jew Town synagogue', 'Kathakali performance at Kerala Kathakali Centre', 'Kochi-Muziris Biennale art (Dec–Mar, check dates)', 'Overnight houseboat, Alleppey → Kumarakom', 'Village canoe tour through the narrow canals', 'Marari Beach sunset'],
      food: ['Karimeen pollichathu (pearl spot fish in banana leaf)', 'Fish moilee & prawn curry on the houseboat', 'Puttu & kadala curry breakfast', 'Seafood at Fort House or Oceanos'],
      stay: { budget: 'Fort Kochi homestays · €20–35', mid: 'Fort House Hotel, Old Harbour Hotel · €80–150 · Houseboat €90–160 per night (whole boat, 2 pax)', lux: 'Brunton Boatyard, Taj Malabar, Marari Beach Resort, Kumarakom Lake Resort · €200–450' },
      area: 'Alleppey is 1.5 h from Kochi. Book houseboats through a reputed operator (Spice Routes, Lakes & Lagoons) and board around noon.',
      perDay: '€40 – 160',
    },
    {
      id: 'thekkady', region: 'south', airport: null, via: 'COK', priceIndex: 1.0, months: [3, 3, 2, 2, 1, 0, 0, 1, 2, 2, 2, 3], comfort: { score: 4, hospital: 'Kumily taluk hospital (basic) · Kottayam / Madurai for anything serious', notes: ['Park treks only with forest-department guides.', 'Wild elephants on the roads at dusk — no night driving.'] }, lat: 9.6, lng: 77.16, hours: 8, transfer: 40, type: 'wildlife', from: '3 h from Munnar', nights: '1–2 nights', name: 'Thekkady (Periyar)', tag: 'Wildlife & spice gardens', emoji: '🐘',
      hue: 'linear-gradient(135deg,#84cc16,#15803d)',
      weather: '18–28 °C · fresh',
      intro: 'A perfect bridge between Munnar and the backwaters: a lake safari in Periyar Tiger Reserve, spice plantations and Kalaripayattu martial-arts shows.',
      todo: ['Periyar Lake boat safari (elephants, bison, hornbills)', 'Guided spice-garden walk (cardamom, pepper, vanilla)', 'Kalaripayattu & Kathakali evening show', 'Bamboo rafting or border-hike with forest guides'],
      food: ['Pepper chicken', 'Home-style Syrian Christian fish curry', 'Fresh spice tea'],
      stay: { budget: 'Kumily guesthouses · €20–35', mid: 'Greenwoods Resort, Cardamom County · €70–130', lux: 'Spice Village (CGH Earth), Niraamaya · €180–300' },
      area: '3 h from Munnar, 4 h to Alleppey. Add 1 night if you have time.',
      perDay: '€35 – 130',
    },
    {
      id: 'mysuru', region: 'south', airport: null, via: 'BLR', priceIndex: 0.8, months: [3, 3, 2, 1, 1, 2, 2, 2, 2, 3, 3, 3], comfort: { score: 5, hospital: 'Apollo BGS Hospital · JSS Hospital', notes: ['One of the cleanest, safest cities in India.', 'Palace crowds on Sundays — keep bags in front.'] }, lat: 12.3, lng: 76.65, hours: 2, transfer: 25, type: 'culture', from: '2 h train', nights: '1–2 nights', name: 'Mysuru', tag: 'Palaces, silk & sandalwood', emoji: '🏰',
      hue: 'linear-gradient(135deg,#f43f5e,#be185d)',
      weather: '17–28 °C · pleasant',
      intro: 'Karnataka\'s royal city, 2 h from Bengaluru by fast train. The Maharaja\'s Palace lit by 100,000 bulbs on Sunday evenings is unforgettable.',
      todo: ['Mysore Palace (Sunday 19:00 illumination)', 'Chamundi Hill temple & the giant Nandi', 'Devaraja Market — jasmine, spices, kumkum', 'Srirangapatna: Tipu Sultan\'s summer palace', 'Brindavan Gardens musical fountain', 'Ashtanga yoga class (Mysuru is the birthplace)'],
      food: ['Mysore pak sweet at Guru Sweets', 'Mysore masala dosa at Mylari', 'Filter coffee & benne dosa'],
      stay: { budget: 'Zostel Mysuru, guesthouses · €10–25', mid: 'Royal Orchid Metropole (heritage) · €70–110', lux: 'Radisson Blu Plaza, Grand Mercure · €110–180' },
      area: 'Book the Vande Bharat / Shatabdi train from Bengaluru KSR station. Autos and Uber cover the city.',
      perDay: '€30 – 100',
    },
    {
      id: 'coorg', region: 'south', airport: null, via: 'BLR', priceIndex: 1.3, months: [3, 3, 2, 2, 1, 0, 0, 0, 2, 2, 3, 3], comfort: { score: 4, hospital: 'Madikeri district hospital (basic) · Mysuru 3 h for serious care', notes: ['No ride-hailing; use hotel cars. Roads are narrow and unlit at night.', 'Estate stays are remote — good for peace, check driving distances.'] }, lat: 12.42, lng: 75.74, hours: 5.5, transfer: 60, type: 'hills', from: '5–6 h drive', nights: '2 nights', name: 'Coorg (Kodagu)', tag: 'Coffee estates & waterfalls', emoji: '☕',
      hue: 'linear-gradient(135deg,#a16207,#78350f)',
      weather: '15–25 °C · fresh & green',
      intro: 'The "Scotland of India": misty coffee plantations, Kodava culture and estate homestays where the harvest starts in November.',
      todo: ['Stay on a working coffee estate', 'Abbey Falls & Raja\'s Seat sunset', 'Dubare Elephant Camp (ethical morning visit)', 'Namdroling Golden Temple, Bylakuppe Tibetan settlement', 'Talacauvery river source & Bhagamandala', 'Coffee-roasting walk and tasting'],
      food: ['Pandi curry (Kodava pork) with kadambuttu rice balls', 'Estate-grown coffee', 'Akki roti with coconut chutney'],
      stay: { budget: 'Homestays around Madikeri · €25–45', mid: 'Coorg Wilderness Resort, Amanvana · €90–160', lux: 'Evolve Back Coorg, Taj Madikeri Resort & Spa · €250–450' },
      area: '3 h drive from Mysuru, 6 h from Bengaluru. Private car for the group is the practical choice.',
      perDay: '€40 – 150',
    },
    {
      id: 'hampi', region: 'south', airport: 'VDY', via: null, priceIndex: 1.1, months: [3, 3, 2, 0, 0, 1, 1, 1, 2, 3, 3, 3], comfort: { score: 3, hospital: 'Hosapete district hospital (basic) · Bengaluru for serious care', notes: ['Ruins are spread out and hot — start at dawn, carry water.', 'Coracle rides: agree price first; life jackets are not always offered.', 'Very limited nightlife and medical care — plan for that.'] }, lat: 15.34, lng: 76.46, hours: 7, transfer: 60, type: 'culture', from: 'Night train or 1 h flight', nights: '2 nights', name: 'Hampi', tag: 'UNESCO ruins among boulders', emoji: '🪨',
      hue: 'linear-gradient(135deg,#f97316,#c2410c)',
      weather: '18–31 °C · dry & clear',
      intro: 'The 14th-century capital of the Vijayanagara empire — temples, royal baths and a stone chariot scattered across a surreal boulder landscape.',
      todo: ['Vittala Temple & the stone chariot', 'Sunrise on Matanga Hill', 'Virupaksha Temple & Hampi Bazaar', 'Coracle ride on the Tungabhadra river', 'Cycle or e-bike tour of the Royal Enclosure', 'Sunset at Hemakuta Hill; Sanapur lake cliff-jumping'],
      food: ['Mango Tree restaurant thalis', 'Cafés across the river in Sanapur / Hippie Island', 'North Karnataka jolada rotti meals'],
      stay: { budget: 'Guesthouses in Hampi Bazaar & Sanapur · €10–25', mid: 'Heritage Resort Hampi, Hampi\'s Boulders · €60–120', lux: 'Evolve Back Kamalapura Palace · €250–400' },
      area: 'Hampi Express night train from Bengaluru (2AC ≈ €15) or 1 h flight to Vidyanagar. Hire a tuk-tuk or bikes for the ruins.',
      perDay: '€30 – 120',
    },
    /* ---------- More places reachable from Bengaluru ---------- */
    {
      id: 'hyderabad', region: 'south', airport: 'HYD', via: null, priceIndex: 1.0, months: [3, 3, 2, 1, 0, 1, 2, 2, 2, 3, 3, 3], comfort: { score: 5, hospital: 'Apollo Jubilee Hills · KIMS · Yashoda', notes: ['Safe, orderly city with excellent hospitals.', 'Old City is crowded at dusk — go with a guide, keep phones secured.'] }, lat: 17.39, lng: 78.49, hours: 1, transfer: 110, type: 'city', from: '1 h flight', nights: '2 nights', name: 'Hyderabad', tag: 'Nizams, forts & biryani', emoji: '🕌',
      hue: 'linear-gradient(135deg,#7c3aed,#4c1d95)',
      weather: '18–30 °C · dry & sunny',
      intro: 'The city of the Nizams: a 16th-century old town around the Charminar, a hilltop fort, palaces full of treasure and the most famous biryani in India — an hour\'s flight from Bengaluru.',
      todo: ['Charminar & Laad Bazaar bangle lanes at dusk', 'Golconda Fort sound-and-light show', 'Chowmahalla Palace & Salar Jung Museum', 'Qutb Shahi Tombs', 'Hussain Sagar lake & Necklace Road', 'Ramoji Film City (full day, optional)'],
      food: ['Hyderabadi dum biryani at Paradise, Shah Ghouse or Bawarchi', 'Haleem & Irani chai with Osmania biscuits', 'Qubani ka meetha (apricot dessert)'],
      stay: { budget: 'Hostels & guesthouses in Banjara Hills · €12–30', mid: 'Lemon Tree, ITC Kakatiya, Marriott · €70–130', lux: 'Taj Falaknuma Palace, Park Hyatt · €250–600' },
      area: 'IndiGo / Air India fly BLR → HYD hourly (1 h, €30–70). Uber everywhere; the old city is best explored on foot with a guide.',
      perDay: '€35 – 130',
    },
    {
      id: 'ooty', region: 'south', airport: null, via: 'CJB', priceIndex: 0.9, months: [3, 3, 3, 3, 2, 1, 1, 1, 2, 2, 2, 3], comfort: { score: 4, hospital: 'Government hospital Ooty (basic) · Coimbatore 3 h for serious care', notes: ['Ghat road through Bandipur closes 21:00–06:00; travel by day.', 'Cold nights (5–10 °C in winter); altitude 2,200 m.'] }, lat: 11.41, lng: 76.7, hours: 7, transfer: 70, type: 'hills', from: '7 h drive · or 1 h flight to Coimbatore + 3 h', nights: '2–3 nights', name: 'Ooty & Coonoor', tag: 'Nilgiri toy train & tea', emoji: '🚂',
      hue: 'linear-gradient(135deg,#22c55e,#166534)',
      weather: '8–20 °C · cool, some rain',
      intro: 'The Nilgiri hills at 2,200 m: a UNESCO-listed steam mountain railway, colonial bungalows, eucalyptus forests and quiet tea town Coonoor. Cold nights — bring layers.',
      todo: ['Nilgiri Mountain Railway (Mettupalayam → Coonoor → Ooty) — book weeks ahead', 'Doddabetta Peak, the highest in the Nilgiris', 'Coonoor: Sim\'s Park, Lamb\'s Rock, Dolphin\'s Nose', 'Government Botanical Garden & Rose Garden', 'Tea factory visit & homemade chocolate tasting', 'Avalanche Lake & Emerald Lake (permit day trip)'],
      food: ['Varkey biscuits & Ooty chocolate', 'Badaga cuisine in a homestay', 'Nilgiri honey and fresh estate tea'],
      stay: { budget: 'YWCA Anandagiri, guesthouses · €15–35', mid: 'Sinclairs Retreat, Gem Park · €60–110', lux: 'Savoy (Taj), Kurumba Village Resort, Wallwood Garden (Coonoor) · €140–250' },
      area: 'Drive via Mysuru and Bandipur (wildlife sightings on the ghat road; the forest gate closes 21:00–06:00). Alternatively fly to Coimbatore and take the toy train up.',
      perDay: '€35 – 120',
    },
    {
      id: 'kabini', region: 'south', airport: null, via: 'BLR', priceIndex: 1.6, months: [3, 3, 3, 3, 3, 1, 0, 0, 1, 2, 3, 3], comfort: { score: 4, hospital: 'Mysuru hospitals (1.5 h)', notes: ['Lodges are fenced and well run; follow naturalists\' instructions on safari.', 'Malaria risk is low but use repellent at dawn and dusk.'] }, lat: 12.02, lng: 76.3, hours: 5, transfer: 60, type: 'wildlife', from: '5 h drive', nights: '2 nights', name: 'Kabini & Nagarhole', tag: 'Tigers, leopards & elephants', emoji: '🐆',
      hue: 'linear-gradient(135deg,#65a30d,#365314)',
      weather: '17–29 °C · dry, prime season',
      intro: 'One of India\'s best big-cat parks. Jeep and boat safaris on the Kabini backwaters from November, when the water is high and elephant herds gather on the banks.',
      todo: ['Morning & evening jeep safaris in Nagarhole (tiger, leopard, wild dog)', 'Boat safari on the Kabini reservoir', 'Coracle ride & birdwatching (300+ species)', 'Kuruba tribal village visit', 'Combine with Mysuru (1.5 h) or Bandipur'],
      food: ['Lodge buffets — full board is standard here', 'Karnataka ragi mudde & bisi bele bath'],
      stay: { budget: 'Kabini Springs, homestays in Antharasanthe · €40–70 with safaris', mid: 'Red Earth Kabini, Kaav Safari Lodge · €120–200 full board', lux: 'Evolve Back Kabini, Kabini River Lodge (JLR, classic) · €250–450 full board' },
      area: 'Lodges arrange safaris — book them with the stay, not separately. Forest safaris run ~06:30 and ~15:30; wear muted colours.',
      perDay: '€60 – 250',
    },
    {
      id: 'chikmagalur', region: 'south', airport: null, via: 'BLR', priceIndex: 1.1, months: [3, 3, 2, 2, 1, 0, 0, 0, 2, 3, 3, 3], comfort: { score: 4, hospital: 'Chikmagalur district hospital (basic) · Bengaluru 4.5 h', notes: ['Estate roads are rough; a car with driver is essential.', 'Cool, quiet, very safe; limited restaurants outside resorts.'] }, lat: 13.32, lng: 75.77, hours: 4.5, transfer: 60, type: 'hills', from: '4.5 h drive', nights: '2 nights', name: 'Chikmagalur', tag: 'Birthplace of Indian coffee', emoji: '🌄',
      hue: 'linear-gradient(135deg,#b45309,#451a03)',
      weather: '15–27 °C · fresh, clear',
      intro: 'Coffee was first planted in India here in the 1600s. Karnataka\'s highest peak, waterfalls, ancient Hoysala temples nearby and quieter than Coorg.',
      todo: ['Mullayanagiri sunrise (1,930 m, highest point in Karnataka)', 'Baba Budangiri hills & Manikyadhara Falls', 'Hebbe Falls jeep ride (through estates)', 'Belur & Halebidu Hoysala temples (1 h, extraordinary carving)', 'Coffee estate tour & cupping', 'Bhadra Wildlife Sanctuary boat safari'],
      food: ['Estate-roasted filter coffee', 'Malnad meals: akki roti, kadubu, pandi curry', 'Chikmagalur\'s famous benne dosa'],
      stay: { budget: 'Estate homestays · €25–45', mid: 'Trivik Hotels, Java Rain Resorts · €90–170', lux: 'The Serai Chikmagalur, Eka Resort · €180–320' },
      area: 'Best paired with Belur/Halebidu on the way from Bengaluru. A private car for two days covers everything.',
      perDay: '€40 – 160',
    },
    {
      id: 'gokarna', region: 'west', airport: null, via: 'GOI', priceIndex: 0.9, months: [3, 3, 2, 1, 0, 0, 0, 0, 1, 2, 3, 3], comfort: { score: 3, hospital: 'Gokarna primary care only · Manipal Hospital Goa 3 h', notes: ['Beach paths between coves are rocky — walk them in daylight.', 'Sea can be rough; no lifeguards on the smaller beaches.', 'Simple infrastructure — choose SwaSwara or Kahani for comfort.'] }, lat: 14.55, lng: 74.32, hours: 8, transfer: 40, type: 'beach', from: '8 h drive · overnight sleeper bus · 1 h flight to Goa + 3 h', nights: '2–3 nights', name: 'Gokarna', tag: 'Goa without the crowds', emoji: '🌊',
      hue: 'linear-gradient(135deg,#06b6d4,#0e7490)',
      weather: '22–32 °C · dry & sunny',
      intro: 'A temple town with a string of crescent beaches reached by a cliff-top trail: Kudle, Om, Half Moon and Paradise. Slower and cheaper than Goa; ideal for a few unplanned days.',
      todo: ['Beach trek Kudle → Om → Half Moon → Paradise (start early)', 'Sunset at Om Beach', 'Mahabaleshwar Temple & the old town lanes', 'Kayaking, surfing lessons at Kudle', 'Yana rocks & Mirjan Fort day trip'],
      food: ['Beach-shack thalis & fresh fish', 'Namaste Café on Om Beach', 'Kokum juice and coconut water everywhere'],
      stay: { budget: 'Beach huts & Zostel Gokarna · €8–25', mid: 'Namaste Sanjeevini, Arya Ayurvedic Resort · €50–100', lux: 'Kahani Paradise, SwaSwara (CGH Earth, wellness) · €180–350' },
      area: 'Overnight KSRTC / private sleeper bus from Bengaluru (€12–20) is the classic route. Combine with Goa: Goa → Gokarna is 3 h by road.',
      perDay: '€25 – 120',
    },
    {
      id: 'wayanad', region: 'south', airport: null, via: 'CCJ', priceIndex: 1.1, months: [3, 3, 2, 2, 1, 0, 0, 0, 2, 2, 3, 3], comfort: { score: 4, hospital: 'Kozhikode (Calicut) hospitals 2 h', notes: ['Landslide-prone in the monsoon — avoid June–August.', 'Wildlife on roads at night; stick to daytime transfers.'] }, lat: 11.61, lng: 76.08, hours: 6, transfer: 60, type: 'hills', from: '6 h drive', nights: '2 nights', name: 'Wayanad', tag: 'Rainforest, caves & treehouses', emoji: '🌿',
      hue: 'linear-gradient(135deg,#059669,#064e3b)',
      weather: '18–28 °C · green, some showers',
      intro: 'Kerala\'s green plateau: prehistoric cave art, spice farms, bamboo rafting and resorts built into the forest canopy. A quieter alternative to Munnar closer to Bengaluru.',
      todo: ['Edakkal Caves — 6,000-year-old petroglyphs', 'Chembra Peak heart-shaped lake trek (permit)', 'Banasura Sagar dam & the earth dam viewpoint', 'Bamboo raft to Kuruva Island', 'Tea & spice plantation walk', 'Tholpetty wildlife safari'],
      food: ['Kerala breakfast: puttu, idiyappam, egg curry', 'Wayanadan chicken & bamboo-rice payasam', 'Homestay dinners'],
      stay: { budget: 'Homestays around Vythiri / Kalpetta · €20–40', mid: 'Vythiri Village, Pepper Trail estate · €80–150', lux: 'Vythiri Resort treehouses, Taj Wayanad, Wayanad Wild (CGH) · €180–350' },
      area: 'Drive via Mysuru and Bandipur; the road is beautiful but slow. Pair with Kabini (2.5 h) or Coorg (3 h).',
      perDay: '€35 – 140',
    },
    {
      id: 'varkala', region: 'south', airport: null, via: 'TRV', priceIndex: 1.0, months: [3, 3, 2, 1, 0, 0, 0, 1, 2, 2, 3, 3], comfort: { score: 4, hospital: 'KIMS Health Trivandrum (1 h)', notes: ['Cliff path has no railings in places — care at night.', 'Strong currents at Papanasam; swim near lifeguards.'] }, lat: 8.73, lng: 76.72, hours: 2.5, transfer: 150, type: 'beach', from: '1 h 15 flight to Trivandrum + 1 h', nights: '2–3 nights', name: 'Varkala & Kovalam', tag: 'Cliff beaches & Ayurveda', emoji: '🏄',
      hue: 'linear-gradient(135deg,#f472b6,#be185d)',
      weather: '24–31 °C · warm, calming sea',
      intro: 'Kerala\'s red laterite cliff drops straight onto Papanasam beach, lined with cafés and yoga shalas. Perfect for a restorative end to a trip — Ayurvedic massage, surf, sunsets.',
      todo: ['Cliff-top walk & sunset at Varkala', 'Ayurveda treatment (2–7 day programmes)', 'Surf or SUP lesson at Kappil', 'Jatayu Earth\'s Center giant sculpture (cable car)', 'Kovalam lighthouse beach', 'Padmanabhaswamy Temple in Trivandrum (dress code strict)'],
      food: ['Cliff cafés: fresh seafood grilled to order', 'Kerala fish curry with tapioca', 'Coffee Temple for breakfast'],
      stay: { budget: 'Cliff guesthouses · €12–30', mid: 'Palm Tree Heritage, Clafouti · €50–100', lux: 'Taj Green Cove (Kovalam), Niraamaya Surya Samudra, The Leela Kovalam · €200–400' },
      area: 'Fly BLR → Trivandrum (TRV), then 1 h taxi. Kochi is 4 h north — combine with the Kerala route.',
      perDay: '€30 – 150',
    },
    {
      id: 'andaman', region: 'islands', airport: 'IXZ', via: null, priceIndex: 1.5, months: [3, 3, 3, 2, 1, 0, 0, 0, 1, 2, 3, 3], comfort: { score: 4, hospital: 'GB Pant Hospital Port Blair (basic); serious cases are flown to Chennai', notes: ['Book only government-registered dive and ferry operators.', 'No decompression chamber on Havelock — dive conservatively and no flying within 24 h.', 'Mobile coverage is patchy; download maps offline.'] }, lat: 11.62, lng: 92.73, hours: 2.5, transfer: 240, type: 'beach', from: '2 h 30 flight to Port Blair', nights: '5–6 nights', name: 'Andaman Islands', tag: 'Turquoise water & coral reefs', emoji: '🐠',
      hue: 'linear-gradient(135deg,#0ea5e9,#0369a1)',
      weather: '24–30 °C · post-monsoon calm seas',
      intro: 'Direct flights from Bengaluru make the Andamans a realistic add-on: white-sand Radhanagar Beach, world-class scuba, mangrove kayaking and the moving Cellular Jail history in Port Blair.',
      todo: ['Radhanagar Beach, Havelock (Swaraj Dweep) — on every best-beach list', 'Scuba diving / snorkelling at Elephant Beach & Neil Island', 'Cellular Jail & the evening light-and-sound show', 'Bioluminescence night kayak in the mangroves', 'Ross Island ruins & Chidiya Tapu sunset', 'Ferry hopping: Port Blair → Havelock → Neil'],
      food: ['Grilled lobster and crab at Havelock beach restaurants', 'Bengali-style fish curries', 'Fresh coconut everything'],
      stay: { budget: 'Beach huts & hostels on Havelock · €15–35', mid: 'SeaShell, Silver Sand · €80–150', lux: 'Taj Exotica Andamans, Barefoot at Havelock, Jalakara (boutique) · €250–600' },
      area: 'IndiGo / Air India fly BLR → IXZ (Port Blair) nonstop (2.5 h, €70–150). Book Makruzz / Nautika ferries ahead. Foreigners need no permit for the main islands; carry passport & visa copies.',
      perDay: '€50 – 220',
    },
    {
      id: 'madurai', region: 'south', airport: 'IXM', via: null, priceIndex: 0.8, months: [3, 3, 2, 1, 0, 1, 2, 2, 2, 1, 1, 2], comfort: { score: 4, hospital: 'Apollo Speciality Madurai · Meenakshi Mission Hospital', notes: ['Temple lanes are crowded; bags in front, shoes in the paid stand.', 'Hot — sightsee early and late.'] }, lat: 9.93, lng: 78.12, hours: 1, transfer: 130, type: 'culture', from: '1 h flight · 7 h drive', nights: '2–3 nights', name: 'Madurai & Chettinad', tag: 'Living temple city', emoji: '🛕',
      hue: 'linear-gradient(135deg,#f59e0b,#b91c1c)',
      weather: '24–31 °C · warm, NE-monsoon showers',
      intro: 'One of the oldest continuously inhabited cities on earth, built around the towering Meenakshi Amman Temple. Add the crumbling Chettinad mansions and their famous spicy cuisine.',
      todo: ['Meenakshi Temple — the 21:00 night ceremony', 'Thirumalai Nayakkar Palace', 'Banana market & flower market at dawn', 'Chettinad: Karaikudi mansions, Athangudi tile factory (2 h)', 'Rameswaram & the Pamban bridge day trip (3 h)', 'Gandhi Memorial Museum'],
      food: ['Chettinad chicken & pepper mutton', 'Jigarthanda (cold almond-milk drink) at Famous Jigarthanda', 'Kari dosa, paruthi paal, idli at Murugan Idli Shop'],
      stay: { budget: 'Temple-area guesthouses · €10–25', mid: 'Heritage Madurai, Courtyard by Marriott · €60–120', lux: 'Chettinad mansions: The Bangala, Visalam (CGH Earth) · €120–220' },
      area: 'IndiGo flies BLR → IXM (Madurai) in 1 h. Temples: no shorts, shoes off, cameras restricted inside.',
      perDay: '€30 – 110',
    },
    {
      id: 'badami', region: 'south', airport: null, via: 'HBX', priceIndex: 0.7, months: [3, 3, 2, 0, 0, 1, 1, 1, 2, 3, 3, 3], comfort: { score: 3, hospital: 'Bagalkot district hospital (basic) · Hubli 2 h', notes: ['Rural area with few services; combine with Hampi and a good car.', 'Monkeys at the caves — keep food and glasses out of sight.'] }, lat: 15.92, lng: 75.68, hours: 7, transfer: 70, type: 'culture', from: '7 h drive · 1 h flight to Hubli + 2 h', nights: '1–2 nights', name: 'Badami, Aihole & Pattadakal', tag: '6th-century rock-cut temples', emoji: '🏛️',
      hue: 'linear-gradient(135deg,#dc2626,#7f1d1d)',
      weather: '19–31 °C · dry & clear',
      intro: 'The cradle of Indian temple architecture: sandstone cave temples above a green lake at Badami, the UNESCO complex at Pattadakal and 120 experimental temples at Aihole. A natural add-on to Hampi.',
      todo: ['Badami cave temples at sunrise', 'Bhutanatha temples reflected in Agastya Lake', 'Pattadakal (UNESCO) — Dravidian meets Nagara style', 'Aihole Durga temple & Ravanaphadi cave', 'Rock climbing on Badami sandstone', 'Continue to Hampi (2.5 h)'],
      food: ['North Karnataka jolada rotti & ennegai (stuffed brinjal)', 'Girmit (spiced puffed rice) street snack'],
      stay: { budget: 'Guesthouses in Badami town · €10–25', mid: 'Heritage Resort Badami, Clarks Inn · €50–90', lux: 'Stay at Hampi (Evolve Back) and day-trip · €250–400' },
      area: 'Hire a car from Hampi for a Badami loop, or fly BLR → Hubli (1 h) and drive 2 h.',
      perDay: '€30 – 100',
    },
    {
      id: 'pondicherry', region: 'south', airport: null, via: 'MAA', priceIndex: 1.0, months: [3, 3, 2, 1, 0, 1, 1, 1, 2, 0, 0, 2], comfort: { score: 4, hospital: 'JIPMER (excellent teaching hospital)', notes: ['Cyclone season Oct–Dec — check IMD warnings before driving down.', 'White Town is calm and safe on foot at night.'] }, lat: 11.93, lng: 79.83, hours: 6, transfer: 60, type: 'beach', from: '6 h drive · 1 h flight to Chennai + 3 h', nights: '2 nights', name: 'Pondicherry', tag: 'French Quarter by the sea', emoji: '🇫🇷',
      hue: 'linear-gradient(135deg,#fbbf24,#f97316)',
      weather: '24–30 °C · rainiest month — late Nov onwards only',
      intro: 'Mustard-yellow colonial villas, bougainvillea, croissants and a seaside promenade — plus the experimental township of Auroville. Charming, but November is the wettest month here; go in the last week or save it for another trip.',
      todo: ['White Town heritage walk & Rue Romain Rolland', 'Auroville Matrimandir (book the viewing point ahead)', 'Promenade Beach at sunrise', 'Sri Aurobindo Ashram', 'Surfing at Serenity Beach', 'Paradise Beach boat trip (weather permitting)'],
      food: ['French bakeries: Baker Street, Zuka chocolate', 'Creole dishes at Villa Shanti & Le Dupleix', 'Tamil filter coffee and idli'],
      stay: { budget: 'Guesthouses & ashram rooms · €12–30', mid: 'Villa Shanti, Le Dupleix, Palais de Mahé (CGH) · €80–160', lux: 'La Villa, Maison Perumal · €150–250' },
      area: 'Drive from Bengaluru is 6 h (leave early). Check the forecast: cyclone alerts are common in November.',
      perDay: '€30 – 120',
    },
    {
      id: 'goldentriangle', region: 'north', airport: 'AGR', via: null, priceIndex: 1.4, months: [2, 3, 3, 1, 0, 0, 1, 1, 2, 3, 2, 2], comfort: { score: 4, hospital: 'Medanta Gurugram · Max Saket (Delhi); Apollo Jaipur', notes: ['Touts at the Taj and Amber Fort: book official guides only.', 'Delhi air quality is severe Nov–Jan — masks, and limit Delhi nights.', 'Use pre-booked cars; avoid unmetered taxis at stations.'] }, lat: 27.18, lng: 78.01, hours: 2.7, transfer: 260, type: 'far', from: '2 h 40 flight to Delhi', nights: '5–6 nights', name: 'Delhi, Agra & Jaipur', tag: 'The Golden Triangle', emoji: '🕌',
      hue: 'linear-gradient(135deg,#ef4444,#9a3412)',
      weather: '12–28 °C · perfect season, Delhi smog risk',
      intro: 'If the group has 6 spare days, North India in November is at its best: Taj Mahal at dawn, Mughal Delhi, Rajasthan\'s pink city. Caveat: Delhi\'s air quality is often very poor in November — keep Delhi short and spend nights in Agra and Jaipur.',
      todo: ['Taj Mahal sunrise & Agra Fort', 'Fatehpur Sikri on the road to Jaipur', 'Amber Fort, Hawa Mahal, City Palace, Jaipur', 'Humayun\'s Tomb, Qutb Minar, Old Delhi food walk', 'Gatore cenotaphs & a block-printing workshop', 'Overnight in a Rajasthani heritage haveli'],
      food: ['Old Delhi: Karim\'s, parathe wali gali, chaat', 'Agra petha; Jaipur dal baati churma & laal maas', 'Lassi at Lassiwala, Jaipur'],
      stay: { budget: 'Hostels & havelis · €15–35', mid: 'Trident Agra / Jaipur, Samode Haveli · €90–180', lux: 'Oberoi Amarvilas (Taj view), Rambagh Palace, The Imperial · €350–900' },
      area: 'Fly BLR → DEL (2.5 h, €50–120). Private car with driver for the loop (≈ €300–400 for the group), or Gatimaan Express train Delhi → Agra (1 h 40). Fly back to BLR from Jaipur.',
      perDay: '€45 – 250',
    },
    {
      id: 'rajasthan', region: 'north', airport: 'UDR', via: null, priceIndex: 1.5, months: [3, 3, 2, 1, 0, 0, 1, 1, 2, 3, 3, 3], comfort: { score: 4, hospital: 'Apollo Jaipur · GBH American Hospital Udaipur', notes: ['Well-worn tourist circuit with excellent hotels and drivers.', 'Bargain firmly but politely; ignore “government emporium” claims.', 'Dry heat in Mar–Apr; carry water.'] }, lat: 24.58, lng: 73.71, hours: 2.5, transfer: 250, type: 'far', from: '2 h 30 flight to Udaipur', nights: '5–6 nights', name: 'Udaipur & Jodhpur', tag: 'Lake palaces & the blue city', emoji: '🏯',
      hue: 'linear-gradient(135deg,#f59e0b,#7c2d12)',
      weather: '12–30 °C · dry, ideal',
      intro: 'Rajasthan in November is close to perfect: cool mornings, golden light on Udaipur\'s lake palaces, the towering Mehrangarh Fort above Jodhpur\'s blue houses, and the Jain marble temples of Ranakpur in between.',
      todo: ['Sunset boat on Lake Pichola & City Palace, Udaipur', 'Mehrangarh Fort and the blue lanes of Jodhpur (zip line over the fort)', 'Ranakpur Jain temple & Kumbhalgarh wall on the drive between the two', 'Bagore ki Haveli folk dance show', 'Block-printing workshop & bazaars', 'Pushkar Camel Fair (mid–late Nov, 4 h from Udaipur) if dates align'],
      food: ['Laal maas & dal baati churma', 'Mirchi vada and makhaniya lassi in Jodhpur', 'Rooftop dinner with a lake view at Ambrai'],
      stay: { budget: 'Zostel & havelis · €12–35', mid: 'Jagat Niwas, Raas Jodhpur, Jaipur\'s havelis · €90–200', lux: 'Taj Lake Palace, Umaid Bhawan Palace, Leela Palace Udaipur · €400–1,200' },
      area: 'IndiGo flies BLR → UDR nonstop (2.5 h, €60–130). Udaipur → Jodhpur is 5 h by car via Ranakpur. Fly back from Jodhpur (JDH) or Jaipur.',
      perDay: '€45 – 300',
    },
    {
      id: 'varanasi', region: 'north', airport: 'VNS', via: null, priceIndex: 1.1, months: [2, 3, 3, 1, 0, 0, 1, 1, 2, 3, 3, 3], comfort: { score: 3, hospital: 'Heritage Hospital · BHU Sir Sunderlal Hospital', notes: ['Intense crowds at the ghats; hire a licensed boatman via the hotel.', 'Do not drink or swim in the river; keep valuables minimal.', 'Stay on the riverfront in a heritage hotel for a calm base.'] }, lat: 25.32, lng: 83.01, hours: 2.5, transfer: 220, type: 'far', from: '2 h 30 flight', nights: '2–3 nights', name: 'Varanasi', tag: 'Ghats, fire & the Ganges', emoji: '🪔',
      hue: 'linear-gradient(135deg,#fb923c,#7f1d1d)',
      weather: '14–29 °C · pleasant, misty dawns',
      intro: 'The oldest living city in the world, and the most intense. A sunrise rowing boat past the ghats, the evening Ganga aarti fire ceremony, silk lanes and Buddhist Sarnath. In late November 2026 it hosts Dev Deepawali, when a million lamps light the ghats.',
      todo: ['Sunrise boat along the ghats', 'Ganga aarti at Dashashwamedh Ghat (arrive 17:30)', 'Old-city walking tour: Kashi Vishwanath lanes, Manikarnika', 'Sarnath — where the Buddha first taught', 'Banarasi silk weaving workshop', 'Dev Deepawali (Kartik Purnima, ≈ 24 Nov 2026)'],
      food: ['Kachori-sabzi breakfast & Blue Lassi', 'Banarasi paan and malaiyo (winter cream dessert)', 'Thali at Baati Chokha'],
      stay: { budget: 'Hostels near Assi Ghat · €8–25', mid: 'Ganpati Guest House, Suryauday Haveli (riverfront) · €60–130', lux: 'BrijRama Palace, Taj Ganges, Taj Nadesar Palace · €200–450' },
      area: 'IndiGo flies BLR → VNS nonstop (2.5 h, €60–130). Stay on the riverfront. It is crowded and unfiltered — keep valuables close and hire a licensed boatman.',
      perDay: '€30 – 180',
    },
    {
      id: 'rishikesh', region: 'north', airport: null, via: 'DED', priceIndex: 1.2, months: [2, 3, 3, 3, 2, 0, 0, 0, 2, 3, 3, 2], comfort: { score: 4, hospital: 'AIIMS Rishikesh (major hospital)', notes: ['Rafting only with licensed operators, helmets and life jackets.', 'Vegetarian and alcohol-free town — plan expectations.', 'Monkeys on the bridges: hold on to bags and glasses.'] }, lat: 30.09, lng: 78.27, hours: 3.5, transfer: 230, type: 'far', from: '3 h flight to Dehradun + 45 min', nights: '3 nights', name: 'Rishikesh', tag: 'Yoga, rafting & the Himalayan foothills', emoji: '🧘',
      hue: 'linear-gradient(135deg,#34d399,#1e3a8a)',
      weather: '10–26 °C · crisp, clear, rafting season',
      intro: 'Where the Ganges leaves the Himalayas. Yoga ashrams, white-water rafting at its best in November, suspension bridges, the graffiti-covered Beatles Ashram and the great evening aarti at Haridwar down the road.',
      todo: ['White-water rafting (Shivpuri → Rishikesh, grade II–III)', 'Sunrise yoga class or a 3-day ashram taster', 'Beatles Ashram (Chaurasi Kutia) street art', 'Triveni Ghat evening aarti', 'Rajaji National Park jeep safari', 'Har Ki Pauri aarti in Haridwar (45 min)'],
      food: ['Vegetarian only in town: thalis, Chotiwala', 'Cafés on the Laxman Jhula side: Little Buddha, Beatles Café', 'Fresh juices, no alcohol served'],
      stay: { budget: 'Ashrams & Zostel Rishikesh · €8–25', mid: 'Aloha on the Ganges, Divine Resort · €60–120', lux: 'Ananda in the Himalayas (spa), Taj Rishikesh · €250–700' },
      area: 'Fly BLR → Dehradun (DED, 3 h, €60–130), then 45 min taxi. Rafting operators: book a morning slot; November water is cold but clear.',
      perDay: '€30 – 250',
    },
    {
      id: 'mumbai', region: 'west', airport: 'BOM', via: null, priceIndex: 1.4, months: [3, 3, 2, 1, 0, 0, 0, 0, 1, 2, 3, 3], comfort: { score: 5, hospital: 'Breach Candy · Lilavati · Jaslok (all excellent)', notes: ['Safe, busy city; Uber and metered taxis reliable at any hour.', 'Avoid local trains at rush hour; use cabs.', 'Monsoon flooding in July–August disrupts everything.'] }, lat: 19.08, lng: 72.88, hours: 1.5, transfer: 130, type: 'city', from: '1 h 30 flight', nights: '2–3 nights', name: 'Mumbai', tag: 'Art-deco seafront & street food', emoji: '🌆',
      hue: 'linear-gradient(135deg,#f43f5e,#1e293b)',
      weather: '22–33 °C · dry, humid evenings',
      intro: 'India\'s biggest, fastest city: the Gateway of India, sunset on Marine Drive, Elephanta\'s cave temples by ferry, Bandra\'s cafés and the best street food in the country. Also a smart place to end the trip — Mumbai has many nonstop flights to Europe.',
      todo: ['Gateway of India & the Taj Mahal Palace hotel', 'Marine Drive sunset walk to Chowpatty', 'Elephanta Caves ferry (UNESCO)', 'Kala Ghoda art district & Colaba Causeway', 'Bandra street art & Bandstand', 'Dhobi Ghat & a Dharavi community walk (ethical operator)'],
      food: ['Vada pav & pav bhaji at Chowpatty', 'Parsi café breakfast at Britannia or Kyani', 'Modern Indian at The Bombay Canteen', 'Seafood at Trishna or Gajalee'],
      stay: { budget: 'Hostels in Colaba · €12–30', mid: 'Abode Bombay, Residency Fort, Gordon House · €80–160', lux: 'Taj Mahal Palace, The Oberoi, Soho House Mumbai · €250–600' },
      area: 'Flights BLR → BOM every 30 min (1.5 h, €30–80). Use Uber; local trains are an experience but avoid rush hour. Lufthansa and SWISS fly Mumbai → Frankfurt / Zurich nonstop.',
      perDay: '€40 – 220',
    },
    {
      id: 'delhi', region: 'north', airport: 'DEL', via: null, priceIndex: 1.2, months: [2,3,3,1,0,0,1,1,2,3,2,2], comfort: { score: 4, hospital: 'Medanta Gurugram · Max Saket · Apollo Indraprastha', notes: ['Use hotel cars or Uber; never accept “your hotel is closed” stories.', 'Air quality is severe Nov–Jan: masks, short stays, indoor evenings.', 'Women: prefer pre-booked cars after dark; the Metro has women\'s carriages.'] }, lat: 28.61, lng: 77.21, hours: 2.7, transfer: 130, type: 'city', from: '2 h 40 flight', nights: '2 nights', name: 'Delhi', tag: 'Mughal capital & modern metropolis', emoji: '🕌',
      hue: 'linear-gradient(135deg,#dc2626,#4c1d95)',
      weather: '12–28 °C in Nov · smog season',
      intro: 'Seven cities layered on one another: Mughal tombs, Lutyens\' boulevards, the spice lanes of Old Delhi and India\'s best restaurants. The gateway to the north — keep it to two nights in winter because of the air.',
      todo: ['Humayun\'s Tomb & Lodhi Garden at sunrise', 'Old Delhi walk: Jama Masjid, Chandni Chowk, spice market', 'Qutb Minar complex', 'India Gate & the Rajpath at dusk', 'Hauz Khas village & Khan Market shopping', 'National Museum or the Crafts Museum'],
      food: ['Karim\'s kebabs and nihari', 'Chaat at Bengali Market', 'Indian Accent or Bukhara for a big night out'],
      stay: { budget: '—', mid: 'The Lodhi, Taj Mahal Delhi · €150–300', lux: 'The Oberoi New Delhi, The Imperial, Leela Palace · €300–600' },
      area: 'Stay in Lutyens\' Delhi (Chanakyapuri, Lodhi Road) or Aerocity by the airport for a short stop. Metro is clean and fast; cars for the old city.',
      perDay: '€60 – 300',
    },
    {
      id: 'chennai', region: 'south', airport: 'MAA', via: null, priceIndex: 0.9, months: [3,2,1,0,0,0,1,1,2,1,0,2], comfort: { score: 4, hospital: 'Apollo Greams Road (India\'s best-known hospital) · MIOT', notes: ['Hot and humid most of the year; November brings heavy northeast-monsoon rain.', 'Safe, conservative city; dress modestly at temples and beaches.'] }, lat: 13.08, lng: 80.27, hours: 1, transfer: 110, type: 'city', from: '1 h flight', nights: '1–2 nights', name: 'Chennai', tag: 'Tamil culture & the Coromandel coast', emoji: '🏛️',
      hue: 'linear-gradient(135deg,#0ea5e9,#7c2d12)',
      weather: '24–30 °C in Nov · rainy',
      intro: 'The cultural capital of Tamil Nadu: Carnatic music, silk, Dravidian temples and a 13-km beach. Best as a gateway to Mahabalipuram, Pondicherry and the temple trail — outside the Oct–Dec monsoon.',
      todo: ['Mahabalipuram shore temples (UNESCO, 1.5 h)', 'Kapaleeshwarar Temple & Mylapore lanes', 'Marina Beach at dawn', 'Kanchipuram silk weavers (day trip)', 'DakshinaChitra heritage village', 'Music season concerts (Dec–Jan)'],
      food: ['Filter coffee and idli at Murugan Idli or Saravana Bhavan', 'Chettinad at Anjappar', 'Seafood at Bay View, Taj Fisherman\'s Cove'],
      stay: { budget: '—', mid: 'Hyatt Regency, Taj Club House · €100–180', lux: 'ITC Grand Chola, Taj Fisherman\'s Cove (beach) · €180–400' },
      area: 'British Airways flies nonstop from London. Stay in Nungambakkam or on the ECR coast; use Uber.',
      perDay: '€50 – 250',
    },
    {
      id: 'kolkata', region: 'east', airport: 'CCU', via: null, priceIndex: 0.9, months: [3,3,2,1,0,0,0,1,1,3,3,3], comfort: { score: 4, hospital: 'Apollo Gleneagles · AMRI · Fortis Anandapur', notes: ['Friendly, intellectual city; safe by Indian big-city standards.', 'Durga Puja (Oct) is magical but crowds and traffic are extreme — book far ahead.', 'Humid; the Oct–Feb window is the comfortable one.'] }, lat: 22.57, lng: 88.36, hours: 2.5, transfer: 150, type: 'city', from: '2 h 30 flight', nights: '2–3 nights', name: 'Kolkata', tag: 'Colonial grandeur & Bengali culture', emoji: '🎭',
      hue: 'linear-gradient(135deg,#f59e0b,#1e3a8a)',
      weather: '18–29 °C in Nov · pleasant',
      intro: 'The former capital of British India: crumbling colonial palaces, Victoria Memorial, the world\'s busiest bridge, sweet shops and a fierce love of books, film and football. Gateway to Darjeeling and the north-east.',
      todo: ['Victoria Memorial & the Maidan', 'Kumartuli idol-makers\' quarter', 'Howrah Bridge at dawn & Mullick Ghat flower market', 'College Street bookshops & the Indian Coffee House', 'Park Street dinner and jazz', 'Sundarbans mangrove day trip (tigers, boats)'],
      food: ['Kathi rolls at Nizam\'s', 'Bengali thali at 6 Ballygunge Place or Bhojohori Manna', 'Rosogolla and mishti doi at Balaram Mullick'],
      stay: { budget: '—', mid: 'The Park, Taj Bengal · €90–180', lux: 'The Oberoi Grand, ITC Royal Bengal, Glenburn Penthouse · €180–400' },
      area: 'Fly via a Gulf hub or from Delhi/Mumbai. Yellow Ambassador taxis are an experience; Uber is easier.',
      perDay: '€45 – 220',
    },
  ],

  routes: [
    {
      id: 'goa', gateway: 'BLR', months: [10, 11, 12, 1, 2, 3], name: 'Sun & Spice', subtitle: 'Bengaluru → Goa', days: 10,
      emoji: '🏖️', accent: '#f59e0b',
      summary: 'The easy, sociable itinerary: two days to settle in Bengaluru, then a short flight to Goa for beaches, Portuguese history, seafood and markets.',
      stats: { flights: '2 domestic', pace: 'Relaxed', cost: '€1,250 – 2,100 pp' },
      itinerary: [
        { day: 1, place: 'Frankfurt / Zurich', title: 'Fly to India', text: 'Afternoon departure. Nonstop from Frankfurt (≈ 9 h) or one stop from Zurich. Set your watch to IST (+4 h 30 from CET) and sleep on the plane.', tags: ['✈️ Long-haul'] },
        { day: 2, place: 'Bengaluru', title: 'Land & unwind', text: 'Arrive around 01:00–02:00. Prepaid airport taxi or Uber to Indiranagar (45–75 min, ₹1,000–1,500). Sleep in, then a slow afternoon: Cubbon Park, Church Street coffee, sunset drinks at a rooftop.', tags: ['🛬 Arrival', '😴 Jet-lag day'] },
        { day: 3, place: 'Bengaluru', title: 'Gardens & palaces', text: 'Lalbagh Botanical Garden early, Bangalore Palace, lunch at MTR, Commercial Street shopping. Evening: VV Puram food street or craft beer at Toit.', tags: ['🌳 City day'] },
        { day: 4, place: 'Goa (North)', title: 'Fly to the coast', text: 'Morning flight BLR → GOX Mopa (1 h 10, €40–90). Taxi 45 min to Assagao / Vagator. Sunset at Chapora Fort, dinner at a beach shack.', tags: ['✈️ Domestic', '🌅 Sunset'] },
        { day: 5, place: 'Goa (North)', title: 'Beach day', text: 'Rent scooters (€6/day). Ashwem and Morjim beaches, lunch at a shack, siesta. Wednesday? Anjuna flea market. Saturday? Arpora night market.', tags: ['🏖️ Beach', '🛵 Scooter'] },
        { day: 6, place: 'Old Goa & Panaji', title: 'Heritage day', text: 'UNESCO churches at Old Goa (Bom Jesus, Sé Cathedral), then a walk through Fontainhas, Panaji\'s pastel Latin Quarter. Goan fish thali for lunch, Mandovi sunset cruise.', tags: ['⛪ UNESCO', '🍛 Food'] },
        { day: 7, place: 'Dudhsagar', title: 'Waterfall & spices', text: 'Day trip: jeep safari to Dudhsagar Falls (strong flow after the monsoon), lunch and tour at a spice plantation. Back by evening.', tags: ['🚙 Day trip', '💦 Waterfall'] },
        { day: 8, place: 'Goa (South)', title: 'Slow south', text: 'Move south: Palolem or Agonda. Kayaking, Cabo de Rama fort, quiet dinner on the sand. A night in the south balances the buzz of the north.', tags: ['🏖️ Beach', '🛶 Kayak'] },
        { day: 9, place: 'Bengaluru', title: 'Return & farewell', text: 'Fly GOI → BLR (1 h 10). Last-minute shopping at UB City or Commercial Street; farewell dinner of coastal food at Karavalli.', tags: ['✈️ Domestic', '🍽️ Farewell'] },
        { day: 10, place: 'Bengaluru → Europe', title: 'Fly home', text: 'Early morning departure (most Europe-bound flights leave BLR 02:00–05:00). Arrive Frankfurt / Zurich late morning the same day.', tags: ['✈️ Long-haul'] },
      ],
    },
    {
      id: 'kerala', gateway: 'BLR', months: [9, 10, 11, 12, 1, 2, 3], name: 'Tea Hills & Backwaters', subtitle: 'Bengaluru → Munnar → Alleppey → Kochi', days: 11,
      emoji: '🍃', accent: '#10b981',
      summary: 'The scenic itinerary: cool tea mountains in Munnar, a wildlife lake in Thekkady, a night on a houseboat and the old spice port of Fort Kochi.',
      stats: { flights: '2 domestic', pace: 'Moderate', cost: '€1,450 – 2,500 pp' },
      itinerary: [
        { day: 1, place: 'Frankfurt / Zurich', title: 'Fly to India', text: 'Afternoon departure, overnight flight to Bengaluru.', tags: ['✈️ Long-haul'] },
        { day: 2, place: 'Bengaluru', title: 'Land & unwind', text: 'Arrive early morning; sleep, then Cubbon Park and an easy evening in Indiranagar.', tags: ['🛬 Arrival'] },
        { day: 3, place: 'Bengaluru', title: 'City day', text: 'Lalbagh, Bangalore Palace, MTR lunch, sunset on a rooftop. Buy a local SIM if you didn\'t at the airport.', tags: ['🌳 City day'] },
        { day: 4, place: 'Kochi → Munnar', title: 'Into the hills', text: 'Flight BLR → COK (1 h 05). Pre-booked car with driver climbs 4 h through waterfalls and spice country to Munnar. Arrive for tea at 1,600 m.', tags: ['✈️ Domestic', '🚗 4 h drive'] },
        { day: 5, place: 'Munnar', title: 'Tea & tahr', text: 'Eravikulam National Park (Nilgiri tahr), KDHP Tea Museum, Mattupetty Dam and Top Station viewpoint. Evening estate walk.', tags: ['🍃 Tea', '🦌 Wildlife'] },
        { day: 6, place: 'Munnar', title: 'Sunrise above the clouds', text: '04:30 jeep to Kolukkumalai, the highest tea estate in the world, for sunrise over Tamil Nadu. Afternoon free: spa, Lockhart Gap, or simply the veranda.', tags: ['🌄 Sunrise', '🚙 Jeep'] },
        { day: 7, place: 'Thekkady', title: 'Periyar wildlife', text: 'Drive 3 h to Thekkady. Afternoon boat safari on Periyar Lake, spice-garden walk, Kalaripayattu martial-arts show.', tags: ['🐘 Wildlife', '🌶️ Spices'] },
        { day: 8, place: 'Alleppey', title: 'Houseboat night', text: 'Drive 4 h to Alleppey, board a private houseboat at noon. Lunch on deck, canals, sunset, dinner and a night moored on the lake.', tags: ['⛵ Houseboat', '🌅 Backwaters'] },
        { day: 9, place: 'Fort Kochi', title: 'Spice port', text: 'Disembark 09:00, drive 1.5 h to Fort Kochi. Chinese fishing nets, Mattancherry Palace, Jew Town antiques, Kathakali performance at 18:00.', tags: ['🏛️ Heritage', '🎭 Kathakali'] },
        { day: 10, place: 'Bengaluru', title: 'Return & farewell', text: 'Fly COK → BLR (1 h 05). Farewell dinner. Tip: Kochi also has direct Gulf connections to Europe if you prefer to skip Bengaluru.', tags: ['✈️ Domestic', '🍽️ Farewell'] },
        { day: 11, place: 'Bengaluru → Europe', title: 'Fly home', text: 'Early morning departure, home by midday.', tags: ['✈️ Long-haul'] },
      ],
    },
    {
      id: 'heritage', gateway: 'BLR', months: [10, 11, 12, 1, 2, 3], name: 'Heritage & Coffee', subtitle: 'Bengaluru → Mysuru → Coorg → Hampi', days: 12,
      emoji: '🏰', accent: '#f43f5e',
      summary: 'The Karnataka loop for culture lovers: royal Mysuru by fast train, coffee-estate living in Coorg and the surreal ruins of Hampi.',
      stats: { flights: '0–1 domestic', pace: 'Active', cost: '€1,300 – 2,200 pp' },
      itinerary: [
        { day: 1, place: 'Frankfurt / Zurich', title: 'Fly to India', text: 'Overnight flight to Bengaluru.', tags: ['✈️ Long-haul'] },
        { day: 2, place: 'Bengaluru', title: 'Land & unwind', text: 'Recover, Cubbon Park, easy dinner.', tags: ['🛬 Arrival'] },
        { day: 3, place: 'Bengaluru', title: 'City day', text: 'Lalbagh, Bangalore Palace, Commercial Street, brewery evening.', tags: ['🌳 City day'] },
        { day: 4, place: 'Mysuru', title: 'Royal city by train', text: 'Vande Bharat to Mysuru (2 h). Mysore Palace, Devaraja Market, Chamundi Hill at sunset. Sunday? Palace illumination at 19:00.', tags: ['🚆 Train', '🏰 Palace'] },
        { day: 5, place: 'Mysuru', title: 'Tipu & silk', text: 'Srirangapatna island fort and summer palace, silk weaving factory, Brindavan Gardens evening fountain.', tags: ['🏛️ History'] },
        { day: 6, place: 'Coorg', title: 'Coffee country', text: 'Car 3 h to a coffee estate near Madikeri. Estate walk, Raja\'s Seat sunset, Kodava dinner.', tags: ['🚗 3 h drive', '☕ Estate'] },
        { day: 7, place: 'Coorg', title: 'Elephants & monks', text: 'Dubare Elephant Camp early, Abbey Falls, Namdroling Golden Temple at Bylakuppe. Coffee tasting at the estate.', tags: ['🐘 Elephants', '🛕 Monastery'] },
        { day: 8, place: 'Bengaluru', title: 'Back to base', text: 'Drive 6 h back to Bengaluru (or 5 h to Mysuru + train). Evening: board the Hampi Express night train (2AC sleeper, ≈ €15).', tags: ['🚗 Drive', '🚆 Night train'] },
        { day: 9, place: 'Hampi', title: 'Boulders & temples', text: 'Arrive Hosapete 07:00, 30 min to Hampi. Virupaksha Temple, Hampi Bazaar, Hemakuta Hill sunset.', tags: ['🪨 UNESCO'] },
        { day: 10, place: 'Hampi', title: 'Stone chariot', text: 'Sunrise on Matanga Hill, Vittala Temple, Royal Enclosure by e-bike, coracle ride, afternoon at Sanapur lake.', tags: ['🌄 Sunrise', '🚲 Cycle'] },
        { day: 11, place: 'Bengaluru', title: 'Return & farewell', text: 'Morning flight VDY → BLR (1 h) or day train. Farewell dinner in Bengaluru.', tags: ['✈️ Domestic', '🍽️ Farewell'] },
        { day: 12, place: 'Bengaluru → Europe', title: 'Fly home', text: 'Early morning departure.', tags: ['✈️ Long-haul'] },
      ],
    },
    {
      id: 'golden', gateway: 'DEL', months: [10, 11, 12, 1, 2, 3], name: 'Golden Triangle & Ganges', subtitle: 'Delhi → Agra → Jaipur → Varanasi', days: 10,
      emoji: '🕌', accent: '#dc2626',
      summary: 'The classic north: Mughal Delhi, the Taj at dawn, Jaipur\'s forts, then a flight to Varanasi for the Ganges at sunrise. Private driver throughout, heritage hotels.',
      stats: { flights: '1 domestic', pace: 'Moderate', cost: '€1,900 – 3,200 pp' },
      itinerary: [
        { day: 1, place: 'Europe', title: 'Fly to Delhi', text: 'Nonstop from London, Paris, Frankfurt, Munich, Zurich, Vienna, Helsinki, Warsaw or Milan; overnight flight.', tags: ['✈️ Long-haul'] },
        { day: 2, place: 'Delhi', title: 'Land & settle', text: 'Airport meet-and-greet, hotel in Lutyens\' Delhi. Afternoon Humayun\'s Tomb and Lodhi Garden; dinner at Indian Accent.', tags: ['🛬 Arrival'] },
        { day: 3, place: 'Delhi', title: 'Old & New Delhi', text: 'Jama Masjid, spice market by rickshaw, Qutb Minar, India Gate at dusk.', tags: ['🕌 Heritage'] },
        { day: 4, place: 'Agra', title: 'Taj Mahal', text: 'Gatimaan Express to Agra (1 h 40). Agra Fort, then Taj Mahal at sunset from Mehtab Bagh.', tags: ['🚆 Train', '🏛️ UNESCO'] },
        { day: 5, place: 'Jaipur', title: 'Sunrise Taj, then Rajasthan', text: 'Taj at dawn, then drive to Jaipur via Fatehpur Sikri (5 h with driver).', tags: ['🌄 Sunrise', '🚗 Drive'] },
        { day: 6, place: 'Jaipur', title: 'Forts & bazaars', text: 'Amber Fort early, City Palace, Hawa Mahal, block-printing workshop, rooftop dinner.', tags: ['🏰 Forts'] },
        { day: 7, place: 'Varanasi', title: 'Fly to the Ganges', text: 'Flight JAI → VNS (1 h 20). Evening Ganga aarti from a boat.', tags: ['✈️ Domestic', '🪔 Aarti'] },
        { day: 8, place: 'Varanasi', title: 'Ghats & Sarnath', text: 'Sunrise boat, old-city walk, Sarnath, silk weavers.', tags: ['🌅 Sunrise'] },
        { day: 9, place: 'Delhi', title: 'Return', text: 'Flight VNS → DEL. Last shopping at Khan Market, farewell dinner.', tags: ['✈️ Domestic', '🍽️ Farewell'] },
        { day: 10, place: 'Delhi → Europe', title: 'Fly home', text: 'Morning departure.', tags: ['✈️ Long-haul'] },
      ],
    },
    {
      id: 'rajasthan', gateway: 'DEL', months: [10, 11, 12, 1, 2, 3], name: 'Palaces of Rajasthan', subtitle: 'Delhi → Jaipur → Jodhpur → Udaipur', days: 11,
      emoji: '🏯', accent: '#b45309',
      summary: 'Pink, blue and white cities with a private driver and palace hotels: Jaipur, Jodhpur, Ranakpur and Udaipur, flying home from Udaipur or via Mumbai.',
      stats: { flights: '1 domestic', pace: 'Relaxed', cost: '€2,200 – 4,000 pp' },
      itinerary: [
        { day: 1, place: 'Europe', title: 'Fly to Delhi', text: 'Overnight nonstop or one-stop flight.', tags: ['✈️ Long-haul'] },
        { day: 2, place: 'Delhi', title: 'Land & rest', text: 'Meet-and-greet, calm hotel, Humayun\'s Tomb at golden hour.', tags: ['🛬 Arrival'] },
        { day: 3, place: 'Jaipur', title: 'To the pink city', text: 'Drive 5 h with driver (or Vande Bharat). Evening at a rooftop over the old city.', tags: ['🚗 Drive'] },
        { day: 4, place: 'Jaipur', title: 'Amber & the bazaars', text: 'Amber Fort, City Palace, Jantar Mantar, block printing.', tags: ['🏰 Forts'] },
        { day: 5, place: 'Jodhpur', title: 'The blue city', text: 'Flight or 6 h drive. Mehrangarh Fort at sunset, dinner under the fort.', tags: ['✈️ Domestic', '🌇 Sunset'] },
        { day: 6, place: 'Jodhpur', title: 'Fort & old town', text: 'Fort museum, zip line, clock-tower market, Umaid Bhawan.', tags: ['🏯 Palace'] },
        { day: 7, place: 'Udaipur', title: 'Via Ranakpur', text: 'Drive 5 h with a stop at Ranakpur Jain temple and Kumbhalgarh.', tags: ['🚗 Drive', '🛕 Temple'] },
        { day: 8, place: 'Udaipur', title: 'Lakes & palaces', text: 'City Palace, boat on Lake Pichola, Bagore ki Haveli dance show.', tags: ['⛵ Lake'] },
        { day: 9, place: 'Udaipur', title: 'Slow day', text: 'Spa, Monsoon Palace sunset, rooftop dinner.', tags: ['🧘 Rest'] },
        { day: 10, place: 'Udaipur / Delhi', title: 'Return', text: 'Fly UDR → DEL (or Mumbai). Farewell dinner.', tags: ['✈️ Domestic'] },
        { day: 11, place: 'Delhi → Europe', title: 'Fly home', text: 'Morning departure.', tags: ['✈️ Long-haul'] },
      ],
    },
  ],

  /* Cost model — per person, EUR, by travel style. No budget tier: comfort is the floor. */
  costModel: {
    styles: {
      comfort: { label: 'Comfort',  stars: '4★', intl: 900,  hotel: 65,  food: 30, local: 22, actFactor: 1.0, desc: 'Good 4-star hotels and boutique stays, economy flights with reputable airlines, private car with driver in the hills, well-reviewed restaurants.' },
      premium: { label: 'Premium',  stars: '5★', intl: 1500, hotel: 140, food: 55, local: 35, actFactor: 1.3, desc: 'Five-star hotels (Taj, ITC, Marriott, Hyatt), premium-economy long-haul, private driver throughout, guided visits, airport meet-and-greet.' },
      luxury:  { label: 'Luxury',   stars: '5★+', intl: 3300, hotel: 300, food: 90, local: 60, actFactor: 1.8, desc: 'Business class, palace hotels and Oberoi / Taj / Aman-level resorts, domestic business class, chauffeur and private guides everywhere.' },
    },
    routes: {
      goa:      { transport: 150, activities: 110 },
      kerala:   { transport: 270, activities: 190 },
      heritage: { transport: 190, activities: 90 },
      golden:   { transport: 260, activities: 160 },
      rajasthan:{ transport: 300, activities: 170 },
    },
    fixed: { visa: 40, insurance: 60, sim: 8 },
    bufferPct: 0.10,
  },

  safety: [
    { icon: '🛂', title: 'e-Visa before you fly', text: 'All EU, UK and Swiss citizens are eligible for the Indian e-Tourist Visa (30 days, 1 year or 5 years). Apply only on the official site, at least 7 days before departure. Print the approval.', link: { label: 'indianvisaonline.gov.in/evisa', url: 'https://indianvisaonline.gov.in/evisa/' } },
    { icon: '🩺', title: 'Health & vaccinations', text: 'Routine vaccines plus Hepatitis A and Typhoid are usually recommended; talk to a travel clinic 6 weeks out. Drink only sealed bottled or filtered water, and carry oral rehydration salts and a basic kit.', link: { label: 'CRM / Tropeninstitut travel advice', url: 'https://www.crm.de/' } },
    { icon: '🛡️', title: 'Travel insurance', text: 'Take a policy that covers medical evacuation and adventure activities. Private hospitals in the big cities (Apollo, Manipal, Max, Medanta, Aster) are excellent — insurance makes them stress-free. Every destination guide names the nearest good hospital.', link: { label: 'Compare on Check24', url: 'https://www.check24.de/reiseversicherung/' } },
    { icon: '🚨', title: 'Emergency numbers', text: '112 — all emergencies (police, fire, ambulance). 1363 — 24 h multilingual tourist helpline (German, French, Spanish, Italian and more). Save your embassy and nearest consulate from the card above.', link: { label: 'Incredible India helpline 1363', url: 'https://www.incredibleindia.gov.in/' } },
    { icon: '🚕', title: 'Getting around safely', text: 'Use Uber, Ola or the airport\'s prepaid taxi counter instead of street hawkers. Trains: book 2AC/3AC or Vande Bharat. For hill roads hire a car with driver — don\'t self-drive.', link: { label: 'Uber India', url: 'https://www.uber.com/in/en/' } },
    { icon: '💳', title: 'Money', text: 'ATMs are everywhere (SBI, HDFC, ICICI). Wise or Revolut cards give the best rates. Foreign tourists can activate UPI (QR payments) via "UPI One World" at BLR airport — very handy for cafés and autos.', link: { label: 'Wise', url: 'https://wise.com/' } },
    { icon: '📱', title: 'SIM & connectivity', text: 'Buy an Airtel or Jio tourist SIM at BLR arrivals (passport + visa needed, ~€8 for 28 days), or install an eSIM (Airalo, Holafly) before you fly. WhatsApp is how everyone communicates.', link: { label: 'Airalo India eSIM', url: 'https://www.airalo.com/india-esim' } },
    { icon: '👗', title: 'Culture & dress', text: 'Cover shoulders and knees at temples and remove shoes. Bargain politely at markets, tip 5–10 % in restaurants. Public affection is frowned upon; alcohol is fine in Goa and Bengaluru bars.', link: null },
    { icon: '🕵️', title: 'Common scams to skip', text: '"Your hotel is closed" taxi stories, gem/carpet "export" deals, unofficial guides at monuments, and card skimmers at isolated ATMs. Politely say no and keep walking.', link: null },
    { icon: '🔌', title: 'Plugs, time & tips', text: 'Type C/D/M sockets, 230 V — a universal adapter works. IST is UTC+5:30 (CET +4:30 in November). Diwali 2026 falls on 8 November: fireworks, sweets and some closures — plan around it.', link: null },
  ],

  links: [
    { group: 'Flights', items: [
      { label: 'Google Flights', url: 'https://www.google.com/travel/flights', note: 'Best price calendar for FRA/ZRH → BLR' },
      { label: 'Skyscanner', url: 'https://www.skyscanner.net/', note: 'Compare Gulf-carrier connections' },
      { label: 'Lufthansa', url: 'https://www.lufthansa.com/', note: 'Nonstop Frankfurt → Bengaluru' },
      { label: 'IndiGo', url: 'https://www.goindigo.in/', note: 'Domestic: Goa, Kochi, Hyderabad' },
      { label: 'Air India', url: 'https://www.airindia.com/', note: 'Domestic & international' },
      { label: 'Akasa Air', url: 'https://www.akasaair.com/', note: 'Low-cost domestic' },
    ]},
    { group: 'Trains & buses', items: [
      { label: 'IRCTC', url: 'https://www.irctc.co.in/', note: 'Official rail booking (foreign cards accepted)' },
      { label: '12Go Asia', url: 'https://12go.asia/en/travel/india', note: 'Easiest for foreigners — trains, buses, ferries' },
      { label: 'ConfirmTkt', url: 'https://www.confirmtkt.com/', note: 'Seat availability predictions' },
      { label: 'redBus', url: 'https://www.redbus.in/', note: 'Intercity buses' },
      { label: 'KSRTC Karnataka', url: 'https://ksrtc.in/', note: 'State buses incl. airport Vayu Vajra' },
    ]},
    { group: 'Stays', items: [
      { label: 'Booking.com', url: 'https://www.booking.com/', note: 'Widest hotel & homestay choice' },
      { label: 'Airbnb', url: 'https://www.airbnb.com/', note: 'Villas in Goa, estates in Coorg' },
      { label: 'MakeMyTrip', url: 'https://www.makemytrip.com/', note: 'Indian rates, often cheaper' },
      { label: 'CGH Earth', url: 'https://www.cghearth.com/', note: 'Sustainable heritage hotels in Kerala' },
      { label: 'Hostelworld', url: 'https://www.hostelworld.com/', note: 'Zostel & hostel network' },
    ]},
    { group: 'On the ground', items: [
      { label: 'Uber', url: 'https://www.uber.com/in/en/', note: 'Cabs & autos in all cities' },
      { label: 'Ola', url: 'https://www.olacabs.com/', note: 'Local alternative' },
      { label: 'Zomato', url: 'https://www.zomato.com/', note: 'Restaurant ratings & delivery' },
      { label: 'Google Maps', url: 'https://maps.google.com/', note: 'Download offline maps' },
      { label: 'UPI One World', url: 'https://www.npci.org.in/what-we-do/upi/upi-one-world', note: 'QR payments for tourists' },
    ]},
    { group: 'Official & safety', items: [
      { label: 'Indian e-Visa', url: 'https://indianvisaonline.gov.in/evisa/', note: 'Only official site' },
      { label: 'Auswärtiges Amt — Indien', url: 'https://www.auswaertiges-amt.de/de/service/laender/indien-node', note: 'German travel advice' },
      { label: 'EDA — Indien', url: 'https://www.eda.admin.ch/eda/de/home/vertretungen-und-reisehinweise/indien.html', note: 'Swiss travel advice' },
      { label: 'Incredible India', url: 'https://www.incredibleindia.gov.in/', note: 'Official tourism board' },
      { label: 'India Meteorological Dept', url: 'https://mausam.imd.gov.in/', note: 'Forecasts & monsoon updates' },
      { label: 'Kerala Tourism', url: 'https://www.keralatourism.org/', note: 'Houseboats, festivals, events' },
      { label: 'Goa Tourism', url: 'https://goa-tourism.com/', note: 'Official Goa information' },
    ]},
  ],
};
