/* ------------------------------------------------------------------
   Destinations across India beyond the original southern set.
   Merged into TRIP.destinations and GUIDE at load (see bottom).
   Schema matches data.js. Comfort floor: 4★ — no hostels here.
   ------------------------------------------------------------------ */
(function () {
  const D = [
    /* ---------------- North: Golden Triangle & Rajasthan ---------------- */
    { id: 'agra', region: 'north', airport: 'AGR', via: null, priceIndex: 1.2, months: [2,3,3,1,0,0,1,1,2,3,3,2], comfort: { score: 3, hospital: 'SN Medical College · Pushpanjali Hospital (basic); Delhi 3 h for serious care', notes: ['Touts are relentless at the Taj gates: buy tickets online, hire an ASI-licensed guide through your hotel.', 'One or two nights is right; the city beyond the monuments is rough.', 'Sunrise entry is calm and cool; avoid Friday (closed) and Indian holidays.'] }, lat: 27.18, lng: 78.01, hours: 2.5, transfer: 60, type: 'culture', from: 'Delhi 2 h by train', nights: '1–2 nights', name: 'Agra', tag: 'The Taj Mahal at dawn', emoji: '🕌', hue: 'linear-gradient(135deg,#f5f5f4,#a16207)', weather: '12–28 °C in Nov · clear mornings', intro: 'The Taj Mahal is everything they say, especially at sunrise before the crowds. Add Agra Fort, the ghost city of Fatehpur Sikri and the Mehtab Bagh riverside view at sunset — then move on.', todo: ['Taj Mahal at sunrise (book a timed slot online)', 'Agra Fort and its Taj views', 'Mehtab Bagh across the river at sunset', 'Itimad-ud-Daulah, the "Baby Taj"', 'Fatehpur Sikri on the road to Jaipur', 'Petha sweets and a marble-inlay workshop'], food: ['Peshawri at ITC Mughal for dal bukhara', 'Pinch of Spice for North-Indian classics', 'Joney\'s Place chai stop near the Taj (institution, humble)'], stay: { budget: '—', mid: 'Trident Agra, ITC Mughal · €110–200', lux: 'The Oberoi Amarvilas (Taj view from every room) · €500–900' }, area: 'Gatimaan Express from Delhi (1 h 40) or car with driver. Stay in the Tajganj / Fatehabad Road hotel belt.', perDay: '€60 – 350' },
    { id: 'jaipur', region: 'north', airport: 'JAI', via: null, priceIndex: 1.3, months: [3,3,2,1,0,0,1,1,2,3,3,3], comfort: { score: 4, hospital: 'Fortis Escorts · Eternal Hospital · Apollo', notes: ['Well-organised tourist city with excellent hotels and drivers.', 'Bargain firmly in Johari Bazaar; ignore "government emporium" claims from drivers.', 'Elephant rides at Amber Fort raise welfare concerns — take the jeep.'] }, lat: 26.91, lng: 75.79, hours: 2.5, transfer: 120, type: 'culture', from: '2 h 30 flight · 5 h from Delhi', nights: '2–3 nights', name: 'Jaipur', tag: 'The pink city: forts, palaces, bazaars', emoji: '🏰', hue: 'linear-gradient(135deg,#f472b6,#9f1239)', weather: '11–28 °C in Nov · dry, perfect', intro: 'Amber Fort on its hill, the honeycomb Hawa Mahal, a living royal palace and bazaars of block prints and gems. The most polished stop in Rajasthan, with hotels that were once palaces.', todo: ['Amber Fort early, then Jaigarh above it', 'City Palace & the Jantar Mantar observatory', 'Hawa Mahal from the café opposite', 'Block-printing workshop in Sanganer or Bagru', 'Nahargarh Fort at sunset over the city', 'Johari Bazaar and Bapu Bazaar shopping'], food: ['Laxmi Misthan Bhandar (LMB) thali and sweets', 'Lassiwala on MI Road', 'Suvarna Mahal at Rambagh Palace for a royal dinner', '1135 AD inside Amber Fort'], stay: { budget: '—', mid: 'Samode Haveli, Trident Jaipur, Alsisar Haveli · €100–200', lux: 'Rambagh Palace, Oberoi Rajvilas, Raffles Jaipur, Taj Jai Mahal · €300–900' }, area: 'Nonstop flights from most gateways; Vande Bharat from Delhi. Stay in the C-Scheme / Civil Lines area or a heritage haveli in the old city.', perDay: '€60 – 400' },
    { id: 'jodhpur', region: 'north', airport: 'JDH', via: null, priceIndex: 1.3, months: [3,3,2,1,0,0,0,1,2,3,3,3], comfort: { score: 4, hospital: 'AIIMS Jodhpur · Medipulse', notes: ['Old-city lanes are steep and narrow — cars stop at the edge, walk or take a tuk-tuk.', 'Very hot Apr–Jun; November mornings are ideal.', 'Safe, friendly; the market around the clock tower is busy but calm.'] }, lat: 26.30, lng: 73.02, hours: 3, transfer: 130, type: 'culture', from: '1 h 20 flight from Delhi', nights: '2 nights', name: 'Jodhpur', tag: 'The blue city beneath Mehrangarh', emoji: '🏯', hue: 'linear-gradient(135deg,#60a5fa,#1e3a8a)', weather: '13–30 °C in Nov · dry, sunny', intro: 'A vast fort on a cliff, a sea of indigo houses below it, and one of India\'s great palace hotels. Compact enough for two full days, with Ranakpur and Osian within reach.', todo: ['Mehrangarh Fort and its museum (allow 3 h)', 'Flying Fox zip line over the fort lakes', 'Blue lanes of Navchokiya on foot', 'Clock-tower market: spices, makhaniya lassi', 'Umaid Bhawan Palace museum', 'Jaswant Thada marble cenotaph at sunset'], food: ['Indique rooftop at Pal Haveli', 'Shri Mishrilal for lassi', 'Gypsy for unlimited Rajasthani thali', 'Umaid Bhawan\'s Risala for a splurge'], stay: { budget: '—', mid: 'RAAS Jodhpur, Pal Haveli, Ranbanka Palace · €120–250', lux: 'Umaid Bhawan Palace (Taj) · €600–1,500' }, area: 'Flights from Delhi, Mumbai and Jaipur. Udaipur is 5 h by car via Ranakpur.', perDay: '€60 – 450' },
    { id: 'udaipur', region: 'north', airport: 'UDR', via: null, priceIndex: 1.5, months: [3,3,2,1,0,0,1,1,2,3,3,3], comfort: { score: 5, hospital: 'GBH American Hospital · Paras JK', notes: ['The gentlest city in Rajasthan: walkable, calm, superb hotels.', 'Lake levels vary; after a weak monsoon Pichola can be low — check recent photos.', 'Evening boat trips sell out; book through the hotel.'] }, lat: 24.58, lng: 73.71, hours: 2.5, transfer: 130, type: 'culture', from: '1 h 30 flight from Delhi', nights: '2–3 nights', name: 'Udaipur', tag: 'Lake palaces & golden light', emoji: '🛶', hue: 'linear-gradient(135deg,#fbbf24,#7c2d12)', weather: '12–30 °C in Nov · dry, ideal', intro: 'White palaces reflected in Lake Pichola, rooftop dinners, boat rides at sunset and the finest hotels in India. The place to end a Rajasthan loop slowly.', todo: ['City Palace museum in the morning', 'Sunset boat on Lake Pichola to Jag Mandir', 'Bagore ki Haveli folk-dance show at 19:00', 'Sajjangarh (Monsoon Palace) for the view', 'Ranakpur Jain temple day trip (2 h)', 'Miniature-painting studio in the old city'], food: ['Ambrai at Amet Haveli, lakeside', 'Upre by 1559 AD rooftop', 'Jagat Niwas rooftop', 'Jheel\'s Ginger Coffee Bar for breakfast'], stay: { budget: '—', mid: 'Jagat Niwas Palace, Trident Udaipur, Amet Haveli · €90–220', lux: 'Taj Lake Palace, The Oberoi Udaivilas, Leela Palace, Raffles Udaipur · €400–1,500' }, area: 'Nonstop from Delhi, Mumbai and Bengaluru. Everything worth seeing is around the lake; walk or take short autos.', perDay: '€70 – 500' },
    { id: 'jaisalmer', region: 'north', airport: 'JSA', via: null, priceIndex: 1.3, months: [3,3,2,0,0,0,0,0,1,3,3,3], comfort: { score: 3, hospital: 'Jawahir Hospital (basic); Jodhpur 5 h for serious care', notes: ['Remote desert town: carry medicines, expect basic facilities outside your hotel.', 'Camel safaris: use your hotel\'s operator, one night max, and check the camels are well kept.', 'Blistering Apr–Sep; Nov–Feb is the season.'] }, lat: 26.92, lng: 70.92, hours: 5, transfer: 140, type: 'culture', from: '1 h 30 flight from Delhi (seasonal) · 5 h from Jodhpur', nights: '2 nights', name: 'Jaisalmer', tag: 'Golden fort & Thar desert', emoji: '🐪', hue: 'linear-gradient(135deg,#fcd34d,#b45309)', weather: '10–29 °C in Nov · dry desert air', intro: 'A sandstone fort that glows at sunset, still lived in, with carved havelis below and dunes an hour away. Luxury desert camps make the Thar surprisingly comfortable.', todo: ['Jaisalmer Fort at first light, before the shops open', 'Patwon ki Haveli carved mansions', 'Gadisar Lake at sunset', 'Sam or Khuri dunes: camel ride and a night in a luxury camp', 'Kuldhara abandoned village', 'Longewala war memorial (2 h) for history buffs'], food: ['Ker sangri and dal baati at a haveli restaurant', 'Saffron kulfi in the fort', 'Camp dinners under the stars with folk music'], stay: { budget: '—', mid: 'Suryagarh (edge of desert), Fort Rajwada · €120–250', lux: 'Suryagarh suites, The Serai desert camp · €350–900' }, area: 'Winter flights from Delhi; otherwise a 5 h desert drive from Jodhpur. Stay outside the fort — inside, water use damages the walls.', perDay: '€60 – 400' },
    { id: 'pushkar', region: 'north', airport: null, via: 'JAI', priceIndex: 1.1, months: [3,3,2,1,0,0,1,1,2,3,3,3], comfort: { score: 3, hospital: 'Ajmer hospitals (30 min); Jaipur 2.5 h', notes: ['Holy town: no alcohol or meat in the centre; hotels outside serve both.', 'Priests at the ghats push "pujas" for money — a polite no works.', 'Camel-fair week (Nov) triples prices; book months ahead.'] }, lat: 26.49, lng: 74.55, hours: 3, transfer: 60, type: 'culture', from: '2.5 h from Jaipur by car', nights: '1–2 nights', name: 'Pushkar', tag: 'Sacred lake & the camel fair', emoji: '🐫', hue: 'linear-gradient(135deg,#fde68a,#c2410c)', weather: '12–29 °C in Nov · dry', intro: 'A tiny temple town around a sacred lake, ringed by ghats and hills. In November the world\'s biggest camel fair fills the dunes with traders, folk musicians and hot-air balloons.', todo: ['Sunrise at Savitri Temple by ropeway', 'Evening aarti on the ghats', 'Pushkar Camel Fair (Nov, around Kartik Purnima)', 'Hot-air balloon flight over the fair', 'Brahma Temple, one of very few in the world', 'Ajmer\'s Dargah Sharif, 30 min away'], food: ['Rooftop cafés with lake views (vegetarian)', 'Malpua sweets from the market', 'Falafel and Israeli food — a Pushkar oddity'], stay: { budget: '—', mid: 'Pushkar Palace, Dera Masuda · €80–150', lux: 'The Westin Pushkar Resort, Ananta Spa · €150–300' }, area: 'Car from Jaipur (2.5 h) or Ajmer station (Vande Bharat from Delhi, then 30 min).', perDay: '€50 – 250' },
    { id: 'ranthambore', region: 'north', airport: null, via: 'JAI', priceIndex: 1.6, months: [2,3,3,3,3,2,0,0,0,2,3,3], comfort: { score: 4, hospital: 'Sawai Madhopur district hospital (basic); Jaipur 3 h', notes: ['Safaris are allocated by lottery-style booking — reserve the moment your dates are fixed, ideally through the lodge.', 'Park closed Jul–Sep; tiger sightings best Mar–May (hot) and decent Nov–Feb.', 'Lodges are excellent and secure; follow guide instructions in the park.'] }, lat: 26.02, lng: 76.50, hours: 4, transfer: 90, type: 'wildlife', from: '3 h from Jaipur · train from Delhi', nights: '2–3 nights', name: 'Ranthambore', tag: 'Tigers among ruined forts', emoji: '🐯', hue: 'linear-gradient(135deg,#f59e0b,#78350f)', weather: '11–30 °C in Nov · dry', intro: 'India\'s most photogenic tiger reserve: dry forest, lakes, a 10th-century fort inside the park and tigers used to jeeps. The best odds of a sighting on a first trip.', todo: ['Morning and afternoon jeep or canter safaris (zones 1–5 best)', 'Ranthambore Fort and the Ganesh temple', 'Padam Talao lake at dawn', 'Dastkar craft centre for village textiles', 'Birdwatching around Surwal Lake'], food: ['Lodge dining is the standard here; full board', 'Rajasthani thali at the lodges'], stay: { budget: '—', mid: 'Ranthambhore Regency, Tiger Den · €120–220 with safaris', lux: 'Oberoi Vanyavilas, Aman-i-Khás, Sher Bagh (Sujan) · €500–1,500' }, area: 'Train from Delhi to Sawai Madhopur (4 h) or car from Jaipur (3 h). Book safaris and lodge together.', perDay: '€90 – 600' },
    { id: 'amritsar', region: 'north', airport: 'ATQ', via: null, priceIndex: 1.0, months: [2,3,3,2,0,0,1,1,2,3,3,2], comfort: { score: 4, hospital: 'Fortis Escorts Amritsar · Amandeep', notes: ['One of the friendliest cities; the Golden Temple is open to all, cover your head, no shoes, no smoking anywhere near.', 'Wagah border ceremony: seats are free but arrive by 15:30; foreigners have a separate enclosure.', 'Fog can delay flights Dec–Jan.'] }, lat: 31.63, lng: 74.87, hours: 4, transfer: 110, type: 'culture', from: '1 h 10 flight from Delhi · Vande Bharat 5 h', nights: '1–2 nights', name: 'Amritsar', tag: 'The Golden Temple & Punjabi food', emoji: '🛕', hue: 'linear-gradient(135deg,#fbbf24,#b45309)', weather: '10–26 °C in Nov · clear', intro: 'The Golden Temple floating on its pool is one of the most moving sights in India, and its kitchen feeds 100,000 people a day for free. Add the Wagah border ceremony and the best food in the north.', todo: ['Golden Temple at dawn and again lit at night', 'Langar: eat with everyone in the community kitchen', 'Jallianwala Bagh memorial', 'Wagah–Attari border retreat ceremony', 'Partition Museum', 'Heritage walk through the old city'], food: ['Kesar da Dhaba for dal and paratha', 'Kulcha at Kulcha Land', 'Beera Chicken House', 'Lassi at Gian di Lassi'], stay: { budget: '—', mid: 'Taj Swarna, Hyatt Regency Amritsar · €90–160', lux: 'Taj Swarna suites, Ramada Amritsar (heritage wing) · €150–250' }, area: 'Fly from Delhi or take the Vande Bharat. Stay near the temple for the night visit.', perDay: '€45 – 200' },

    /* ---------------- Himalaya ---------------- */
    { id: 'shimla', region: 'north', airport: null, via: 'DEL', priceIndex: 1.2, months: [2,2,3,3,3,2,0,0,2,3,3,2], comfort: { score: 4, hospital: 'IGMC Shimla · Indus Hospital', notes: ['Mountain roads: hire an experienced hill driver, travel by day, carry motion-sickness tablets.', 'Cold Nov–Feb (0–15 °C), snow possible Dec–Feb.', 'Very safe, walkable Mall Road; monkeys steal food and glasses.'] }, lat: 31.10, lng: 77.17, hours: 8, transfer: 120, type: 'hills', from: '8 h from Delhi · toy train from Kalka', nights: '2–3 nights', name: 'Shimla', tag: 'The colonial hill capital', emoji: '🏔️', hue: 'linear-gradient(135deg,#86efac,#14532d)', weather: '5–18 °C in Nov · crisp, clear', intro: 'The Raj\'s summer capital: a ridge of Tudor buildings and pines with the Himalaya on the horizon, reached by a UNESCO narrow-gauge railway. Best paired with the quieter estates of Mashobra and Naldehra.', todo: ['Kalka–Shimla toy train (UNESCO, 5 h of tunnels and bridges)', 'The Ridge and Mall Road at dusk', 'Viceregal Lodge and its gardens', 'Jakhu Temple hill walk', 'Naldehra golf course and cedar walks', 'Kufri snow point in winter'], food: ['Himachali dham thali', 'Wake & Bake café on Mall Road', 'Cecil (Oberoi) for old-world dinner', 'Sidhu dhaba momos'], stay: { budget: '—', mid: 'Clarkes Shimla, Radisson Jass · €90–160', lux: 'The Oberoi Cecil, Wildflower Hall (Mashobra), Chalets Naldehra · €250–600' }, area: 'Car with driver from Delhi (8 h) or fly to Chandigarh (1 h) then 3 h. Toy train from Kalka is the romantic option.', perDay: '€50 – 350' },
    { id: 'manali', region: 'north', airport: null, via: 'DEL', priceIndex: 1.2, months: [1,1,2,3,3,3,0,0,2,3,3,1], comfort: { score: 3, hospital: 'Lady Willingdon Hospital (basic); Chandigarh 8 h for serious care', notes: ['Long mountain drive; the Atal Tunnel now opens Lahaul year-round but passes close in snow.', 'Altitude: Rohtang and Lahaul are above 3,000 m — take it slow.', 'Old Manali and Naggar are calmer and safer than the main bazaar in high season.'] }, lat: 32.24, lng: 77.19, hours: 12, transfer: 150, type: 'hills', from: '12 h from Delhi · overnight Volvo bus · Kullu flight (unreliable)', nights: '3 nights', name: 'Manali', tag: 'Kullu valley & the Atal Tunnel', emoji: '🌲', hue: 'linear-gradient(135deg,#a7f3d0,#065f46)', weather: '2–15 °C in Nov · cold, clear', intro: 'Apple orchards, deodar forests and snow peaks. Through the Atal Tunnel lies Lahaul\'s high desert. Choose an estate in Naggar or Old Manali for comfort; this is trekking and rafting country.', todo: ['Atal Tunnel to Sissu and Lahaul valley', 'Solang Valley paragliding and zip lines', 'Hadimba Temple in the cedar forest', 'Naggar Castle and the Roerich gallery', 'Old Manali cafés and the river walk', 'Jogini Falls hike from Vashisht'], food: ['Siddu (steamed bread) and trout', 'Johnson\'s Café for trout and apple crumble', 'Café 1947 by the river'], stay: { budget: '—', mid: 'Span Resort & Spa, The Himalayan (castle) · €100–200', lux: 'Lodge at Wah (Naggar), The Himalayan suites, Manuallaya · €200–400' }, area: 'Fly to Chandigarh (or Delhi) and take a car with driver; 8–12 h. Overnight luxury buses exist but are not comfortable.', perDay: '€50 – 300' },
    { id: 'dharamshala', region: 'north', airport: 'DHM', via: null, priceIndex: 1.1, months: [2,2,3,3,3,2,0,0,2,3,3,2], comfort: { score: 4, hospital: 'Fortis Kangra (30 min) · Delek Hospital McLeod Ganj', notes: ['Peaceful, English-speaking, safe; steep lanes need good shoes.', 'Gaggal airport flights cancel in bad weather — keep a buffer day.', 'The Dalai Lama\'s public teachings need advance registration.'] }, lat: 32.22, lng: 76.32, hours: 9, transfer: 140, type: 'hills', from: '1 h 20 flight from Delhi to Gaggal', nights: '2–3 nights', name: 'Dharamshala & McLeod Ganj', tag: 'Tibet in exile, under the Dhauladhar', emoji: '🙏', hue: 'linear-gradient(135deg,#fca5a5,#7f1d1d)', weather: '8–20 °C in Nov · clear peaks', intro: 'Home of the Dalai Lama: monasteries, momos, Tibetan cafés and the snow wall of the Dhauladhar range above. Gentle walks, meditation courses and a cricket ground with a view.', todo: ['Tsuglagkhang complex and the Dalai Lama temple', 'Norbulingka Institute for Tibetan arts', 'Triund day hike (or overnight)', 'Bhagsu waterfall and Dharamkot cafés', 'HPCA cricket stadium view', 'Kangra Fort and Masroor rock temples (1 h)'], food: ['Tibet Kitchen for momos and thukpa', 'Lung Ta Japanese vegetarian', 'Illiterati café for coffee with a view', 'Trout at Dharamkot'], stay: { budget: '—', mid: 'Hyatt Regency Dharamshala, Chonor House · €90–170', lux: 'Hyatt Regency suites, Norwood Green, Rakkh Resort · €150–300' }, area: 'Fly Delhi → Gaggal (DHM), 30 min to town. Or Vande Bharat to Amritsar (Amritsar → Dharamshala 4 h).', perDay: '€45 – 250' },
    { id: 'leh', region: 'north', airport: 'IXL', via: null, priceIndex: 1.4, months: [1,1,1,2,3,3,3,3,3,2,1,1], comfort: { score: 3, hospital: 'SNM Hospital Leh (altitude experience); evacuation to Delhi for serious cases', notes: ['3,500 m altitude: rest for 24–48 h on arrival, hydrate, no alcohol day one. Not for people with heart or lung conditions without advice.', 'Season is May–Oct; passes and most hotels close in winter.', 'Inner Line Permits needed for Nubra, Pangong (arranged by your hotel).'] }, lat: 34.16, lng: 77.58, hours: 4, transfer: 200, type: 'hills', from: '1 h 30 flight from Delhi', nights: '5–6 nights', name: 'Leh & Ladakh', tag: 'High desert, monasteries, Pangong', emoji: '🏔️', hue: 'linear-gradient(135deg,#bfdbfe,#1e3a8a)', weather: 'May–Sep season · Nov −5 to 8 °C', intro: 'Trans-Himalayan moonscape: gompas on cliffs, turquoise Pangong lake, the Nubra dunes and some of the highest roads on earth. Summer only — and worth building a trip around.', todo: ['Thiksey and Hemis monasteries', 'Pangong Tso lake (overnight in a luxury camp)', 'Nubra Valley via Khardung La', 'Shanti Stupa at sunset', 'Rafting on the Zanskar (Jul–Sep)', 'Leh Palace and old-town walk'], food: ['Thukpa, momos, butter tea', 'Bon Appetit for dinner with a view', 'Lamayuru Restaurant', 'Apricot everything in season'], stay: { budget: '—', mid: 'The Grand Dragon, Ladakh Sarai · €120–220', lux: 'Chamba Camp Thiksey (TUTC), Stone Hedge, Pangong luxury camps · €300–1,200' }, area: 'Fly Delhi → Leh (nonstop, 1 h 30). Hire a car with a local driver for the whole stay; distances are long and roads high.', perDay: '€80 – 500' },
    { id: 'corbett', region: 'north', airport: null, via: 'DEL', priceIndex: 1.5, months: [2,3,3,3,3,1,0,0,0,1,3,3], comfort: { score: 4, hospital: 'Ramnagar hospital (basic); Delhi 6 h', notes: ['Book Dhikala or Bijrani safaris weeks ahead; permits are limited.', 'Core zones close Jul–mid Nov (Dhikala) — check dates.', 'Riverside resorts are excellent; avoid the party resorts near the town.'] }, lat: 29.53, lng: 78.77, hours: 6, transfer: 110, type: 'wildlife', from: '6 h from Delhi by car · train to Ramnagar', nights: '2–3 nights', name: 'Jim Corbett', tag: 'India\'s oldest tiger reserve', emoji: '🐅', hue: 'linear-gradient(135deg,#bef264,#365314)', weather: '10–27 °C in Nov · clear', intro: 'Sal forest, grassland and the Ramganga river at the foot of the Himalaya — tigers, elephants and 600 bird species. Dhikala\'s forest rest house is the classic stay; the Kosi riverside lodges the comfortable one.', todo: ['Jeep safaris in Bijrani, Jhirna and Dhela zones', 'Dhikala grassland (overnight permit needed)', 'Elephant herds at Dhikala chaur', 'Birding along the Kosi river', 'Garjiya Devi temple on a rock in the river', 'Corbett Museum at Kaladhungi'], food: ['Lodge dining, Kumaoni thalis', 'Bhatt ki churkani and aloo ke gutke (Kumaon specialities)'], stay: { budget: '—', mid: 'Taj Corbett Resort, Riverview Retreat · €120–220', lux: 'Aahana, Jim\'s Jungle Retreat, Taj Corbett suites · €250–500' }, area: 'Car from Delhi (6 h) or Ranikhet Express night train to Ramnagar. Combine with Nainital (2 h).', perDay: '€80 – 400' },

    /* ---------------- Central & West ---------------- */
    { id: 'khajuraho', region: 'central', airport: 'HJR', via: null, priceIndex: 1.1, months: [3,3,2,1,0,0,1,1,2,3,3,3], comfort: { score: 3, hospital: 'Khajuraho hospital (basic); Jhansi 4 h', notes: ['Tiny town built around the temples; hire the ASI guide at the gate, not touts.', 'Flights are few — fix them first, then build around.', 'Very hot Apr–Jun.'] }, lat: 24.85, lng: 79.92, hours: 3, transfer: 140, type: 'culture', from: '1 h 30 flight from Delhi (limited days)', nights: '1–2 nights', name: 'Khajuraho', tag: 'UNESCO temples of the Chandelas', emoji: '🛕', hue: 'linear-gradient(135deg,#fdba74,#9a3412)', weather: '10–28 °C in Nov · dry', intro: 'Thirty temples covered in some of the finest sculpture in India, famous for the erotic panels but astonishing throughout. A night here, then on to the tiger reserves or Varanasi.', todo: ['Western group at sunrise (Kandariya Mahadeva, Lakshmana)', 'Eastern group and the Jain temples', 'Sound-and-light show', 'Raneh Falls canyon (20 km)', 'Panna Tiger Reserve safari (45 min)', 'Khajuraho Dance Festival (Feb)'], food: ['Raja Café opposite the western group', 'Lalit Temple View dining', 'Bundelkhandi thali'], stay: { budget: '—', mid: 'Ramada Khajuraho, Radisson Jass · €80–140', lux: 'The Lalit Temple View, Sarai at Toria (Panna) · €150–350' }, area: 'Flights from Delhi/Varanasi on select days; or Vande Bharat to Jhansi/Orchha then 4 h by car. Bandhavgarh is 5 h by road.', perDay: '€50 – 300' },
    { id: 'bandhavgarh', region: 'central', airport: null, via: 'HJR', priceIndex: 1.7, months: [2,3,3,3,3,2,0,0,0,2,3,3], comfort: { score: 4, hospital: 'Umaria district hospital (basic); Jabalpur 4 h', notes: ['Highest tiger density in India — but still book 3–4 safaris to be sure.', 'Park closes Jul–Sep; Oct–Jun season, best sightings Mar–Jun.', 'Lodges handle permits, jeeps and naturalists; remote otherwise.'] }, lat: 23.70, lng: 81.03, hours: 8, transfer: 200, type: 'wildlife', from: '4 h from Jabalpur airport · 5 h from Khajuraho', nights: '3 nights', name: 'Bandhavgarh', tag: 'The best tiger odds in India', emoji: '🐯', hue: 'linear-gradient(135deg,#fde047,#713f12)', weather: '8–28 °C in Nov · dry', intro: 'Sal forest and meadows below an ancient hill fort, with the densest tiger population in the country. Sightings are frequent, lodges are superb and the pace is slow.', todo: ['Morning and evening jeep safaris (Tala zone is the classic)', 'Bandhavgarh Fort walk (permit)', 'Full-day safari permit for serious photographers', 'Village walk and Baiga tribal art', 'Night drives in the buffer zone'], food: ['Full board at the lodge', 'Bush breakfasts after the morning drive'], stay: { budget: '—', mid: 'Kings Lodge, Tree House Hideaway · €150–300 full board', lux: 'Samode Safari Lodge, Mahua Kothi (Taj), Bandhav Vilas · €400–900 full board' }, area: 'Fly to Jabalpur (from Delhi/Mumbai) then 4 h by car, or drive from Khajuraho (5 h). Kanha is 5 h away for a two-park trip.', perDay: '€120 – 700' },
    { id: 'kanha', region: 'central', airport: null, via: 'HJR', priceIndex: 1.6, months: [2,3,3,3,3,2,0,0,0,2,3,3], comfort: { score: 4, hospital: 'Mandla hospital (basic); Jabalpur 3.5 h · Nagpur 5 h', notes: ['The "Jungle Book" forest — huge park, sightings spread out; stay 3 nights.', 'Closed Jul–Sep.', 'Lodges are remote and excellent; no independent driving inside.'] }, lat: 22.33, lng: 80.63, hours: 9, transfer: 200, type: 'wildlife', from: '3.5 h from Jabalpur · 5 h from Nagpur airport', nights: '3 nights', name: 'Kanha', tag: 'The Jungle Book forest', emoji: '🦌', hue: 'linear-gradient(135deg,#86efac,#166534)', weather: '8–27 °C in Nov · dry', intro: 'Sal and bamboo forest, wide meadows, the rare barasingha swamp deer and tigers with room to roam. Bigger and wilder than Bandhavgarh; pair the two.', todo: ['Jeep safaris in Kanha, Kisli and Mukki zones', 'Barasingha herds on the Kanha meadow', 'Bamni Dadar sunset point', 'Kanha Museum at Kisli', 'Gond and Baiga village visit', 'Birding walks in the buffer'], food: ['Lodge full board', 'Local Gond cooking demos at some lodges'], stay: { budget: '—', mid: 'Kanha Earth Lodge, Chitvan Jungle Lodge · €150–300 full board', lux: 'Banjaar Tola (Taj), Singinawa Jungle Lodge · €400–900 full board' }, area: 'Fly to Jabalpur or Nagpur, then car. Bandhavgarh is 5 h; many do both.', perDay: '€120 – 700' },
    { id: 'aurangabad', region: 'west', airport: 'IXU', via: null, priceIndex: 1.0, months: [3,3,2,1,0,0,1,1,2,3,3,3], comfort: { score: 4, hospital: 'MGM Hospital · Kamalnayan Bajaj Hospital', notes: ['Ajanta is a 2.5 h drive each way — leave early, take water.', 'Ellora closes Tuesdays; Ajanta closes Mondays.', 'Solid mid-range hotels; the city itself is a base, not a sight.'] }, lat: 19.88, lng: 75.34, hours: 5, transfer: 130, type: 'culture', from: '1 h flight from Mumbai · 2 h from Delhi', nights: '2–3 nights', name: 'Ajanta & Ellora', tag: 'Rock-cut caves of three faiths', emoji: '🪨', hue: 'linear-gradient(135deg,#d6d3d1,#57534e)', weather: '15–30 °C in Nov · dry', intro: 'Two UNESCO sites: the Buddhist painted caves of Ajanta (2nd century BC) and Ellora\'s Kailasa temple, carved top-down from a single cliff. Among the greatest art in Asia and rarely crowded.', todo: ['Ellora: Kailasa Temple (Cave 16) and the Jain caves', 'Ajanta: painted caves 1, 2, 16, 17 with a guide', 'Daulatabad Fort on the way to Ellora', 'Bibi ka Maqbara, the "mini Taj"', 'Paithani silk weaving in Paithan', 'Grishneshwar temple'], food: ['Naan qalia, the Aurangabad speciality', 'Bhoj thali', 'Hotel restaurants at Vivanta and Ambassador Ajanta'], stay: { budget: '—', mid: 'Vivanta Aurangabad, Lemon Tree · €80–140', lux: 'Vivanta suites, WelcomHotel Rama · €120–200' }, area: 'Flights from Mumbai and Delhi. Car with driver for both cave sites (Ellora 45 min, Ajanta 2.5 h).', perDay: '€50 – 220' },
    { id: 'kutch', region: 'west', airport: 'BHJ', via: null, priceIndex: 1.2, months: [3,3,2,0,0,0,0,0,0,2,3,3], comfort: { score: 3, hospital: 'GK General Hospital Bhuj; Ahmedabad 6 h', notes: ['Rann is a border area: carry passport, permits arranged by camps.', 'Gujarat is a dry state — no alcohol (permits for tourists possible but tedious).', 'Season is Nov–Feb only; the Rann Utsav tent city runs then.'] }, lat: 23.25, lng: 69.67, hours: 7, transfer: 180, type: 'culture', from: '1 h 30 flight from Mumbai to Bhuj', nights: '2–3 nights', name: 'Kutch & the White Rann', tag: 'Salt desert, full moon, craft villages', emoji: '🌕', hue: 'linear-gradient(135deg,#f8fafc,#64748b)', weather: '12–30 °C in Nov · dry', intro: 'A white salt desert that glows under the full moon, and villages of embroiderers, weavers and bell-makers around Bhuj. Go around the full moon for the Rann at its most surreal.', todo: ['White Rann at sunset and full moon (permit)', 'Kala Dungar black hill viewpoint', 'Craft villages: Nirona (rogan art), Bhujodi (weaving), Hodka', 'Aina Mahal and Prag Mahal in Bhuj', 'Mandvi beach and shipbuilding yard', 'Living & Learning Design Centre museum'], food: ['Kutchi dabeli', 'Gujarati thali at Hotel Prince', 'Camp dinners with folk music'], stay: { budget: '—', mid: 'Shaam-e-Sarhad (Hodka), Regenta Resort Bhuj · €80–160', lux: 'Rann Utsav premium tents, The Fern Residency · €150–350' }, area: 'Fly Mumbai → Bhuj. Car with driver for the desert and villages (1–2 h each way).', perDay: '€50 – 300' },

    /* ---------------- East & North-east ---------------- */
    { id: 'darjeeling', region: 'east', airport: null, via: 'IXB', priceIndex: 1.1, months: [1,2,3,3,2,0,0,0,1,3,3,2], comfort: { score: 3, hospital: 'Planters\' Hospital Darjeeling (basic); Siliguri 3 h', notes: ['3 h winding drive from Bagdogra airport; go by day.', 'Political strikes occasionally shut the hills — check news before travel.', 'Cold and clear Oct–Nov: best Kanchenjunga views. Foggy in monsoon.'] }, lat: 27.04, lng: 88.26, hours: 5, transfer: 150, type: 'hills', from: '1 h flight to Bagdogra from Kolkata + 3 h', nights: '2–3 nights', name: 'Darjeeling', tag: 'Tea, toy train, Kanchenjunga', emoji: '🍵', hue: 'linear-gradient(135deg,#bbf7d0,#1e3a8a)', weather: '5–16 °C in Nov · clearest skies', intro: 'Colonial tea town on a ridge facing Kanchenjunga, the world\'s third-highest mountain. A UNESCO steam railway, first-flush tea and Tibetan monasteries.', todo: ['Tiger Hill sunrise over Kanchenjunga', 'Darjeeling Himalayan Railway joyride (UNESCO)', 'Happy Valley or Makaibari tea estate tasting', 'Ghoom Monastery', 'Himalayan Mountaineering Institute & zoo (red pandas)', 'Mall Road and Glenary\'s bakery'], food: ['Glenary\'s for breakfast and cake', 'Kunga for Tibetan momos', 'Keventer\'s rooftop breakfast', 'Estate lunches at Glenburn'], stay: { budget: '—', mid: 'Mayfair Darjeeling, Windamere Hotel (heritage) · €100–200', lux: 'Glenburn Tea Estate (all inclusive), Elgin Darjeeling · €250–600' }, area: 'Fly to Bagdogra (from Kolkata or Delhi), then 3 h by car. Combine with Gangtok (4 h).', perDay: '€50 – 350' },
    { id: 'gangtok', region: 'east', airport: null, via: 'IXB', priceIndex: 1.2, months: [1,2,3,3,2,0,0,0,1,3,3,2], comfort: { score: 4, hospital: 'STNM Hospital Gangtok (good for the region)', notes: ['Clean, orderly, litter-free state with strict rules; excellent for first-timers to the Himalaya.', 'Permits for Tsomgo Lake and Nathu La arranged by hotels (passport photos needed).', 'Roads to North Sikkim are rough; luxury stays are in and around Gangtok.'] }, lat: 27.33, lng: 88.61, hours: 5, transfer: 160, type: 'hills', from: '4 h from Bagdogra airport', nights: '2–3 nights', name: 'Gangtok & Sikkim', tag: 'Monasteries and the Kanchenjunga wall', emoji: '🏔️', hue: 'linear-gradient(135deg,#c7d2fe,#312e81)', weather: '6–18 °C in Nov · clear', intro: 'A tidy Himalayan capital with big monasteries, cardamom forests and a wall of snow peaks. Sikkim is India\'s calmest, cleanest state — organic by law, and alcohol is legal, unlike much of the north-east.', todo: ['Rumtek Monastery', 'Tsomgo Lake and Baba Mandir (permit)', 'Tashi viewpoint at sunrise', 'MG Marg pedestrian street', 'Pelling and the Khecheopalri lake (day 2 base)', 'Temi tea garden'], food: ['Sikkimese thali with gundruk and nettle soup', 'Momos everywhere; Taste of Tibet', 'Chhurpi cheese and millet beer (tongba)'], stay: { budget: '—', mid: 'Mayfair Spa Resort, Denzong Regency · €120–220', lux: 'Mayfair suites, Elgin Nor-Khill, Taj Guras Kutir · €200–400' }, area: 'Bagdogra airport then 4 h; pair with Darjeeling. Pakyong airport near Gangtok has unreliable flights.', perDay: '€60 – 300' },
    { id: 'kaziranga', region: 'east', airport: null, via: 'GAU', priceIndex: 1.5, months: [3,3,3,2,0,0,0,0,0,1,3,3], comfort: { score: 4, hospital: 'Tezpur / Jorhat hospitals (2 h); Guwahati 4 h', notes: ['Park open Nov–Apr only; floods close it in monsoon.', 'Elephant-back safaris exist; jeep safaris are the ethical, comfortable choice.', 'Assam is safe for tourists; Guwahati airport is the practical gateway.'] }, lat: 26.58, lng: 93.17, hours: 6, transfer: 190, type: 'wildlife', from: '4 h from Guwahati airport', nights: '2–3 nights', name: 'Kaziranga', tag: 'One-horned rhinos on the Brahmaputra', emoji: '🦏', hue: 'linear-gradient(135deg,#d9f99d,#3f6212)', weather: '12–26 °C in Nov · pleasant', intro: 'Two-thirds of the world\'s one-horned rhinos, wild elephants, buffalo and tigers in tall grassland by the Brahmaputra. Sightings are near-guaranteed and the tea-garden lodges are lovely.', todo: ['Jeep safaris in Kohora and Bagori ranges', 'Early-morning elephant grass at Bagori', 'Brahmaputra river cruise from Neamati', 'Tea-estate stay near Jorhat', 'Majuli river island (day trip)', 'Kaziranga Orchid Park'], food: ['Assamese thali: khar, fish tenga, duck curry', 'Lodge dining'], stay: { budget: '—', mid: 'Diphlu River Lodge, Iora Resort · €120–250', lux: 'Diphlu suites, Wild Grass (heritage) · €250–400' }, area: 'Fly to Guwahati (from Delhi, Kolkata, Bengaluru), then 4 h by car. Jorhat airport is 2 h but has fewer flights.', perDay: '€80 – 350' },
    { id: 'shillong', region: 'east', airport: null, via: 'GAU', priceIndex: 1.1, months: [2,2,3,3,2,0,0,0,2,3,3,2], comfort: { score: 4, hospital: 'NEIGRIHMS Shillong (major hospital)', notes: ['Very safe, English-speaking, musical; roads narrow.', 'Cherrapunji is the wettest place on earth — even in the dry season carry rain gear.', 'Root-bridge treks involve thousands of steps: good knees required.'] }, lat: 25.58, lng: 91.89, hours: 6, transfer: 130, type: 'hills', from: '3 h from Guwahati airport', nights: '3 nights', name: 'Shillong & Meghalaya', tag: 'Living root bridges & waterfalls', emoji: '🌿', hue: 'linear-gradient(135deg,#6ee7b7,#064e3b)', weather: '10–22 °C in Nov · dry, clear', intro: 'Pine hills, Khasi villages, crystal rivers and bridges grown from living tree roots. The cleanest village in Asia, canyons at Cherrapunji, and a café culture with live music.', todo: ['Double-decker living root bridge at Nongriat (3,000 steps)', 'Dawki river, clear as glass, by boat', 'Mawlynnong, "Asia\'s cleanest village"', 'Cherrapunji canyons and Nohkalikai Falls', 'Mawsmai caves', 'Shillong Peak and Ward\'s Lake'], food: ['Jadoh (Khasi rice and pork)', 'Café Shillong live-music evenings', 'Dylan\'s Café', 'Trattoria for Khasi thali'], stay: { budget: '—', mid: 'Ri Kynjai resort (lake), Courtyard by Marriott Shillong · €100–180', lux: 'Ri Kynjai suites, Polo Orchid Cherrapunji · €150–300' }, area: 'Guwahati airport, then 3 h. A car with driver for the whole stay; Cherrapunji is 2 h from Shillong.', perDay: '€50 – 250' },
    { id: 'puri', region: 'east', airport: null, via: 'BBI', priceIndex: 0.9, months: [3,3,2,1,0,0,0,1,1,2,3,3], comfort: { score: 3, hospital: 'Puri district hospital (basic); AIIMS Bhubaneswar 1.5 h', notes: ['Jagannath Temple admits Hindus only; the view from the library roof is the alternative.', 'Rath Yatra (Jun–Jul) draws a million people — avoid unless that is the point.', 'Beach currents are strong; swim only near lifeguards.'] }, lat: 19.81, lng: 85.83, hours: 4, transfer: 110, type: 'culture', from: '1.5 h from Bhubaneswar airport', nights: '2 nights', name: 'Puri & Konark', tag: 'The Sun Temple & a sacred shore', emoji: '☀️', hue: 'linear-gradient(135deg,#fdba74,#7c2d12)', weather: '18–30 °C in Nov · pleasant', intro: 'The 13th-century Sun Temple at Konark, a chariot in stone, is one of India\'s three or four greatest monuments. Puri adds a pilgrim town, a long beach and Raghurajpur\'s painters.', todo: ['Konark Sun Temple with an ASI guide', 'Raghurajpur artists\' village (pattachitra)', 'Puri beach at dawn', 'Bhubaneswar temples: Lingaraj, Mukteshwar', 'Chilika Lake dolphins and birds (2 h)', 'Udayagiri & Khandagiri caves'], food: ['Odia thali with dalma', 'Chhena poda dessert', 'Wildgrass restaurant, Puri'], stay: { budget: '—', mid: 'Mayfair Heritage Puri, Toshali Sands · €80–160', lux: 'Mayfair Waves, Lotus Eco Resort Konark · €150–250' }, area: 'Fly to Bhubaneswar (from Delhi, Kolkata, Bengaluru), 1.5 h to Puri. Konark is 45 min along the coast road.', perDay: '€45 – 220' },

    /* ---------------- South additions ---------------- */
    { id: 'thanjavur', region: 'south', airport: null, via: 'TRZ', priceIndex: 0.9, months: [3,3,2,1,0,0,1,1,2,1,1,2], comfort: { score: 4, hospital: 'Apollo Trichy (1 h) · Thanjavur Medical College', notes: ['Hot most of the year; temples are best at dawn and dusk.', 'Nov–Dec is the northeast monsoon: showers, rarely all day.', 'Modest dress; men remove shirts in some inner sanctums (guides will advise).'] }, lat: 10.79, lng: 79.14, hours: 3, transfer: 100, type: 'culture', from: '1 h from Trichy airport', nights: '2 nights', name: 'Thanjavur & Trichy', tag: 'Chola temples of the Kaveri delta', emoji: '🛕', hue: 'linear-gradient(135deg,#fde68a,#78350f)', weather: '23–31 °C in Nov · warm, some rain', intro: 'The Brihadeeswara Temple, a thousand years old and still the tallest of its kind, plus the Chola bronzes, Tanjore paintings and the rock fort and island temple of Trichy. Deep South India for lovers of art.', todo: ['Brihadeeswara Temple (UNESCO) at dusk', 'Thanjavur Palace and the Saraswathi Mahal library', 'Tanjore painting workshop', 'Sri Ranganathaswamy, the largest temple in India (Srirangam)', 'Rock Fort temple climb in Trichy', 'Darasuram and Gangaikondacholapuram (UNESCO)'], food: ['Thanjavur thali on banana leaf', 'Filter coffee at Kumbakonam', 'Sangeetha and Vasanta Bhavan for vegetarian classics'], stay: { budget: '—', mid: 'Svatma (heritage), Sangam Hotel Trichy · €90–180', lux: 'Svatma suites, Mantra Koodam (CGH Earth, Kumbakonam) · €150–300' }, area: 'Fly to Trichy (from Chennai/Bengaluru, and nonstop from the Gulf), then 1 h. Best by car with a guide.', perDay: '€45 – 250' },
    { id: 'kodaikanal', region: 'south', airport: null, via: 'IXM', priceIndex: 1.0, months: [3,3,3,3,2,1,1,1,2,2,2,3], comfort: { score: 4, hospital: 'KMC Hospital Kodaikanal (basic); Madurai 3 h', notes: ['Cool, misty, walkable; a quieter alternative to Ooty.', 'Ghat road from Madurai: 3 h, by day.', 'Nights drop to 5–10 °C in winter.'] }, lat: 10.24, lng: 77.49, hours: 5, transfer: 90, type: 'hills', from: '3 h from Madurai airport', nights: '2 nights', name: 'Kodaikanal', tag: 'The princess of hill stations', emoji: '🌫️', hue: 'linear-gradient(135deg,#bae6fd,#0c4a6e)', weather: '10–20 °C in Nov · cool, showers', intro: 'A star-shaped lake, cliff walks, shola forest and homemade chocolate at 2,100 m in the Palani hills. Gentler and greener than Ooty, and 3 h from Madurai\'s temples.', todo: ['Coaker\'s Walk cliff path at dawn', 'Cycling around Kodai Lake', 'Pillar Rocks and Guna Caves', 'Vattakanal and Dolphin\'s Nose hike', 'Berijam Lake forest permit drive', 'Chocolate and cheese shopping on Bazaar Road'], food: ['Cloud Street café', 'Homemade chocolate everywhere', 'Tava for South-Indian vegetarian', 'Carlton\'s lakeside dining'], stay: { budget: '—', mid: 'The Tamara Kodai, Sterling Kodai Lake · €100–180', lux: 'The Tamara suites, The Carlton · €150–300' }, area: 'Madurai airport then 3 h by car. Combine with Madurai and Thanjavur for a Tamil Nadu loop.', perDay: '€50 – 250' },
  ];

  /* Hotel picks (4★ floor), restaurants, operators, airports, search cities */
  const picks = {
    agra: [{ n: 'The Oberoi Amarvilas', tier: 'lux', area: '600 m from the Taj', why: 'Taj view from every room and the pool; the best hotel in Agra by a distance.' }, { n: 'ITC Mughal', tier: 'mid', area: 'Fatehabad Road', why: 'Mughal-garden resort with Peshawri restaurant and a huge spa.' }, { n: 'Trident Agra', tier: 'mid', area: 'Fatehabad Road', why: 'Calm courtyard hotel, reliable, good value.' }, { n: 'Taj Hotel & Convention Centre Agra', tier: 'mid', area: 'Taj East Gate', why: 'Modern, rooftop Taj view.' }],
    jaipur: [{ n: 'Rambagh Palace', tier: 'lux', area: 'Bhawani Singh Road', why: 'Former Maharaja\'s palace with peacocks on the lawns.' }, { n: 'The Oberoi Rajvilas', tier: 'lux', area: 'Goner Road', why: 'Villa resort around a 280-year-old temple.' }, { n: 'Samode Haveli', tier: 'mid', area: 'Old city', why: 'Painted haveli with a pool; real Jaipur atmosphere.' }, { n: 'Trident Jaipur', tier: 'mid', area: 'Amber Road', why: 'Lake views towards Jal Mahal, dependable.' }, { n: 'Alsisar Haveli', tier: 'mid', area: 'Sansar Chandra Road', why: 'Heritage haveli close to the bazaars.' }],
    jodhpur: [{ n: 'Umaid Bhawan Palace', tier: 'lux', area: 'Umaid Bhawan', why: 'Art-deco palace, half museum, half hotel; the Maharaja still lives here.' }, { n: 'RAAS Jodhpur', tier: 'lux', area: 'Old city', why: 'Modern boutique hotel beneath Mehrangarh with fort views.' }, { n: 'Pal Haveli', tier: 'mid', area: 'Clock tower', why: 'Family-run haveli with the Indique rooftop.' }, { n: 'Ranbanka Palace', tier: 'mid', area: 'Circuit House Road', why: 'Heritage palace at a fair price.' }],
    udaipur: [{ n: 'Taj Lake Palace', tier: 'lux', area: 'Lake Pichola', why: 'The marble palace floating in the lake, reached by boat.' }, { n: 'The Oberoi Udaivilas', tier: 'lux', area: 'Haridasji ki Magri', why: 'Domes, courtyards and pools on the lake shore.' }, { n: 'The Leela Palace Udaipur', tier: 'lux', area: 'Lake Pichola', why: 'Every room faces the lake and City Palace.' }, { n: 'Jagat Niwas Palace', tier: 'mid', area: 'Lal Ghat', why: 'Lakeside haveli with a rooftop restaurant, superb value.' }, { n: 'Trident Udaipur', tier: 'mid', area: 'Haridasji ki Magri', why: 'Gardens by the lake, quiet, good pool.' }],
    jaisalmer: [{ n: 'Suryagarh', tier: 'lux', area: 'Kahala Phata', why: 'A modern fort on the desert edge with legendary breakfasts and desert dinners.' }, { n: 'The Serai (Sujan)', tier: 'lux', area: 'Chandan', why: 'Luxury tented camp in a private desert reserve.' }, { n: 'Fort Rajwada', tier: 'mid', area: 'Jodhpur–Barmer link road', why: 'Large heritage-style hotel, pool, reliable.' }, { n: 'Jaisalmer Marriott', tier: 'mid', area: 'Jaisalmer', why: 'Modern comfort with fort views.' }],
    pushkar: [{ n: 'The Westin Pushkar Resort & Spa', tier: 'lux', area: 'Ajmer road', why: 'Full resort with pools; calm base for the fair.' }, { n: 'Ananta Spa & Resort', tier: 'lux', area: 'Village Tilora', why: 'Hillside resort with big rooms.' }, { n: 'Pushkar Palace', tier: 'mid', area: 'Lakeside', why: 'Heritage palace on the lake.' }, { n: 'Dera Masuda', tier: 'mid', area: 'Ajmer road', why: 'Boutique haveli-style stay.' }],
    ranthambore: [{ n: 'The Oberoi Vanyavilas', tier: 'lux', area: 'Ranthambore Road', why: 'Luxury tents with private gardens; the finest safari lodge in India.' }, { n: 'Aman-i-Khás', tier: 'lux', area: 'Sherpur', why: 'Ten tents, absolute peace, Aman service.' }, { n: 'Sher Bagh (Sujan)', tier: 'lux', area: 'Sherpur', why: '1920s-style tented camp with expert naturalists.' }, { n: 'Ranthambhore Regency', tier: 'mid', area: 'Ranthambore Road', why: 'Pool, gardens, well-run safaris.' }, { n: 'Tiger Den Resort', tier: 'mid', area: 'Ranthambore Road', why: 'Cottages, good food, good value.' }],
    amritsar: [{ n: 'Taj Swarna', tier: 'lux', area: 'Amritsar', why: 'The best rooms in town; 15 min to the temple.' }, { n: 'Hyatt Regency Amritsar', tier: 'mid', area: 'GT Road', why: 'Modern, spacious, next to the mall.' }, { n: 'Ramada Amritsar', tier: 'mid', area: 'Hall Bazaar', why: 'Walking distance to the Golden Temple.' }],
    shimla: [{ n: 'Wildflower Hall (Oberoi)', tier: 'lux', area: 'Mashobra', why: 'Kipling\'s former estate in cedar forest at 2,500 m; pool with mountain views.' }, { n: 'The Oberoi Cecil', tier: 'lux', area: 'Chaura Maidan', why: 'Colonial grande dame on the Mall.' }, { n: 'Clarkes Shimla', tier: 'mid', area: 'The Mall', why: 'Oberoi heritage hotel at a fair price.' }, { n: 'Radisson Jass Shimla', tier: 'mid', area: 'Lower Bazaar', why: 'Modern, central, good views.' }],
    manali: [{ n: 'Span Resort & Spa', tier: 'lux', area: 'Kullu–Manali highway, by the Beas', why: 'Riverside cottages, spa, quiet.' }, { n: 'The Himalayan', tier: 'lux', area: 'Hadimba Road', why: 'Gothic castle hotel in an apple orchard.' }, { n: 'Lodge at Wah', tier: 'lux', area: 'Naggar', why: 'Boutique estate stay among orchards.' }, { n: 'Manuallaya Resort', tier: 'mid', area: 'Old Manali', why: 'Spa resort with valley views.' }],
    dharamshala: [{ n: 'Hyatt Regency Dharamshala Resort', tier: 'lux', area: 'Dharamshala', why: 'Best rooms in the valley, spa, mountain views.' }, { n: 'Chonor House', tier: 'mid', area: 'McLeod Ganj', why: 'Norbulingka-run guesthouse with hand-painted rooms.' }, { n: 'Norwood Green', tier: 'mid', area: 'Palampur', why: 'Tea-estate villas 40 min away.' }, { n: 'Rakkh Resort', tier: 'mid', area: 'Palampur', why: 'Cottages with Dhauladhar views.' }],
    leh: [{ n: 'Chamba Camp Thiksey (TUTC)', tier: 'lux', area: 'Thiksey', why: 'Ultra-luxury tents below Thiksey monastery.' }, { n: 'The Grand Dragon Ladakh', tier: 'lux', area: 'Leh', why: 'The best hotel in town, oxygen-enriched rooms.' }, { n: 'Stone Hedge Hotel', tier: 'mid', area: 'Nubra Valley', why: 'Boutique stone lodge for the Nubra night.' }, { n: 'Ladakh Sarai', tier: 'mid', area: 'Stok', why: 'Cottages in the fields outside Leh.' }],
    corbett: [{ n: 'Aahana Resort', tier: 'lux', area: 'Sawaldeh village', why: 'Eco-resort by the park boundary with spa and pool.' }, { n: 'Jim\'s Jungle Retreat', tier: 'lux', area: 'Dhela', why: 'Superb naturalists and cottages by the forest.' }, { n: 'Taj Corbett Resort & Spa', tier: 'mid', area: 'Dhikuli', why: 'Riverside Taj with pool, families welcome.' }, { n: 'Riverview Retreat', tier: 'mid', area: 'Dhikuli', why: 'Cottages on the Kosi river, reliable.' }],
    khajuraho: [{ n: 'The Lalit Temple View', tier: 'lux', area: 'Western group', why: 'Views of the temples from the garden.' }, { n: 'Sarai at Toria', tier: 'lux', area: 'Panna (45 min)', why: 'Riverside eco-lodge run by conservationists.' }, { n: 'Ramada by Wyndham Khajuraho', tier: 'mid', area: 'Airport road', why: 'Pool and gardens near the temples.' }, { n: 'Radisson Jass Khajuraho', tier: 'mid', area: 'Bypass road', why: 'Dependable, good restaurant.' }],
    bandhavgarh: [{ n: 'Mahua Kothi (Taj Safaris)', tier: 'lux', area: 'Tala', why: 'Kothi-style villas and expert naturalists.' }, { n: 'Samode Safari Lodge', tier: 'lux', area: 'Mardari', why: 'Village-style villas, superb food.' }, { n: 'Kings Lodge (Pugdundee)', tier: 'mid', area: 'Bijhariya', why: 'Cottages in forest, strong conservation focus.' }, { n: 'Tree House Hideaway', tier: 'mid', area: 'Tala', why: 'Five tree houses in a forest of sal.' }],
    kanha: [{ n: 'Banjaar Tola (Taj Safaris)', tier: 'lux', area: 'Mukki gate', why: 'Tented suites on the Banjaar river.' }, { n: 'Singinawa Jungle Lodge', tier: 'lux', area: 'Mukki', why: 'Stone cottages, art gallery, great guides.' }, { n: 'Kanha Earth Lodge (Pugdundee)', tier: 'mid', area: 'Kanha', why: 'Cottages built from local materials in the buffer.' }, { n: 'Chitvan Jungle Lodge', tier: 'mid', area: 'Mukki', why: 'Pool and spa, family-friendly.' }],
    aurangabad: [{ n: 'Vivanta Aurangabad', tier: 'lux', area: 'Rauza Bagh', why: 'Garden hotel in Mughal style, the best in the city.' }, { n: 'WelcomHotel Rama International', tier: 'mid', area: 'Chikalthana', why: 'Large grounds near the airport.' }, { n: 'Lemon Tree Hotel Aurangabad', tier: 'mid', area: 'Chikalthana', why: 'Modern, sensible base.' }],
    kutch: [{ n: 'Rann Utsav Tent City (premium)', tier: 'lux', area: 'Dhordo', why: 'Government-run tent city at the Rann with all comforts (Nov–Feb).' }, { n: 'Shaam-e-Sarhad', tier: 'mid', area: 'Hodka', why: 'Community-run village resort with mud bhungas.' }, { n: 'Regenta Resort Bhuj', tier: 'mid', area: 'Bhuj', why: 'Best conventional hotel in Bhuj.' }, { n: 'The Fern Residency Bhuj', tier: 'mid', area: 'Bhuj', why: 'Reliable, central.' }],
    darjeeling: [{ n: 'Glenburn Tea Estate', tier: 'lux', area: 'Glenburn', why: 'Planter\'s bungalow on a working estate, all-inclusive, Kanchenjunga views.' }, { n: 'Mayfair Darjeeling', tier: 'lux', area: 'The Mall', why: 'Former Maharaja\'s summer palace.' }, { n: 'Windamere Hotel', tier: 'mid', area: 'Observatory Hill', why: 'Time-capsule colonial hotel, fires and afternoon tea.' }, { n: 'Elgin Darjeeling', tier: 'mid', area: 'HD Lama Road', why: 'Heritage hotel with a good restaurant.' }],
    gangtok: [{ n: 'Mayfair Spa Resort & Casino', tier: 'lux', area: 'Ranipool', why: 'Big resort with spa and mountain views.' }, { n: 'Taj Guras Kutir Resort & Spa', tier: 'lux', area: 'Gangtok', why: 'New Taj resort with Kanchenjunga views.' }, { n: 'Elgin Nor-Khill', tier: 'mid', area: 'Gangtok', why: 'Former royal guest house.' }, { n: 'Denzong Regency', tier: 'mid', area: 'Gangtok', why: 'Sikkimese architecture and views.' }],
    kaziranga: [{ n: 'Diphlu River Lodge', tier: 'lux', area: 'Kohora', why: 'Stilted cottages on the Diphlu river; superb naturalists.' }, { n: 'Wild Grass Lodge', tier: 'mid', area: 'Kohora', why: 'Heritage lodge in gardens, the original Kaziranga stay.' }, { n: 'Iora — The Retreat', tier: 'mid', area: 'Kohora', why: 'Resort with pool and spa.' }],
    shillong: [{ n: 'Ri Kynjai', tier: 'lux', area: 'Umiam Lake', why: 'Khasi-style cottages above the lake.' }, { n: 'Courtyard by Marriott Shillong', tier: 'mid', area: 'Shillong', why: 'Modern, central.' }, { n: 'Polo Orchid Resort', tier: 'mid', area: 'Cherrapunji', why: 'Cliff-edge resort with canyon views.' }],
    puri: [{ n: 'Mayfair Waves', tier: 'lux', area: 'Puri beach', why: 'Beachfront resort with big gardens.' }, { n: 'Mayfair Heritage', tier: 'mid', area: 'Chakratirtha Road', why: 'Old-style Mayfair by the sea.' }, { n: 'Lotus Eco Resort', tier: 'mid', area: 'Konark', why: 'Cottages on the beach near the Sun Temple.' }],
    thanjavur: [{ n: 'Svatma', tier: 'lux', area: 'Thanjavur', why: 'Heritage boutique hotel with music, art and a superb kitchen.' }, { n: 'Mantra Koodam (CGH Earth)', tier: 'lux', area: 'Kumbakonam', why: 'Village-style resort among temples.' }, { n: 'Sangam Hotel Trichy', tier: 'mid', area: 'Trichy', why: 'Best conventional hotel in Trichy.' }, { n: 'Ideal River View Resort', tier: 'mid', area: 'Thanjavur', why: 'Riverside cottages.' }],
    kodaikanal: [{ n: 'The Tamara Kodai', tier: 'lux', area: 'Kodaikanal', why: 'Restored 1845 building, the best rooms in town.' }, { n: 'The Carlton', tier: 'mid', area: 'Lake Road', why: 'Colonial lakeside hotel.' }, { n: 'Sterling Kodai Lake', tier: 'mid', area: 'Lake', why: 'Reliable resort with lake views.' }],
  };
  const eat = {
    agra: [{ n: 'Peshawri, ITC Mughal', area: 'Fatehabad Road', why: 'Dal bukhara and tandoori, worth the price.' }, { n: 'Pinch of Spice', area: 'Fatehabad Road', why: 'Reliable North-Indian near the Taj.' }, { n: 'Esphahan, Oberoi Amarvilas', area: 'Taj East Gate', why: 'Mughal cuisine with live sitar.' }],
    jaipur: [{ n: 'Laxmi Misthan Bhandar (LMB)', area: 'Johari Bazaar', why: 'Rajasthani thali and sweets since 1727.' }, { n: 'Lassiwala', area: 'MI Road', why: 'Lassi in clay cups, the original shop.' }, { n: 'Suvarna Mahal, Rambagh Palace', area: 'Rambagh', why: 'Royal dining under chandeliers.' }, { n: '1135 AD', area: 'Amber Fort', why: 'Rajasthani royal cuisine inside the fort.' }, { n: 'Tapri Central', area: 'C-Scheme', why: 'Rooftop chai and snacks.' }],
    jodhpur: [{ n: 'Indique, Pal Haveli', area: 'Clock tower', why: 'Rooftop with fort views.' }, { n: 'Shri Mishrilal Hotel', area: 'Clock tower', why: 'Makhaniya lassi since 1927.' }, { n: 'Gypsy Restaurant', area: 'Sardarpura', why: 'Unlimited Rajasthani thali.' }, { n: 'Janta Sweet Home', area: 'Nai Sarak', why: 'Mirchi vada and pyaaz kachori.' }],
    udaipur: [{ n: 'Ambrai', area: 'Amet Haveli', why: 'Lakeside dinner facing the City Palace.' }, { n: 'Upre by 1559 AD', area: 'Lake Pichola Hotel', why: 'Rooftop Rajasthani with lake views.' }, { n: 'Jheel\'s Ginger Coffee Bar & Bakery', area: 'Gangaur Ghat', why: 'Breakfast by the water.' }, { n: 'Millets of Mewar', area: 'Hanuman Ghat', why: 'Healthy Rajasthani, great views.' }],
    jaisalmer: [{ n: 'Suryagarh Restaurant', area: 'Suryagarh', why: 'Desert cuisine done beautifully.' }, { n: 'The Trio', area: 'Gandhi Chowk', why: 'Rooftop Rajasthani near the fort.' }, { n: 'Jaisal Italy', area: 'Fort', why: 'Pasta with fort views (yes, really).' }],
    pushkar: [{ n: 'Sunset Café', area: 'Lakeside', why: 'Lake views at sunset, café food.' }, { n: 'Laughing Buddha Café', area: 'Main bazaar', why: 'Vegetarian world food.' }, { n: 'Honey & Spice', area: 'Laxmi Market', why: 'Wholesome breakfasts.' }],
    ranthambore: [], amritsar: [{ n: 'Kesar da Dhaba', area: 'Chowk Passian', why: 'Dal makhani and lachha paratha since 1916.' }, { n: 'Kulcha Land', area: 'District Shopping Centre', why: 'The Amritsari kulcha.' }, { n: 'Beera Chicken House', area: 'Majitha Road', why: 'Tandoori chicken legend.' }, { n: 'Brothers\' Dhaba', area: 'Town Hall', why: 'Vegetarian Punjabi near the temple.' }],
    shimla: [{ n: 'Wake & Bake Café', area: 'Mall Road', why: 'Coffee, crêpes, views.' }, { n: 'Cecil Restaurant, Oberoi Cecil', area: 'Chaura Maidan', why: 'Colonial dinner.' }, { n: 'Himachali Rasoi', area: 'Middle Bazaar', why: 'Traditional dham thali.' }],
    manali: [{ n: 'Johnson\'s Café', area: 'Circuit House Road', why: 'Trout and apple crumble.' }, { n: 'Café 1947', area: 'Old Manali', why: 'Riverside café with live music.' }, { n: 'Drifters\' Inn', area: 'Old Manali', why: 'Good breakfasts and pizza.' }],
    dharamshala: [{ n: 'Tibet Kitchen', area: 'McLeod Ganj', why: 'Momos and thukpa.' }, { n: 'Lung Ta', area: 'Jogiwara Road', why: 'Japanese vegetarian.' }, { n: 'Illiterati Café', area: 'Jogiwara Road', why: 'Books, coffee, valley view.' }],
    leh: [{ n: 'Bon Appetit', area: 'Changspa', why: 'Dinner with a view of the valley.' }, { n: 'Lamayuru Restaurant', area: 'Fort Road', why: 'Ladakhi and Tibetan classics.' }, { n: 'Gesmo Restaurant', area: 'Fort Road', why: 'Breakfasts and bakery.' }],
    corbett: [], khajuraho: [{ n: 'Raja Café', area: 'Western group', why: 'Garden café facing the temples.' }, { n: 'Mediterraneo', area: 'Jain Temple Road', why: 'Italian, oddly good.' }],
    bandhavgarh: [], kanha: [],
    aurangabad: [{ n: 'Bhoj Restaurant', area: 'Station Road', why: 'Gujarati-Rajasthani thali.' }, { n: 'Green Leaf', area: 'Nirala Bazar', why: 'South-Indian and Maharashtrian.' }, { n: 'Latitude, Vivanta', area: 'Rauza Bagh', why: 'Hotel dining, naan qalia on request.' }],
    kutch: [{ n: 'Hotel Prince Restaurant', area: 'Bhuj', why: 'Gujarati thali.' }, { n: 'Khavda sweets', area: 'Khavda', why: 'Mawa sweets on the way to the Rann.' }],
    darjeeling: [{ n: 'Glenary\'s', area: 'Nehru Road', why: 'Bakery and breakfast with views.' }, { n: 'Kunga Restaurant', area: 'Gandhi Road', why: 'Tibetan momos and thukpa.' }, { n: 'Keventer\'s', area: 'Nehru Road', why: 'Rooftop breakfast, an institution.' }],
    gangtok: [{ n: 'Taste of Tibet', area: 'MG Marg', why: 'Momos and thukpa.' }, { n: 'The Dragon Wok', area: 'MG Marg', why: 'Sikkimese and Chinese.' }, { n: 'Baker\'s Café', area: 'MG Marg', why: 'Coffee and pastries.' }],
    kaziranga: [], shillong: [{ n: 'Café Shillong', area: 'Laitumkhrah', why: 'Live music and Khasi dishes.' }, { n: 'Trattoria', area: 'Police Bazar', why: 'Khasi thali, jadoh.' }, { n: 'Dylan\'s Café', area: 'Laitumkhrah', why: 'Bob Dylan shrine and good coffee.' }],
    puri: [{ n: 'Wildgrass Restaurant', area: 'VIP Road', why: 'Odia cuisine in a garden.' }, { n: 'Chung Wah', area: 'VIP Road', why: 'Indo-Chinese, a Puri favourite.' }],
    thanjavur: [{ n: 'Svatma restaurant', area: 'Thanjavur', why: 'Refined Tamil vegetarian.' }, { n: 'Sathars', area: 'Gandhiji Road', why: 'Biryani and non-veg classics.' }, { n: 'Vasanta Bhavan', area: 'Trichy', why: 'Dosa and filter coffee.' }],
    kodaikanal: [{ n: 'Cloud Street', area: 'PT Road', why: 'Pizza, pasta, coffee.' }, { n: 'Tava', area: 'PT Road', why: 'South-Indian vegetarian.' }, { n: 'Carlton dining room', area: 'Lake Road', why: 'Lakeside buffet.' }],
  };
  const ops = {
    agra: [{ n: 'Taj Mahal tickets (ASI)', kind: 'activity', url: 'https://asi.payumoney.com/', why: 'Timed sunrise slot online; closed Fridays.' }, { n: 'Gatimaan / Vande Bharat (IRCTC)', kind: 'train', url: 'https://www.irctc.co.in/', why: 'Delhi → Agra in 1 h 40.' }],
    jaipur: [{ n: 'Uber / Ola & hotel cars', kind: 'cab', url: 'https://www.uber.com/in/en/', why: 'Reliable across the city; hotel cars for Amber.' }, { n: 'Vande Bharat Delhi → Jaipur (IRCTC)', kind: 'train', url: 'https://www.irctc.co.in/', why: '4 h 30, comfortable.' }, { n: 'Block-printing workshop (Anokhi Museum)', kind: 'activity', url: 'https://www.anokhi.com/museum/', why: 'Book a printing session in Amber.' }],
    jodhpur: [{ n: 'Flying Fox zip line', kind: 'activity', url: 'https://www.flyingfox.asia/', why: 'Six zip lines over the fort lakes; book online.' }, { n: 'Mehrangarh Fort tickets', kind: 'activity', url: 'https://www.mehrangarh.org/', why: 'Audio guide included in the foreigner ticket.' }],
    udaipur: [{ n: 'Lake Pichola boat (City Palace jetty)', kind: 'boat', url: 'https://www.google.com/maps/search/Bansi+Ghat+boat+Udaipur', why: 'Sunset boats from Bansi Ghat; hotels can book.' }, { n: 'Car to Ranakpur & Kumbhalgarh', kind: 'car', url: 'https://www.savaari.com/', why: 'Full-day trip, 2 h each way.' }],
    jaisalmer: [{ n: 'Desert camp via hotel', kind: 'activity', url: 'https://www.google.com/maps/search/Sam+Sand+Dunes+camp', why: 'One night in a luxury camp; hotels arrange camel rides and transfers.' }, { n: 'Car with driver', kind: 'car', url: 'https://www.savaari.com/', why: 'Jodhpur ↔ Jaisalmer 5 h.' }],
    pushkar: [{ n: 'Hot-air balloon (Sky Waltz)', kind: 'activity', url: 'https://www.skywaltz.com/', why: 'Dawn flights over the fair; book ahead.' }, { n: 'Car from Jaipur', kind: 'car', url: 'https://www.savaari.com/', why: '2.5 h.' }],
    ranthambore: [{ n: 'Safari permits (Rajasthan Forest Dept)', kind: 'activity', url: 'https://fmdss.forest.rajasthan.gov.in/', why: 'Official portal; lodges book for guests.' }, { n: 'Train Delhi → Sawai Madhopur (IRCTC)', kind: 'train', url: 'https://www.irctc.co.in/', why: '4 h on the Jan Shatabdi / Vande Bharat.' }],
    amritsar: [{ n: 'Vande Bharat Delhi → Amritsar (IRCTC)', kind: 'train', url: 'https://www.irctc.co.in/', why: '5 h 30.' }, { n: 'Wagah border ceremony', kind: 'activity', url: 'https://www.google.com/maps/search/Attari+Wagah+border', why: 'Free; be there by 15:30; car from the city 45 min.' }],
    shimla: [{ n: 'Kalka–Shimla toy train (IRCTC)', kind: 'train', url: 'https://www.irctc.co.in/', why: 'Book the Shivalik Deluxe or Himalayan Queen.' }, { n: 'Hill car with driver', kind: 'car', url: 'https://www.savaari.com/', why: 'Delhi/Chandigarh → Shimla.' }],
    manali: [{ n: 'Car with driver', kind: 'car', url: 'https://www.savaari.com/', why: 'Chandigarh → Manali 8 h.' }, { n: 'Paragliding Solang (licensed operators)', kind: 'activity', url: 'https://www.google.com/maps/search/paragliding+Solang+Valley', why: 'Check the operator\'s licence; mornings are calmer.' }],
    dharamshala: [{ n: 'Flights to Gaggal (DHM)', kind: 'activity', url: 'https://www.goindigo.in/', why: 'IndiGo / Air India from Delhi; weather-dependent.' }, { n: 'Dalai Lama teachings registration', kind: 'activity', url: 'https://www.dalailama.com/schedule', why: 'Register at the Security Office with passport.' }],
    leh: [{ n: 'Inner Line Permits', kind: 'activity', url: 'https://www.lahdclehpermit.in/', why: 'Online or via your hotel; needed for Nubra and Pangong.' }, { n: 'Car with local driver', kind: 'car', url: 'https://www.google.com/maps/search/taxi+union+Leh', why: 'Leh taxi union fixed rates; hotels arrange.' }],
    corbett: [{ n: 'Safari permits (Uttarakhand Forest)', kind: 'activity', url: 'https://www.corbettonline.uk.gov.in/', why: 'Official portal for zones and Dhikala stays.' }, { n: 'Ranikhet Express (IRCTC)', kind: 'train', url: 'https://www.irctc.co.in/', why: 'Overnight Delhi → Ramnagar.' }],
    khajuraho: [{ n: 'Flights (limited days)', kind: 'activity', url: 'https://www.airindia.com/', why: 'Air India / IndiGo from Delhi and Varanasi on select days.' }, { n: 'Panna safari', kind: 'activity', url: 'https://forest.mponline.gov.in/', why: 'MP Forest online booking.' }],
    bandhavgarh: [{ n: 'Safari booking (MP Forest)', kind: 'activity', url: 'https://forest.mponline.gov.in/', why: 'Lodges book for guests; permits limited.' }, { n: 'Car from Jabalpur / Khajuraho', kind: 'car', url: 'https://www.savaari.com/', why: '4–5 h.' }],
    kanha: [{ n: 'Safari booking (MP Forest)', kind: 'activity', url: 'https://forest.mponline.gov.in/', why: 'Book with the lodge.' }, { n: 'Car from Jabalpur / Nagpur', kind: 'car', url: 'https://www.savaari.com/', why: '3.5–5 h.' }],
    aurangabad: [{ n: 'Car with driver for the caves', kind: 'car', url: 'https://www.savaari.com/', why: 'Ellora 45 min, Ajanta 2.5 h each way.' }, { n: 'ASI tickets Ajanta / Ellora', kind: 'activity', url: 'https://asi.payumoney.com/', why: 'Buy online to skip queues.' }],
    kutch: [{ n: 'Rann permit & camps', kind: 'activity', url: 'https://www.rannutsav.com/', why: 'Rann Utsav tent city; permits at Bhirandiyara checkpoint.' }, { n: 'Car with driver', kind: 'car', url: 'https://www.savaari.com/', why: 'Bhuj ↔ Rann 1.5 h; villages spread out.' }],
    darjeeling: [{ n: 'Darjeeling Himalayan Railway (IRCTC)', kind: 'train', url: 'https://www.irctc.co.in/', why: 'Joyrides sell out; book early.' }, { n: 'Car from Bagdogra', kind: 'car', url: 'https://www.savaari.com/', why: '3 h hill road.' }],
    gangtok: [{ n: 'Permits for Tsomgo / Nathu La', kind: 'activity', url: 'https://sikkimtourism.gov.in/', why: 'Hotels arrange; foreigners need the Restricted Area Permit (free) on entry to Sikkim.' }, { n: 'Car from Bagdogra', kind: 'car', url: 'https://www.savaari.com/', why: '4 h.' }],
    kaziranga: [{ n: 'Safari booking via lodge', kind: 'activity', url: 'https://kaziranga.assam.gov.in/', why: 'Lodges arrange jeeps and permits.' }, { n: 'Car from Guwahati', kind: 'car', url: 'https://www.savaari.com/', why: '4 h on a good highway.' }],
    shillong: [{ n: 'Car with driver for Meghalaya', kind: 'car', url: 'https://www.savaari.com/', why: 'Guwahati → Shillong 3 h; Cherrapunji day trips.' }, { n: 'Root-bridge trek guides', kind: 'activity', url: 'https://www.google.com/maps/search/Nongriat+trek+guide', why: 'Hire a local guide at Tyrna village.' }],
    puri: [{ n: 'Car from Bhubaneswar', kind: 'car', url: 'https://www.savaari.com/', why: '1.5 h; Konark loop by car.' }, { n: 'Chilika Lake boats (OTDC)', kind: 'boat', url: 'https://www.odishatourism.gov.in/', why: 'Government boats from Satapada for dolphins.' }],
    thanjavur: [{ n: 'Car with driver & guide', kind: 'car', url: 'https://www.savaari.com/', why: 'Temples are spread across the delta.' }, { n: 'Flights to Trichy', kind: 'activity', url: 'https://www.goindigo.in/', why: 'IndiGo from Chennai, Bengaluru and the Gulf.' }],
    kodaikanal: [{ n: 'Car from Madurai', kind: 'car', url: 'https://www.savaari.com/', why: '3 h ghat road by day.' }, { n: 'Berijam Lake forest permit', kind: 'activity', url: 'https://www.google.com/maps/search/Berijam+Lake+permit+office', why: 'Permits from the forest office the day before.' }],
  };
  const airports = { agra: 'AGR', jaipur: 'JAI', jodhpur: 'JDH', udaipur: 'UDR', jaisalmer: 'JSA', pushkar: 'JAI', ranthambore: 'JAI', amritsar: 'ATQ', shimla: 'IXC', manali: 'IXC', dharamshala: 'DHM', leh: 'IXL', corbett: 'DEL', khajuraho: 'HJR', bandhavgarh: 'JLR', kanha: 'JLR', aurangabad: 'IXU', kutch: 'BHJ', darjeeling: 'IXB', gangtok: 'IXB', kaziranga: 'GAU', shillong: 'GAU', puri: 'BBI', thanjavur: 'TRZ', kodaikanal: 'IXM' };
  const searchCity = { agra: 'Agra', jaipur: 'Jaipur', jodhpur: 'Jodhpur', udaipur: 'Udaipur', jaisalmer: 'Jaisalmer', pushkar: 'Pushkar', ranthambore: 'Sawai Madhopur', amritsar: 'Amritsar', shimla: 'Shimla', manali: 'Manali', dharamshala: 'McLeod Ganj', leh: 'Leh', corbett: 'Ramnagar Uttarakhand', khajuraho: 'Khajuraho', bandhavgarh: 'Bandhavgarh', kanha: 'Kanha', aurangabad: 'Aurangabad', kutch: 'Bhuj', darjeeling: 'Darjeeling', gangtok: 'Gangtok', kaziranga: 'Kaziranga', shillong: 'Shillong', puri: 'Puri', thanjavur: 'Thanjavur', kodaikanal: 'Kodaikanal' };

  /* ---- merge ---- */
  const T = window.TRIP, G = window.GUIDE;
  T.destinations = T.destinations.filter((d) => d.id !== 'goldentriangle' && d.id !== 'rajasthan').concat(D);
  Object.assign(G.picks, picks); Object.assign(G.eat, eat); Object.assign(G.ops, ops); Object.assign(G.airports, airports); Object.assign(G.searchCity, searchCity);
  delete G.picks.goldentriangle; delete G.picks.rajasthan; delete G.eat.goldentriangle; delete G.eat.rajasthan; delete G.ops.goldentriangle; delete G.ops.rajasthan;
  G.roadOnly.push('pushkar', 'ranthambore', 'shimla', 'manali', 'corbett', 'bandhavgarh', 'kanha', 'darjeeling', 'gangtok', 'kaziranga', 'shillong', 'puri', 'thanjavur', 'kodaikanal');
  // retire the 'far' type now that the site covers all of India
  T.destinations.forEach((d) => { if (d.type === 'far') d.type = d.id === 'rishikesh' ? 'hills' : 'culture'; });
})();
