/* Generated by tools/fetch-photos.mjs — do not edit by hand. Credits in img/CREDITS.md */
window.PHOTOS = {
 "goa": {
  "src": "img/goa.jpg",
  "author": "iMahesh",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Palolem_Beach,_South_Goa.jpg"
 },
 "munnar": {
  "src": "img/munnar.jpg",
  "author": "Kondephy",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Munnar_Overview.jpg"
 },
 "kochi": {
  "src": "img/kochi.jpg",
  "author": "Timothy A",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Chinese_Fishing_Net_Raising_Birds_Sunrise_Ashtamudi_Kollam_Mar22_A7C_01784.jpg"
 },
 "thekkady": {
  "src": "img/thekkady.jpg",
  "author": "Wouter Hagens",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Periyar_National_Park.JPG"
 },
 "mysuru": {
  "src": "img/mysuru.jpg",
  "author": "Ingo Mehling",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Mysuru_Palace_-_Night_View.jpg"
 },
 "coorg": {
  "src": "img/coorg.jpg",
  "author": "Jyotirmoy",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Tadiandamol_Valley,_Western_Ghats.jpg"
 },
 "hampi": {
  "src": "img/hampi.jpg",
  "author": "iMahesh",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Wide_angle_of_Galigopuram_of_Virupaksha_Temple,_Hampi_(04)_(cropped).jpg"
 },
 "hyderabad": {
  "src": "img/hyderabad.jpg",
  "author": "Bernard Gagnon",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Golconda_Fort_005.jpg"
 },
 "kabini": {
  "src": "img/kabini.jpg",
  "author": "Paul Mannix",
  "license": "CC BY 2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Bengal_Tiger_Karnataka.jpg"
 },
 "wayanad": {
  "src": "img/wayanad.jpg",
  "author": "KSEB",
  "license": "CC BY-SA 2.5",
  "page": "https://commons.wikimedia.org/wiki/File:Banasurasagar_Main_Dam.jpg"
 },
 "varkala": {
  "src": "img/varkala.jpg",
  "author": "Kondephy",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Varkala_beach_from_above.jpg"
 },
 "badami": {
  "src": "img/badami.jpg",
  "author": "Sanyam Bahga",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:BadamiCaves87.JPG"
 },
 "pondicherry": {
  "src": "img/pondicherry.jpg",
  "author": "Matthew T Rader",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:The_Matrimandir_in_Auroville,_Tamil_Nadu,_India.jpg"
 },
 "goldentriangle": {
  "src": "img/goldentriangle.jpg",
  "author": "Yann; edited by Jim Carter",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Taj_Mahal_(Edited).jpeg"
 },
 "rajasthan": {
  "src": "img/rajasthan.jpg",
  "author": "user:Flicka",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Udaipur_Lake_Palace.jpg"
 },
 "mumbai": {
  "src": "img/mumbai.jpg",
  "author": "Sailko",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Chhatrapati_shivaji_terminus,_esterno_01.jpg"
 },
 "chennai": {
  "src": "img/chennai.jpg",
  "author": "Swarna1311",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Shore_Temple_-Mamallapuram_-Tamil_Nadu_-N-TN-C55.jpg"
 },
 "kolkata": {
  "src": "img/kolkata.jpg",
  "author": "Subhrajyoti07",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Victoria_Memorial_situated_in_Kolkata.jpg"
 },
 "bengaluru": {
  "src": "img/bengaluru.jpg",
  "author": "Chuggingtrails",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Bangalore_Mysore_Maharaja_Palace.jpg"
 },
 "ooty": {
  "src": "img/ooty.jpg",
  "author": "A",
  "license": "CC BY 2.5",
  "page": "https://commons.wikimedia.org/wiki/File:NMR_train_at_Ketti_05-02-26_75.jpeg"
 },
 "chikmagalur": {
  "src": "img/chikmagalur.jpg",
  "author": "Prof",
  "license": "CC BY-SA 2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Chikmagalur,_India._(7793316622).jpg"
 },
 "gokarna": {
  "src": "img/gokarna.jpg",
  "author": "Toby Hudson",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Australian_Pelican_Kioloa.jpg"
 },
 "andaman": {
  "src": "img/andaman.jpg",
  "author": "Harvinder Chandigarh",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Radha_Nagar_beach,_Havelock_Island,_Andamn,_India-_Sun_set_view.jpg"
 },
 "madurai": {
  "src": "img/madurai.jpg",
  "author": "எஸ்ஸார்",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:An_aerial_view_of_Madurai_city_from_atop_of_Meenakshi_Amman_temple.jpg"
 },
 "varanasi": {
  "src": "img/varanasi.jpg",
  "author": "Ken Wieland",
  "license": "CC BY-SA 2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Ahilya_Ghat_by_the_Ganges,_Varanasi.jpg"
 },
 "rishikesh": {
  "src": "img/rishikesh.jpg",
  "author": "KaustubhNayyar",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Rishikesh-Lakshman_Jhula_by_Kaustubh_Nayyar.jpg"
 },
 "delhi": {
  "src": "img/delhi.jpg",
  "author": "Incredible India Portal",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:India_Gate_in_the_Evening.jpg"
 }
};
