/* Generated by tools/fetch-photos.mjs — do not edit by hand. Credits in img/CREDITS.md */
window.PHOTOS = {
 "goa": {
  "src": "img/goa.jpg",
  "author": "iMahesh",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Palolem_Beach,_South_Goa.jpg"
 },
 "munnar": {
  "src": "img/munnar.jpg",
  "author": "Kondephy",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Munnar_Overview.jpg"
 },
 "kochi": {
  "src": "img/kochi.jpg",
  "author": "Timothy A",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Chinese_Fishing_Net_Raising_Birds_Sunrise_Ashtamudi_Kollam_Mar22_A7C_01784.jpg"
 },
 "thekkady": {
  "src": "img/thekkady.jpg",
  "author": "Wouter Hagens",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Periyar_National_Park.JPG"
 },
 "mysuru": {
  "src": "img/mysuru.jpg",
  "author": "Ingo Mehling",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Mysuru_Palace_-_Night_View.jpg"
 },
 "coorg": {
  "src": "img/coorg.jpg",
  "author": "Jyotirmoy",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Tadiandamol_Valley,_Western_Ghats.jpg"
 },
 "hampi": {
  "src": "img/hampi.jpg",
  "author": "iMahesh",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Wide_angle_of_Galigopuram_of_Virupaksha_Temple,_Hampi_(04)_(cropped).jpg"
 },
 "hyderabad": {
  "src": "img/hyderabad.jpg",
  "author": "Bernard Gagnon",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Golconda_Fort_005.jpg"
 },
 "kabini": {
  "src": "img/kabini.jpg",
  "author": "Paul Mannix",
  "license": "CC BY 2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Bengal_Tiger_Karnataka.jpg"
 },
 "wayanad": {
  "src": "img/wayanad.jpg",
  "author": "KSEB",
  "license": "CC BY-SA 2.5",
  "page": "https://commons.wikimedia.org/wiki/File:Banasurasagar_Main_Dam.jpg"
 },
 "varkala": {
  "src": "img/varkala.jpg",
  "author": "Kondephy",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Varkala_beach_from_above.jpg"
 },
 "badami": {
  "src": "img/badami.jpg",
  "author": "Sanyam Bahga",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:BadamiCaves87.JPG"
 },
 "pondicherry": {
  "src": "img/pondicherry.jpg",
  "author": "Matthew T Rader",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:The_Matrimandir_in_Auroville,_Tamil_Nadu,_India.jpg"
 },
 "mumbai": {
  "src": "img/mumbai.jpg",
  "author": "Sailko",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Chhatrapati_shivaji_terminus,_esterno_01.jpg"
 },
 "chennai": {
  "src": "img/chennai.jpg",
  "author": "Swarna1311",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Shore_Temple_-Mamallapuram_-Tamil_Nadu_-N-TN-C55.jpg"
 },
 "kolkata": {
  "src": "img/kolkata.jpg",
  "author": "Subhrajyoti07",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Victoria_Memorial_situated_in_Kolkata.jpg"
 },
 "bengaluru": {
  "src": "img/bengaluru.jpg",
  "author": "Chuggingtrails",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Bangalore_Mysore_Maharaja_Palace.jpg"
 },
 "ooty": {
  "src": "img/ooty.jpg",
  "author": "A",
  "license": "CC BY 2.5",
  "page": "https://commons.wikimedia.org/wiki/File:NMR_train_at_Ketti_05-02-26_75.jpeg"
 },
 "chikmagalur": {
  "src": "img/chikmagalur.jpg",
  "author": "Pavankumar",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:A_scenery_from_bababudan_hill.jpg"
 },
 "gokarna": {
  "src": "img/gokarna.jpg",
  "author": "Gandharva S",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Mirjan_Fort_02.JPG"
 },
 "andaman": {
  "src": "img/andaman.jpg",
  "author": "Harvinder Chandigarh",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Radha_Nagar_beach,_Havelock_Island,_Andamn,_India-_Sun_set_view.jpg"
 },
 "madurai": {
  "src": "img/madurai.jpg",
  "author": "எஸ்ஸார்",
  "license": "CC BY 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:An_aerial_view_of_Madurai_city_from_atop_of_Meenakshi_Amman_temple.jpg"
 },
 "varanasi": {
  "src": "img/varanasi.jpg",
  "author": "Ken Wieland",
  "license": "CC BY-SA 2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Ahilya_Ghat_by_the_Ganges,_Varanasi.jpg"
 },
 "rishikesh": {
  "src": "img/rishikesh.jpg",
  "author": "KaustubhNayyar",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Rishikesh-Lakshman_Jhula_by_Kaustubh_Nayyar.jpg"
 },
 "delhi": {
  "src": "img/delhi.jpg",
  "author": "Incredible India Portal",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:India_Gate_in_the_Evening.jpg"
 },
 "agra": {
  "src": "img/agra.jpg",
  "author": "Yann; edited by Jim Carter",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Taj_Mahal_(Edited).jpeg"
 },
 "jaipur": {
  "src": "img/jaipur.jpg",
  "author": "Jakub Hałun",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:20191219_Fort_Amber,_Amer,_Jaipur_0955_9481.jpg"
 },
 "jodhpur": {
  "src": "img/jodhpur.jpg",
  "author": "Sanhitasinha",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Mehrangarh_Fort_sanhita.jpg"
 },
 "udaipur": {
  "src": "img/udaipur.jpg",
  "author": "user:Flicka",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Udaipur_Lake_Palace.jpg"
 },
 "jaisalmer": {
  "src": "img/jaisalmer.jpg",
  "author": "Gérard Janot",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Jaisalmer_forteresse.jpg"
 },
 "pushkar": {
  "src": "img/pushkar.jpg",
  "author": "Felipe Skroski from Wellington, New Zealand",
  "license": "CC BY 2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Evening_lights_by_the_Pushkar_Lake,_Pushkar.jpg"
 },
 "ranthambore": {
  "src": "img/ranthambore.jpg",
  "author": "THerrington",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Ranthambore_National_Park.JPG"
 },
 "amritsar": {
  "src": "img/amritsar.jpg",
  "author": "Shagil Kannur",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:The_Golden_Temple_of_Amrithsar_7.jpg"
 },
 "shimla": {
  "src": "img/shimla.jpg",
  "author": "No machine-readable author provided",
  "license": "CC BY 2.5",
  "page": "https://commons.wikimedia.org/wiki/File:KSR_Steam_special_at_Taradevi_05-02-13_56.jpeg"
 },
 "manali": {
  "src": "img/manali.jpg",
  "author": "Harvinder Chandigarh",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Solang_Valley_,Manali,_Himachal_Pardes,_India.JPG"
 },
 "dharamshala": {
  "src": "img/dharamshala.jpg",
  "author": "Rignam Wangkhang",
  "license": "CC BY 2.0",
  "page": "https://commons.wikimedia.org/wiki/File:McLeod_Ganj_Dharamkot_Dharmsala_Himachal_Pradesh_India_April_2014.jpg"
 },
 "leh": {
  "src": "img/leh.jpg",
  "author": "Aksveer",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Thikse_Monastery_.jpg"
 },
 "corbett": {
  "src": "img/corbett.jpg",
  "author": "Soumyajit Nandy",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Bengal-Tiger_Corbett_Uttarakhand_Dec-2013.jpg"
 },
 "khajuraho": {
  "src": "img/khajuraho.jpg",
  "author": "PLBechly",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:1_Khajuraho.jpg"
 },
 "bandhavgarh": {
  "src": "img/bandhavgarh.jpg",
  "author": "This Image was created by User:Archith",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Tigress_in_Bandhavgarh_NP.jpg"
 },
 "kanha": {
  "src": "img/kanha.jpg",
  "author": "Davidvraju",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Tiger_Kanha_National_Park.jpg"
 },
 "aurangabad": {
  "src": "img/aurangabad.jpg",
  "author": "No machine-readable author provided",
  "license": "CC BY 2.5",
  "page": "https://commons.wikimedia.org/wiki/File:Ajanta_(63).jpg"
 },
 "kutch": {
  "src": "img/kutch.jpg",
  "author": "Superfast1111",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Rann_of_Kutch_-_White_Desert.jpg"
 },
 "darjeeling": {
  "src": "img/darjeeling.jpg",
  "author": "Arne Hückelheim",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:DarjeelingTrainFruitshop_(2).jpg"
 },
 "gangtok": {
  "src": "img/gangtok.jpg",
  "author": "Ashinpt at enwiki",
  "license": "CC BY-SA 3.0",
  "page": "https://commons.wikimedia.org/wiki/File:Kangch-Goechala.jpg"
 },
 "kaziranga": {
  "src": "img/kaziranga.jpg",
  "author": "Diganta Talukdar",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Beauty_of_Kaziranga_National_Park.jpg"
 },
 "shillong": {
  "src": "img/shillong.jpg",
  "author": "Arshiya Urveeja Bose",
  "license": "CC BY 2.0",
  "page": "https://commons.wikimedia.org/wiki/File:Living_root_bridges,_Nongriat_village,_Meghalaya2.jpg"
 },
 "puri": {
  "src": "img/puri.jpg",
  "author": "Subham9423",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Konarka_Temple.jpg"
 },
 "thanjavur": {
  "src": "img/thanjavur.jpg",
  "author": "Original:  Rainer Halama",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Brihadisvara_Temple_during_Maha_Shivaratri-WUS03611_(edit).jpg"
 },
 "kodaikanal": {
  "src": "img/kodaikanal.jpg",
  "author": "KARTY JazZ",
  "license": "CC BY-SA 4.0",
  "page": "https://commons.wikimedia.org/wiki/File:Boating_in_Kodaikanal_Lake_with_Mist.jpg"
 }
};
