/* Generated by tools/fetch-photos.mjs — do not edit by hand. Credits in img/CREDITS.md */
window.PHOTOS = {
 "goa": {
  "src": "img/goa.jpg",
  "author": "D'Souza and Paul Studio",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Basilica_of_Bom_Jesus,_Old_Goa_(ca._1870).jpg"
 },
 "munnar": {
  "src": "img/munnar.jpg",
  "author": "No machine-readable author provided. Pradeepvkrishna assumed (based on copyright claims).",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:TEA_GARDEN_MUNNAR.JPG"
 },
 "kochi": {
  "src": "img/kochi.jpg",
  "author": "Yourusernamewillbepublic2",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:Fort_Kochi_Hotel.jpg"
 },
 "thekkady": {
  "src": "img/thekkady.jpg",
  "author": "Jonathanawhite at English Wikipedia",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Periyar_National_Park_-_2.JPG"
 },
 "mysuru": {
  "src": "img/mysuru.jpg",
  "author": "Emilien Lebourgeois",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Mysore_Chamundi_Hills_(51057117476).jpg"
 },
 "coorg": {
  "src": "img/coorg.jpg",
  "author": "No machine-readable author provided. Nmadhubala assumed (based on copyright claims).",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Abbey_Falls_Coorg.jpg"
 },
 "hampi": {
  "src": "img/hampi.jpg",
  "author": "Ms Sarah Welch",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:071017_Vitthala_temple_complex_aerial_view,_Hampi_Karnataka.jpg"
 },
 "hyderabad": {
  "src": "img/hyderabad.jpg",
  "author": "Kavali Chandrakanth KCK",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:Chowmahalla_Palace_Hyderabad_Tealagana_India.jpg"
 },
 "kabini": {
  "src": "img/kabini.jpg",
  "author": "Forestowlet",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:Kabini_river.JPG"
 },
 "wayanad": {
  "src": "img/wayanad.jpg",
  "author": "Apletters",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:Chembra_Peak.JPG"
 },
 "varkala": {
  "src": "img/varkala.jpg",
  "author": "P.K.Niyogi",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Kovalam_Lighthouse_Beach.JPG"
 },
 "badami": {
  "src": "img/badami.jpg",
  "author": "Haneeshkm",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:Badami_caves_Cave_One_(15).jpg"
 },
 "pondicherry": {
  "src": "img/pondicherry.jpg",
  "author": "(WT-en) Jarrettman at English Wikivoyage",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Matrimandir,_Auroville,_Tamil_Nadu,_India_(2004).jpg"
 },
 "goldentriangle": {
  "src": "img/goldentriangle.jpg",
  "author": "Shivansh2401",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:Taj_Mahal_in_the_morning_2023.jpg"
 },
 "rajasthan": {
  "src": "img/rajasthan.jpg",
  "author": "Knowledge Seeker",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Jodhpur_from_Mehrangarh_Fort.jpg"
 },
 "mumbai": {
  "src": "img/mumbai.jpg",
  "author": "Mitchell Mark Gilbert",
  "license": "Public domain",
  "page": "https://commons.wikimedia.org/wiki/File:Mumbai_Arabian_Sea_Night_View-_A_Reflection_of_Infrastructure_Brilliance.jpg"
 },
 "chennai": {
  "src": "img/chennai.jpg",
  "author": "Abinayasekar357",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:Marina_beach_Chennai.jpg"
 },
 "kolkata": {
  "src": "img/kolkata.jpg",
  "author": "K.Venkataramana",
  "license": "CC0",
  "page": "https://commons.wikimedia.org/wiki/File:Victoria_Memorial,_Kolkata,_West_Bengal_(1).jpg"
 }
};
